### ISSUE TITLE
Replace RTK slice with React Context  to eliminate the need for createAgreements slice

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1047]
### Goals

Refactor create agreement workflow state, look for code/components that can be reused, etc. All state for the workflow should use React Context.

### Tasks
- [x] ~~refactor steps into their own components~~
- [x] use localState where possible
- [x] ~~elevate reusable comps~~
state refactor with [Reducer and Context pattern](https://react.dev/learn/scaling-up-with-reducer-and-context)
  - [x] Step One
  - [x] Step Two
  - [x] Step Three
- [x] ~~replace useEffects with global state from RTK~~
- [x] remove CreateAgreements slice
- [x] fix/update unit-test and e2e
- [x] update the ADR for when it would make sense to use this implementation vs. RTK?
