### ISSUE TITLE
Define upcoming user research needs

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#107]
### Goals
* As a project team, we need help prioritizing the user research we will need to do to build out OPS so we know what to focus on next.
* As a project team, we need a user research plan that addresses the objectives prioritized above so that we can craft a staffing request or microrequest for support and execute on the plan.

### Tasks
- [ ] Identify research areas and priorities
- [ ] Define questions in priority research area(s)
- [ ] Sketch out rough idea of research activities
- [ ] Sketch out rough idea of protocols

### Additional Context
* Related activities that might fall out of or be impacted by this work:
   * Revising the staffing request or writing a new microrequest
   * User engagement / communication plan (#18 )

**Comment by ninamak** [comment]
Updated based on our conversation!
