### ISSUE TITLE
Refine AirTable Prototype: CANs

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#108]
### Goals
To prepare for writing user stories for our first slice:
* Have a better sense of which fields are needed on which tables to enable budget reporting.
* Better define the field types and relationships.
* Better understand how existing data could/could not be used to populate our new tables.
* Identify open questions that Sheila can't answer/resolve on her own

Focus for this card will be on the CANs table, since that's where the budget process starts.

### Tasks
- [x] Work with Sheila to start populating the AirTable prototype
- [x] Document any user stories or pain points learned
- [x] MAP existing data to the prototype data scheme
- [x] Document any open questions that remain
- [x] Share with team

### Additional Context
- We are using the building of this prototype as a way to more precisely understand and define user needs.  We will need to refine the translation of user needs to implementation details in conjunction with engineers.  

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_

**Comment by ninamak** [comment]
Notes on the data model and user stories [here](https://docs.google.com/spreadsheets/d/15MpMpSZWMhqMTJJ2akFdtuJy6f6iVJJriSmQ4ERAQ7E/edit#gid=1780400632)

**Comment by amymok** [comment]
@ninamak Is this also the task to gather production-like data that will look like MAPS1.0 data structure?

**Comment by ninamak** [comment]
[CAN info here](https://docs.google.com/spreadsheets/d/15MpMpSZWMhqMTJJ2akFdtuJy6f6iVJJriSmQ4ERAQ7E/edit#gid=1780400632).  Includes info about CANs, user stories, pain points, the data model, data sources, and open questions.

Prototype in AirTable for [CANs](https://airtable.com/tblC1gcLbcE5wou4Z/viwkZHevQYTEb1rRF?blocks=hide), which also required tables for [Personnel](https://airtable.com/tblPe0l9XDDPor9ED/viwzRcyxs9S8Ikn3C?blocks=hide) and [Agencies](https://airtable.com/tblGGRgffwAm6oV3h/viw42XXeFHzgoXwuB?blocks=hide).
