### ISSUE TITLE
Strategic Research and Planning for User Alerting & Notifications

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1093]
### Goals
* Determine what the approach and intent should be to users getting notified and alerted to things they need to be aware of and/or take action on. Nothing specific to any one situation but a larger overall mindset.

### Tasks
- [x] Research on design patterns, inspiration, ideas
- [x] Outline possible alerts, notifications needed (what we know so far)
- [x] Explore design options
- [x] Share designs with team for feedback
- [x] Share designs with stakeholder for feedback
- [x] Refine design based on feedback

### Additional Context
* Not intending to replace individual scenario-specific needs

### Resources
*

**Comment by kimschulke** [comment]
Andressa has created 3 options to review :) Maybe we can all take a look on Monday during Refinement.

**Comment by kimschulke** [comment]
Reviewed and edited designs with developers on 6/19. Planning to review with OPRE next. Design in Figma here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=4282%3A118439&t=m3FDyJ79QFAPWltj-1

**Comment by kimschulke** [comment]
Post MVP ideas include

- Looking into whether or not users want to clear individual notifications vs all (currently designed to clear all only).
- Possibility of adding tabs for All vs General vs Requests (might also show requests/to-dos on a home/dashboard

**Comment by kimschulke** [comment]
Reviewed design with OPRE on 6/22 - Design is ready for development!

**Comment by kimschulke** [comment]
Keep in mind, user-specific tasks and to-dos will display on a home page / dashboard which we have not yet designed

**Comment by jonnalley** [comment]
review on 6/23
