### ISSUE TITLE
Break down "first" user story: CANs

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#111]
### Goals
* Break down our overarching "first" user story into more specific user stories so that we can begin to discuss solutions and first steps
* Focus for this card will be CAN management, since that's the beginning of the budget process.

### Tasks
- [x] Document more granular user stories
- [x] Identify how those user needs are being met currently
- [x] Compile pain points for each

### Additional Context
* ["First" user story](https://docs.google.com/presentation/d/1BxbDWAz5Ay2fnHSPEKa9votY-LoAYiwqXWxOBr6EwnY/edit#slide=id.ge5fd088427_0_148)
* ["Next"](https://docs.google.com/presentation/d/1BxbDWAz5Ay2fnHSPEKa9votY-LoAYiwqXWxOBr6EwnY/edit#slide=id.ge5fd088427_0_183) and ["Later"](https://docs.google.com/presentation/d/1BxbDWAz5Ay2fnHSPEKa9votY-LoAYiwqXWxOBr6EwnY/edit#slide=id.ge5fd088427_0_158) user story
* [Lifecycle of a contract](https://docs.google.com/presentation/d/1BxbDWAz5Ay2fnHSPEKa9votY-LoAYiwqXWxOBr6EwnY/edit#slide=id.ge5fd088427_0_168)

**Comment by ninamak** [comment]
Created [this spreadsheet](https://docs.google.com/spreadsheets/d/15MpMpSZWMhqMTJJ2akFdtuJy6f6iVJJriSmQ4ERAQ7E/edit?usp=drive_web&ouid=111990553817353771463) to structure the info I'd like to be able to capture.  May need to switch up formats when it comes to actually populating.

**Comment by ninamak** [comment]
Compiling notes [here](https://docs.google.com/document/d/1ZfdtFVgrXBwxWsH2ur_JtIcy5EslvlZYzqW2rPnZz-k/edit#heading=h.jx6c4p7y1xff).  Synthesizing [here](https://docs.google.com/spreadsheets/d/15MpMpSZWMhqMTJJ2akFdtuJy6f6iVJJriSmQ4ERAQ7E/edit#gid=1780400632).

**Comment by ninamak** [comment]
[Info on CANS compiled here](https://docs.google.com/spreadsheets/d/15MpMpSZWMhqMTJJ2akFdtuJy6f6iVJJriSmQ4ERAQ7E/edit#gid=1780400632).  Includes background on what are CANs and why do they matter, user stories, and the proposed data model.
