### ISSUE TITLE
Refine "Lifecycle of a Contract"

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#112]
### Goals
* _What outcome(s) we are hoping to accomplish_

### Tasks
- [ ] Add CAN Management workflows
- [ ] Verify details with Sheila
- [ ] Augment with the systems/screens being used
- [ ] Identify areas where we need more info
- [ ] Create card to work with designer to turn into a visualization?

### Additional Context
* I wonder if we should update this to be a more holistic map to "Follow the Money."  

### Resources
* [Lifecycle of a Contract](https://app.mural.co/t/gsa6/m/gsa6/1626978306340/7b440640a5a2244ef06ac28f34f0347df76d2e67?sender=ninamak9326)
