### ISSUE TITLE
Develop an overview of the overall system's "To Be" state

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#116]
### Goals
* As a project team, we'd like to have an overarching understanding of what the new system will ultimately be expected to do so that:
   * We can break down the work and develop our roadmap
   * We always know what our work is laddering up to
   * We don't lose sight of why this work is important as we implement tiny details 

### Tasks
- [X] Review interview notes and previous synthesis
- [x]  Brain dump of all the jobs MAPS has to do
- [x] Align on a common definition for "project"
- [x] Understand the relationship between projects and agreements
- [x] Diagram the relationships between different elements in MAPS & answer questions that arise
- [x] Create a storyboard of the full first slice of OPS
- [ ] Create a simplified visual (site map or other) to represent the to-be state for OPS

### Additional Context
* This goes hand in hand with #119 

### Resources
* Details about the existing sitemap and jobs that MAPS has to do are contained within [this mural](https://app.mural.co/t/gsa6/m/gsa6/1619016578440/6a6f44966ee3600e2d3e6659cd1f5245940e10d7?sender=ninamak9326) and [this mural](https://app.mural.co/t/gsa6/m/gsa6/1618233506826/1cc55ed22828f8c8e780e34510c116570380ac6f?sender=ninamak9326)
* The [Lifecycle of a Contract](https://app.mural.co/t/gsa6/m/gsa6/1626978306340/7b440640a5a2244ef06ac28f34f0347df76d2e67?sender=ninamak9326) is a good reference for a main subset of the jobs OPRE needs the new system to support.

**Comment by juliaklindpaintner** [comment]
I think this goes hand in hand with #119 and a new goal of doing some site mapping. 

- [x] Review interview notes and previous synthesis
- [ ] Document existing sitemap
- [ ] Braindump of all the jobs MAPS has to do 
- [ ] Organize along workflows (to the extent possible)
- [ ] Come up with 1+ potential new sitemaps

**Comment by ninamak** [comment]
Updated!

**Comment by ninamak** [comment]
[Here is a story board](https://app.mural.co/t/gsa6/m/gsa6/1630248640188/3105c3b385f17e2cedbc6c5bff2111ba59785520?sender=ninamak9326) depicting the elements that the new system will contain in the "first slice," as well as some of the functionality that's envisioned down the road.

**Comment by juliaklindpaintner** [comment]
@ninamak I don't know if it matters, but I'd be inclined to change the last three checkboxes in the original ticket to something like: 
- [x] Align on a common definition for "project"
- [x] Understand the relationship between projects and agreements
- [x] Diagram the relationships between different elements in MAPS & answer questions that arise
- [x] Create a storyboard of the full first slice of OPS
- [ ] Create a simplified visual (site map or other) to represent the to-be state for OPS

Unless of course you've captured some of that work somewhere else?

**Comment by juliaklindpaintner** [comment]
[Here is the mural](https://app.mural.co/t/gsa6/m/gsa6/1631633871588/53a7b80180aa8f340f80adafc1a69868c72125a3?sender=julialindpaintner1638) with diagrams showing the relationships between different elements in MAPS

**Comment by ninamak** [comment]
@juliaklindpaintner thanks for suggesting those changes!  i did notice that our tasks needed updating but hadn't gotten around to doing anything about it.  these are great!
