### ISSUE TITLE
Remove agreement-level statuses from existing models and pages

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1183]
### Goals
* Remove any UX, frontend validation, backend logic or validation, data models, or anything else  that assumes, implies, or enforces a "status" on the agreement or contract level. Recent research and determinations are such that statuses should only live at the budget line object.

### Tasks
- [x] If applicable, alter various components of the portfolio and research project page(s) (and models, etc..) that reference statuses for agreements and 
- [x] Update agreements listing page to remove the column for agreement status
- [x] Update logic and handling for creating new agreements such that a new agreement shouldn't try to set a status and the concept is removed entirely.
- [x] Update Gherkin rules for references to agreement-level statuses
- [x] Update e2e and cypress tests
- [x] Update the backend data model to remove the attribute/column

### Additional Context
* See figma for references and examples

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_
