### ISSUE TITLE
Supporting multiple authn providers

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1206]
### User Story
As an OPS user, I may need to log in with either AMS or login.gov temporarily until a single provider is in place so that I can get into OPS regardless of environment or my PIV status

### Acceptance Criteria
- [x] User can choose to log in either with login.gov or HHS's AMS system before proceeding on to the respective interface for authentication. 

-----------------------------------------

### Tasks
- [x] Rework backend to support both auth providers
- [x] Address redirect: /login vs. /
- [x] Update tests

### Definition of Done Checklist
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added

### Additional Context & Resources

**Comment by jonnalley** [comment]
@tdonaworth I feel like the intended effort behind this is "done" ?  Presuming you don't have a differing view, would you run through the DoD checklist when you can and check things off when ready?  Thanks!
