### ISSUE TITLE
Strategic Research on Executing a contract

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1225]
### Goals
* Understand more about OPRE business processes involved in the various stages of executing
* Understand what deliverables OPRE staff need to provide to progress a contract through various executing status(es)
* Understand what approvers need to see in order to approve a contract moving through executing status(es)
* Understand what milestones occur in the life of a contract during execution and until it reaches `obligated` status

### Tasks
- [ ] Talk with and get info from relevant OPRE staff or others to whom they delegate
- [ ] Review research from #993
- [ ] Explore design options and review internally
- [ ] Explore design options with OPRE staff

### Additional Context
* 

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_

**Comment by kimschulke** [comment]
I'm going to move the design exploration to the specific user stories related to the executing status/procurement process
