### ISSUE TITLE
As a dev, I want to run the Django server locally

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#123]
### Goals

As a dev, I want to be able to run the Django server locally.

### Definition of Done 

All three engineers can run the Django server on their local machines using the same documented commands.

### Tasks

- [x] Determine the right command to run the Django server locally and document
- [x] Debug any issues that crop up with the application locally
- [x] Potentially: add `settings.py` override for running the application server locally

**Comment by alexsoble** [comment]
Updating this card based on some developer conversation

**Comment by alexsoble** [comment]
Ooooh, we might want to look at https://buildpacks.io/, https://github.com/buildpacks/pack for this. Could let developers run the server locally using buildpacks very similar to the ones that will run on cloud.gov.

**Comment by carjug** [comment]
@alexsoble @amymok ready for review! feel free to pull down and test out according to the instructions in the README.

**Comment by alexsoble** [comment]
@carjug Excellent, pulling it down and testing this out now!
