### ISSUE TITLE
DEVEX: Automagically add reviewers on PR to main

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1253]
### Goals
* Improve the quality of life for developers by automating the review process for PRs to the main branch.

### Tasks
- [ ] Add a developer group to the repository.
- [ ] Configure the repository to automatically add the developer group as a reviewer for all PRs to the main branch.
- [ ] Test the configuration to ensure that the developer group is being added as a reviewer for all PRs to the main branch.

### Additional Context
* The developer group should be composed of experienced developers who are familiar with the codebase and can provide valuable feedback on PRs.
* The automated review process will help to ensure that all PRs to the main branch are reviewed by a qualified developer before being merged.
* The configuration should be easy to maintain and update as the developer group changes over time.

### Resources
* [GitHub documentation on adding reviewers to a pull request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/requesting-a-pull-request-review)

**Comment by tdonaworth** [comment]
This can also be done with the `owners` file, assuming we want our team to be the owners, etc.

**Comment by jonnalley** [comment]
@johndeange did this a long time ago
