### ISSUE TITLE
Frontend handling of other failures

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1262]
### User Story
As an OPS user, I want to be gracefully aware of miscellaneous errors so that I'm not confused or frustrated. 

### Acceptance Criteria
- [ ] Users will see an appropriate message when there’s been a failure to store or retrieve information not related to a user’s input
- [ ] The application will not display developer-facing or default error messages and will instead gracefully catch and present errors

-----------------------------------------

### Tasks
- [ ] Support 400-series and 500-series errors in the frontend that are sent from the backend
- [ ] Determine what should be done, for scenarios that break a logic rule, but can’t be remedied by the user.

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_

**Comment by fpigeonjr** [comment]
We have implemented a redirect to a generic error page if we experience server issues and can be tested with the simulated error prop.

**Comment by fpigeonjr** [comment]
We should add a React Error Boundary to:
* Improve application stability by gracefully handling component-level errors
* Provide users with a fallback UI when errors occur instead of crashing the app
* Enable better error tracking and recovery mechanisms

### Resources from Grok
* [React Error Boundaries Documentation](https://reactjs.org/docs/error-boundaries.html)
* [React Component Lifecycle](https://reactjs.org/docs/react-component.html#componentdidcatch)
* [Error Handling in React Best Practices](https://www.smashingmagazine.com/2020/08/error-handling-react-hooks/)

**Comment by fpigeonjr** [comment]
@jonnalley @johndeange we may to prioritize this story now that we are in PROD

**Comment by jonnalley** [comment]
@fpigeonjr you could argue for doing all that as part of #3466 which is in this sprint IIRC
