### ISSUE TITLE
As a dev, I want to run the automated test suite locally

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#127]
### Goals

As a dev, I want to be able to run the automated test suite locally.

### Definition of Done 

All three engineers can run an (empty/stubbed out) test suite on their local machines using the same documented commands.

### Tasks

- [x] Choose a test runner
- [x] Write a simple test that passes or fails
- [x] Document the command to run the tests
- [ ] Potentially: `settings.py` override for running the test suite

**Comment by alexsoble** [comment]
Updated this based on some developer conversation
