### ISSUE TITLE
[4] As a dev, I want to manage Python dependencies using Pipenv

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#132]
### Goals

Set up Python dependency management using Pipenv 

### Tasks
- [x] Switch from using pip for Python dependencies over to Pipenv
- [x] Document how to add a new Python dependency using Pipenv

### Acceptance Criteria
- [x] Verify the app works locally
~~- [ ] Verify the app works on cloud.gov~~

### Resources

https://blog.dennisokeeffe.com/blog/2020-07-04-abcs-of-pipenv

### Notes

This follows #124.
