### ISSUE TITLE
[4] View agencies

### ISSUE THREAD

**Issue by amymok** [HHS/OPRE-OPS#133]
### User Story
As a user, I will want to know the agency that provided CAN money and whether they need to authorize requisitions that use that CAN.  

### Conditions of Acceptance
- [x] I can use Django Admin in the dev environment to see a list of agencies (based on dummy data).
- [ ] It would be ok if the PM can only view the interface on a dev's local.

### Tasks
- [x] Implement Agency model based on [Agency tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=0)
- [x] Populate with dummy data from AirTable [Agencies tab](https://airtable.com/tblGGRgffwAm6oV3h/viw42XXeFHzgoXwuB?blocks=hide)
- [x] Enable Django Admin interface to display the Agency table

### Additional Context

- [Database Models Spreadsheet](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#)
- [ER Diagram](https://docs.google.com/drawings/d/106BT0UIW_-zmocmNWMoGbe4nVmHGU1fYfsQWnTccsiI/edit)

### Resources
* #91

**Comment by alexsoble** [comment]
@carjug is picking this one up, we're excited to move into implementation world! 🎉

**Comment by ninamak** [comment]
@carjug I tried to update this card to include a user story and CoAs, though it's a little awkward since this is more of a technical task in support of a user story captured elsewhere.  It's not intended to change anything about what work you were planning to do, but let me know if it does!

**Comment by carjug** [comment]
@ninamak It's all clear to me!

**Comment by carjug** [comment]
Ready for review @alexsoble @amymok

**Comment by alexsoble** [comment]
Reviewed and approved with @ninamak synchronously! 👍 👍 🚀
