### ISSUE TITLE
[4] View roles

### ISSUE THREAD

**Issue by amymok** [HHS/OPRE-OPS#134]
### User Story
* As a user, I want to see a list of Roles as they relate to CAN Management (realistic-looking dummy data).
* As a PM, I want to use this view to facilitate conversations about OPRE roles vs user types.

### Conditions of Acceptance
- [x] I can use Django Admin in the dev environment to see a list of roles (based on dummy data).
- [ ] It would be ok if the PM can only view the interface on a dev's local.

### Tasks
- [x] Implement Role model based on [Role tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=347850494)
- [x] Populate with dummy data
   - Project Officer, Team Leader, Division Director, Budget Team
- [x] Enable Django Admin interface to display the Roles table

### Additional Context

- [Database Models Spreadsheet](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#)
- [ER Diagram](https://docs.google.com/drawings/d/106BT0UIW_-zmocmNWMoGbe4nVmHGU1fYfsQWnTccsiI/edit)

### Resources
* #91

**Comment by alexsoble** [comment]
LGTM! 👍

**Comment by alexsoble** [comment]
FWIW my understanding from our meeting with @ninamak this morning was that this work is 👍 👍 and good to go from her POV!
