### ISSUE TITLE
[4] View people

### ISSUE THREAD

**Issue by amymok** [HHS/OPRE-OPS#136]
### User Story
* As a user, I want to see a list of people and their role(s) as they relate to CAN Management (realistic-looking dummy data).

### Conditions of Acceptance
- [x] I can use Django Admin in the dev environment to see a list of people (based on dummy data).
- [ ] It would be ok if the PM can only view the interface on a dev's local.

### Tasks
- [x] Implement Person model based on [Person tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=1998743844)
- [x] Populate with [dummy data](https://airtable.com/tblPe0l9XDDPor9ED/viwzRcyxs9S8Ikn3C?blocks=hide)
- [x] Enable Django Admin interface to display the Person table
- [x] Add local test user to fixture data in order to make local development faster

### Additional Context
- [Database Models Spreadsheet](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#)
- [ER Diagram](https://docs.google.com/drawings/d/106BT0UIW_-zmocmNWMoGbe4nVmHGU1fYfsQWnTccsiI/edit)
- Blocked by #134 and #135

### Resources
* #91

**Comment by alexsoble** [comment]
@carjug Following up on @ninamak's suggestion from this morning, how about we add a Task here saying something like:

"Add local test user to fixture data in order to make local development faster"?

**Comment by carjug** [comment]
@alexsoble fine by me!

**Comment by carjug** [comment]
Ready for review! @amymok @alexsoble

**Comment by alexsoble** [comment]
Hmmmm, I think we still need @ninamak's review and sign-off tomorrow though? I'll re-open and add Nina's label.

**Comment by carjug** [comment]
@alexsoble ohh yeah, it auto-closed the ticket because the PR was linked.

**Comment by alexsoble** [comment]
Yep!

**Comment by carjug** [comment]
Add role in display

**Comment by carjug** [comment]
Hey @ninamak, we fixed the bug in not displaying the roles on the Person display list. Will demo tomorrow for your final sign off!
