### ISSUE TITLE
Azure DevOps beginnings

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1372]
### Goals
* Do we want to re-architect anything for moving into Azure
* IaC exploration
* Determine how agnostic we want to remain, versus buying into "Azure" services (?)
* Pilot in Flexion Azure account

### Tasks
- [x] Pre-planning and architecting
- [x] Evaluate what IaC to use? Terraform? Bicep? another?
- [x] how to manage state, if applicable ?
- [x] Terraform - Labelling/Naming Module
- [x] Terraform - Bootstrap Terraform State (Shell Script) 
- [x] Terraform - Create a version TF Context module w/ examples. 
- [x] Handle schema creation and other bootstrapping needs for Azure Database
  - [x] Address situation of GH runners needing to talk to the Azure instance
- [x] Terraform - Core Project Resources (Private)
- [x] Terraform - Deployments (AppGW? Update backend)
- [x] Determine a reasonable PoC Architecture in Azure
- [x] Update the current pipelines to deploy to Azure (use any IaC that we build for this)

**Comment by jonnalley** [comment]
2/19
