### ISSUE TITLE
Determine if Agreement Total should include Draft BLIs

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1378]
### Goals
* Decide if Agreement Total should include drafts or not

If we do include drafts, add toggle component to necessary pages or utilize filter - need to validate with users

### Tasks
- [x] Discuss and consider options
- [x] Validate with additional users, if needed (or pin for later testing)
- [x] Ensure consistency across the various pages
* Agreement List Page
* Project Details
* Portfolio - Project List

**Comment by jonnalley** [comment]
reviewed this with OPRE this afternoon
