### ISSUE TITLE
Draft initial comms to OPRE staff about OPS

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#140]
### Goals
* Draft initial communications to OPRE staff about OPS ahead of Oct 6 All Staff share out.

### Tasks
- [x] Draft Launch message
- [x] Draft Oct 6 reminder meesage
- [x] Share with Sheila for feedback
- [x] Share with Emily and Camille for feedback

### Additional Context
* #18

**Comment by ninamak** [comment]
Sheila suggests drafting the first set of messages together so Emily and Camille can edit at once and ensure continuity.
* Launch announcement
* Reminder about Oct 6 mtg
