### ISSUE TITLE
Math on fees is wrong somewhere & Changing procurement shop on draft agreement issues

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1404]
Two issues were identified by @jonnalley:

* When adding a simple new contract with a procurement shop that charges fees, the amount shown in the agreement list has one (correct) value for the total of the contract, but when you look at the budget lines tab in the agreement details, a different (incorrect) total is shown. 
* When a user changes the procurement shop on a draft agreement (contract) to one with a differing fee, the total dollar amount is then impacted for the overall agreement and its budget lines and that's reflected on the agreement list correctly but not in the BL details.

## Expected Behavior
* I would expect that if a given calculation is attempting to include the fees on a contract's BL(s), that it would calculate and render it correctly and for there to be testing in place to check for that.
* Dollar amounts for BLs and the agreement total should be both accurate and consistent

## Current Behavior
* It appears that the math for the total amount column on the agreement list is not correct.
* On the agreement list page, the total column is updating to reflect the new amount with the new procurement shop's fees. The budget lines tab of the agreement detail is not updating it seems. 

## Possible Cause
Math is not being done correctly and testing suites evidently not catching this scenario

## Steps to Reproduce

* [Private Zenhub Video 1](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdms1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--946bac63d0d2102b1ab2b9afc490ab0a4c313bdd/Screen%20Recording%202023-08-25%20at%2003.00.12.mov)
* [Private Zenhub Video 2](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdjQ1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6624e122d9c0bd59282a691bbc938f846e2436a6/Screen%20Recording%202023-08-25%20at%2003.09.33.mov)

## Context
This was seen in the staging environment as of 8/24 logged in as an admin user.  Test data really should get checked and verified for accuracy as well.

### Tasks

* [x] Update all BLIs <= PLANNED with PSC fee percentage when PSC is changed for Agreement.
* [x] Prevent BLIs > PLANNED from changing their PSC fee percentage when PSC is changed for Agreement.
* [x] Ensure that Agreement-level total uses correct PSC fee percentage for each BLI in its calculation.
* [x] Prevent PSC from being changed for the Agreement if even 1 BLI is IN EXECUTION or higher.
* [x] Ensure PLANNED BLIs get changed to DRAFT if PSC fee percentage is changed.
* [x] ~Make Gherkin feature/business rules to validate all of this.~ - There already is Gherkin rules for testing these things.
* [x] Ensure that all test data BLIs and Agreements are aligned for the PSC fees. Fix tests as necessary.

**Comment by xlorepdarkhelm** [comment]
Further context I found: Whenever we save the BLIs after they are edited, the procurement shop fees are resubmitted as a change. They are changing by being 1/100th of what they were before. So, if a fee was, for example, 0.05, the new fee being submitted is changed to 0.0005.

**Comment by xlorepdarkhelm** [comment]
I believe that this bug and https://github.com/HHS/OPRE-OPS/issues/1405 might be the same problem.

**Comment by xlorepdarkhelm** [comment]
It appear that this might have to do with the psc fee being stored in each BLI directly, and they are not being updated whenever the PSC is changed for the Agreement.

**Comment by xlorepdarkhelm** [comment]
It looks like this is the fix we need:

1. If BLIs are in DRAFT, and the PSC fee for the agreement is different than what we have for the BLI, the BLI needs to change to match the Agreement.
2. If the BLI is in a state above DRAFT, *DO NOT CHANGE* the PSC fees for that BLI ever (Business rule needs to exist for this).
3. Agreement-level total needs to be using the PSC fees for the individual BLIs in its calculation.

**Comment by jonnalley** [comment]
A twist on 2: Our current understanding is:

Once any BLI on the agreement is > `Planned`, procurement shop and fees are locked

So changing procurement shop with BLs in draft and planned is fine, but the procurement shop ought not/can’t change once the first BL on the agreement moves to `executing`

The procurement shop can change if all BLs are in `planned` (or draft) but doing so should be updating any statically stored percentages/amounts for BLs and as you know from 1000/1001, those BLs would go back to `draft`.

**Comment by xlorepdarkhelm** [comment]
Merged #1405 into this, restructured it a bit, came up with tasks to complete.

**Comment by jonnalley** [comment]
9/25
