### ISSUE TITLE
Endpoint Expansion via "expand_on={object}" for all Endpoints.

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#1411]
###  Goals
* In order to reduce the need for subsequent queries for data we already know, have a feature to expend associated objects for endpoints.

### Acceptance Criteria
- [ ] Hitting the /budget-line-items endpoint with query parameters like `?expand_on=can` should return back the `CAN` object, expended in the json results.
- [ ] Objects that do NOT have the `?expand_on={object}` should not `eager` load those objects (potentially breaking)
- [ ] Unit tests should capture these.
- [ ] OpenAPI.spec should reflect these queryable changes, and clearly document which objects can be expanded.

-----------------------------------------

### Tasks
- [ ] PoC the ability to do this on a single endpoint like `/bli`
- [ ] `DRY` it out, by baking this into the base_view (`OpsMethodView`)? 
- [ ] Create unit tests
- [ ] Create e2e tests
- [ ] Update openapi.yml documentation

**Comment by johndeange** [comment]
Context: Team asked my opinion on this task -

Cons:

1. I think this would arguably break REST, e.g. the object schema/representation would change based on the query parameters.
2. It would add more complexity to the API.

If this pattern/architecture was implemented I think it should probably be developed as flask middleware of some kind since it would not be dependent on any OPS business entity/rules (it would be dynamic)

The alternative is to continue our current path and expand related objects as needed or possibly but them in a `_meta_` field.

**Comment by johndeange** [comment]
Another option would be to have a `?depth=1` query parameter as middleware/flask extension or implemented per endpoint

Options for solving the frontend problem:

1. Standard REST - make multiple calls to backend to GET Agreement, CAN, etc for each BLI
2. Load all related objects with RTK Query
3. Implement additional `@property` as needed
4. Implement middleware for `?expand_on=`
5. Implement middleware for `?depth=`

**Comment by jonnalley** [comment]
@tdonaworth says this still highly in debate. discuss and document please. :-)

**Comment by tdonaworth** [comment]
No expansion, make your additional calls (based on ID for now).
As for authorization, default to "safe" responses, and authz will need to be updated for non-safe responses.
"safe" == data that is not deemed sensitive, kinda, maybe?
