### ISSUE TITLE
Strategy & prep to migrate data from MAPS to OPS

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#1420]
### Goals

As an OPS user, I want to have access to all the data, both current and historical, stored in MAPS in OPS.

### Tasks
- [x] Develop overall architecture/plan for the migration
- [x] Develop model of MAPS DB (using spreadsheet until we have access to the actual DB or DDL)
- [x] Develop model of OPS DB staging area
- [x] Develop configuration for ora2pg (along with tests, DAGs, etc.)
- [ ] Develop fake/test dataset for MAPS
- [ ] Develop scripts/tests for data quality in MAPS
- [x] Initial load: Develop ETL/ELT process for extracting data from MAPS and loading in OPS
  - [x] #2481 
- [x] Diff load: Develop ETL/ELT process for extracting data from MAPS and loading in OPS
- [x] Initial load: Develop transform tooling from MAPS models to OPS models
- [x] Diff load: Develop transform tooling from MAPS models to OPS models
- [x] Develop Data Infrastructure/IaC, e.g. Airflow
- [ ] Develop DAGs for initial and diff loading, data quality, data monitoring
- [x] #3176 
- [x] Develop ELT for CAN BAC file - ingested yearly
  - [x] #2654 
- [x] #1510
- [x] #1520
  - [x] Discovery, exploration, and assessment of S3 storage and references to it
- [x] #1576
- [x]  #1820
- [x]  #1867
- [x] #1963
- [x] #3348
- [x] #3500
- [ ] #3592
- [x] #3615 
- [x] #3631

### Additional Context

consider using `dbt`, `dbt-expectations`, and `Airflow`

Related: #1678, #1447

### Resources

* https://ora2pg.darold.net/
* [MAPS DB Schema](https://github.com/HHS/OPRE-OPS/wiki/files/MAPS%20database%20schema%20diagram.pdf)

**Comment by kimschulke** [comment]
Sheila noted she could help with the test data/scenarios by modifying real data so we have a set of realistic data

**Comment by johndeange** [comment]
Data migration is complete. Closing.
