### ISSUE TITLE
Update existing send to approval process interface

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1428]
### Goals
Our existing interface and interactions on send to approval for draft --> planned  needs to be updated to match accepted designs

### Tasks
- [x] #1546
- [x] #1548
  - [x] 2 column Layout 
- [x] #1552
- [x] #1558
- [x] #1612
- [x] #1588
  - [x] Can Summary Card
  - [x] After Approval Toggle
  - [x] #1646
- [x] #1593
  - [x] Agreement Change Card
  - [x] CAN Change Card
- [x] #1613
- [x] #1614

#### UX Review
- [ ] see if Cypress a11y [config](https://github.com/component-driven/cypress-axe#basic-usage) allows for overrides on disabled colors state
- [ ] dynamic tooltips on disabled table rows

### Resources
* [Figma link](https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=6856-48104&mode=dev)

**Comment by jonnalley** [comment]
11/8
