### ISSUE TITLE
tooltip for disabled edit/delete options

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1430]
### Goals
* To give the user some textual explanation as to why edit and delete options are disabled for BLs or agreements.

### Tasks
- [ ] Come up with a centralized method for documenting/storing each tooltip - aka- `tool-tip-dictionary`? 
- [ ] Come up with tooltip text for each scenario
- [ ] Decide how to architect and structure the text for the component(s) in question

### Additional Context
* In [this comment](https://github.com/HHS/OPRE-OPS/issues/1000#issuecomment-1707208096), it was mentioned that we ought to have a tooltip to help the user understand why they might not be able to edit or delete an agreement or budget line in the various places where editing or deleting might be possible in some scenarios and have that display when the users hovers over those disabled options. 

* 

### Resources
*

**Comment by kimschulke** [comment]
I will draft the tooltip content. update to follow!

**Comment by kimschulke** [comment]
**One tooltip option**
- Budget lines in Executing, Obligated or In Review Status cannot be edited or deleted

**Multiple tooltip options**
- Budget lines in Executing Status cannot be edited
- Budget lines in Executing Status cannot be deleted
- Budget lines in Obligated Status cannot be edited 
- Budget lines in Obligated Status cannot be deleted
- Budget lines In Review Status cannot be edited
- Budget lines In Review Status cannot be deleted



What do you think @andressacurvelo ?

**Comment by andressacurvelo** [comment]
I really like this one: Only budget lines in Draft or Planned Status can be edited or deleted

**Comment by kimschulke** [comment]
[Updated in Figma](https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=6175%3A44289&mode=design&t=0Vbh0YgUmIQCTptg-1) - ready for dev!

<img width="806" alt="Screenshot 2023-09-06 at 4 39 01 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/cc804247-2969-4abe-80d8-0e634aec795c">

**Comment by fpigeonjr** [comment]
wonder if the tooltip message still makes sense in the context of the Agreements list?
<img width="1123" alt="image" src="https://github.com/user-attachments/assets/0738e1c8-a634-4b09-b298-69fbe6306ce3">

**Comment by fpigeonjr** [comment]
👀 saw that AgreementsList disabled icons are on #1470

**Comment by fpigeonjr** [comment]
reviewed with @kimschulke on 8/29/24
