### ISSUE TITLE
[8] As a dev, I want my local buildpack to match the deployed buildpack as closely as possible 

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#144]
### User story

As a dev, I want my local buildpack to match the deployed buildpack as closely as possible.

### Context

We got started using `pack` to manage buildpacks for local development in #123. 

All 3 devs have a working local environment now that uses a Python buildpack!

However, right now we are using a Google provided buildpack; we might be able to specify a closer match to the deployed buildpack. 

From `pack build --help`:

```
  -b, --buildpack strings           Buildpack to use. One of:
                                      a buildpack by id and version in the form of '<buildpack>@<version>',
                                      path to a buildpack directory (not supported on Windows),
                                      path/URL to a buildpack .tar or .tgz file, or
                                      a packaged buildpack image name in the form of '<hostname>/<repo>[:<tag>]'
```

### Tasks

- [ ] Research if we could specify a  `-b --buildpack` that would be a closer match
- [ ] Research if we could specify a `-B --builder` that would be a closer match
- [ ] Verify that app builds correctly locally using the new buildpack
- [ ] Update the documentation with the new local buildpack command and share with eng team

### Resources
* CloudFoundry Python buildpack: https://docs.cloudfoundry.org/buildpacks/python/index.html; https://github.com/cloudfoundry/python-buildpack
