### ISSUE TITLE
[8] As a dev, I want a local Postgres database that talks with my local Django server

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#145]
### User story

As a dev, I want a local Postgres database that talks with my local Django server.

### Tasks

_One approach could be ..._

- [ ] Set up a Docker image that runs Postgres locally
- [ ] Create a Django settings file for local development that points to the Dockerized Postgres
- [ ] Document how to run this service as part of local development 

*Other approaches might be ...*

- [ ] Not Dockerizing Postgres and just including instructions for installing/running/connecting it to Django locally — this is a little less convenient for devs and could create inconsistencies betweeen local dev environments 

### Resources
* Django Database config: https://docs.djangoproject.com/en/3.2/ref/settings/#databases
* Docker for Development: https://engineering.18f.gov/docker/
* Postgres Docker Hub: https://hub.docker.com/_/postgres
* How TANF Data Portal implemented this: https://github.com/HHS/TANF-app/blob/main/tdrs-backend/docker-compose.yml#L13
