### ISSUE TITLE
Step 2 of Procurement Tracker - Pre-solicitation

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1501]
### User Story
As a COR, I need to update and advance an agreement through the pre-solicitation step of an executing contract so that the solicitation package can be finalized

### Preconditions
* An agreement has one or more budget line in `Executing` status and the contract has already advanced past the first step.

### Acceptance Criteria
- [x] The user can see a visual understanding of the overall procurement process and the current progress in it
- [x] The user can optionally choose a **target** completion date and optionally commit the input of only that information and nothing else--independent of other user input. If the user does opt to provide a date, it must be today's date or a future date.
- [x] The user can attest that the package has been edited and finalized
- [x] The user can select the OPS user who attests to this and the date that this was actually completed (as opposed to a target date). The date must either be the current or a prior date.
- [x] The user can optionally provide any notes limited to 750 characters (or same as step 1's notes)
- [x] The user can reset all user input
- [x] The user can commit their input which will advance the agreement to the next step. 
- [x] If any error is encountered in persisting the change(s), that error should be presented to the user
- [ ] The relevant entries should be recorded in the event/history table(s) and be able to be properly rendered properly in the history of changes to the agreement
 
-----------------------------------------

#### UX
- [x] Review design options with team
- [x] Review design with stakeholders
- [x] Refine steps with stakeholders
- [x] Provide designs to developers
- [ ] Review the annotations and OPS Business Rules, and add any additional details as needed
- [x] Write the history messages for Step 2

##### OpenAPI
- [x] #4986

##### UI
- [x] #4990
- [x] #4991
- [x] #5057 
- [x] Draft Solicitation Date (Datepicker) (with specs)
- [x] Pre-solicitation  package checkbox (Disabled state checkbox) (specs included)
- [x] Cancel button handling and subsequent modal (specs included) 
- [x] Submit button handling and validation (specs included)
- [x] Post Submit step presentation
- [x] Ensure disabled state is maintained(agreement 8)
- [x] #5050 
- [ ] Add support for history messages for PT Step 2

##### API
- [x] #4987
- [x] #4988
- [x] #4989

##### Data
- [x] #5007

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [x] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [x] Build process updated
- [ ] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* A story pertaining to the prior step in the contract's lifecycle is #1603
* There is essentially two "tasks" a user can and will complete within step 2. One for if and when the target date is known and one for when the actual date is known.

**Comment by kimschulke** [comment]
[Outline of milestones](https://docs.google.com/document/d/1xFzX6TbPemUwfSzd83cUCRzijUQdIR_sXF-9w07Bfkg/edit)

Designs for milestone 2 in Figma: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=7497-94887&mode=dev

**Comment by jonnalley** [comment]
@fpigeonjr @josbell I'm assuming that for the time being, we want to remove the step 2 text that instructs users to go to the documents tab and upload something, etc......    cc @npage123 @kimschulke @andressacurvelo

**Comment by jonnalley** [comment]
@andressacurvelo @npage123 @kimschulke also this is deployed out to dev and staging and ready for your review please.
