### ISSUE TITLE
[UX Review] —10-3-2023

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1540]
### Goals
UX Review items from demo on 10-3-2023

### Tasks
- [x] BLIFILTERS TAGS spacing on “padding-bottom-205”
- [x] left-align Breadcrumbs
- [x] STEP 3:FORM remove text: ‘Select Add Budget Line to create multiple budget lines’
- [x] Fix tool tip on hover over actions on BL table - Only team members listed on this agreement can edit or delete
- [x] Placement of banner - should be over the H1, under breadcrumbs (global change)
- [x] Fiscal Year filter based on dataset, don't hard code the dates
- [x] All agreements page - Spacing between breadcrumbs, header, and tabs should be about 32 pixels

### Resources
* [slack conversation](https://flexion.slack.com/archives/C03LJ0NKZUG/p1696347776427889)

**Comment by jonnalley** [comment]
very nice @fpigeonjr !
