### ISSUE TITLE
PoC for workflow models and status

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1555]
### Goals
* Separating out "in review" for the multiple ways and times in which it’s used in a contract's lifecycle

### Tasks
- [x] Create flow diagrams to demonstrate the idea
- [x] Create sequence diagram to identify where it would fit into the user-flow for submitting BLIs
- [x] Create sequence diagram to identify where the workflow would fit, for a `Reviewer` approving the workflow.
- [x] Create class diagrams to demonstrate the `workflow` structure

#### Backend
- [x] Create a /bli-package endpoint to capture the "submission" data
- [x] Following the sequence-diagram [link], create a simple workflow
- [x] Apply that workflow to a submitted bli-package
- [x] Create endpoints for updating the workflow (may use `PUT /bli-package`)
- [ ] ...

#### Frontend
- [x] Wire up the "Submit for Review" to call the `/bli-package` endpoint, with a `POST` of the submission data
- [x] Create a hook/function on the `/Review` page, to check for the current workflow-steps / status and reflect  that
- [x] Update the rest of the site to reflect the "workflow-status" instead of `In-Review` status for DRAFT and PLANNED

### Additional Context
* There's at least one instance of a nirvana-like state each time a budget line advances from Draft --> Planned, Planned --> Executing (x2), and possibly Executing --> Obligated (TBD). 
* The ramifications and implications for a BL being in that state and the affect on business rules and other functionality can vary and is still being fleshed out as we work on related stories.

### Resources
*

**Comment by jonnalley** [comment]
11/30
