### ISSUE TITLE
[ALTERNATE to #93] View CAN info and money

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#157]
This is a proposed alternate to #93 that would have us start with the CANs tables, and then work our way towards adding the Agency and Persons tables.  Rationale: this would allow us to more quickly see the Django Admin interface in real life for our core user story (I want to see CAN info) and expose a bunch of unknowns about it.

### User story
As a PM/PO, I want to see what it would look like to view and edit CAN data in the Django interface so that I can provide feedback on how well it meets our needs.  

### Conditions of Acceptance
- [ ] I can use Django Admin in the dev environment to see how much money is available to OPRE and for what purposes (based on dummy data).
- [ ] I can test out the different out-of-box viewing and editing functionalities (or lack thereof).
- [ ] It would be ok if the PM can only view the interface on a dev's local.
- [ ] I do not need to be able to see who is responsible for the CAN (team leader, division, or authorizer)
- [ ] I do not need to be able to see the source of the CAN (source)

### Tasks
- [ ] Implement CAN Info model based on [CAN Info tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=1853066578), *rows 2-7 only*
- [ ] Implement CAN Amount model based on [CAN Amount tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=979139056), *rows 2-7 and 10 only*
- [ ] Populate the tables with the dummy data in [AirTable](https://airtable.com/tblC1gcLbcE5wou4Z/viwkZHevQYTEb1rRF?blocks=hide) *(ignoring Source, CAN Authorize, OPRE Team Leader, OPRE Division)*
- [ ] Display the dummy data using the admin interface

### Resources
- #91

**Comment by alexsoble** [comment]
@ninamak Synced up on this with the eng team: we think the original set of stories will get us where we're going faster than this alternate path. It will involve less re-work, since it will be simpler to start at the "edges" of the entity relationship diagram and work our way in. Ultimately, we know we need all of these database tables regardless of the order in which we tackle them. Let's discuss more 1:1 on Slack or in a meeting to talk this through if you have questions
