### ISSUE TITLE
[Alternate to #133] View Source and Authorizer for CANs (based on dummy data)

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#159]
This is a proposed alternate to #133 that would have us build off of basic CANs tables (#157 ) to add additional fields and tables to support additional user stories.

### User story
As a staff member of OPRE, I want to know where the CAN money originated from so that I can track who my research partners are.

As a staff member of OPRE, I want to know if the agency who provided the CAN money also needs to approve requisitions so that I can secure the appropriate signatures.  

### Conditions of Acceptance
- [ ] I can view the list of agencies in the Agency table (based on dummy data)
- [ ] When viewing CAN info, I can see the Source and the Authorizer for each CAN (based on dummy data).
  - [ ] More than one Source can be displayed for a CAN.
  - [ ] Only one Authorizer can be displayed for a CAN.
- [ ] If I can edit the fields, I should have the option of adding any agency in the Agency table.
  - [ ] More than one Source can be applied to a CAN.
  - [ ] Only one Authorizer can be applied to a CAN.

### Tasks
- [ ] Implement Agency model based on [Agency tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=0)
- [ ] Populate with the dummy data in [AirTable](https://airtable.com/tblGGRgffwAm6oV3h/viw42XXeFHzgoXwuB?blocks=hide)
- [ ] Implement CAN Info model based on [CAN Info tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=1853066578), *rows 8-9 only*
- [ ] Populate the tables with the dummy data in [AirTable](https://airtable.com/tblC1gcLbcE5wou4Z/viwkZHevQYTEb1rRF?blocks=hide) *(Source and CAN Authorizer only)*
- [ ] Display the dummy data using the admin interface

### Resources
- #91  
- [ER Diagram](https://docs.google.com/drawings/d/106BT0UIW_-zmocmNWMoGbe4nVmHGU1fYfsQWnTccsiI/edit)
