### ISSUE TITLE
[DEVEX]: Recommended VSCode Extensions

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#1594]
### Goals
* Improve the development experience by adding recommended Visual Studio Code extensions to our project. This will ensure that all developers are using the same set of tools, leading to more consistent code and easier collaboration.

### Tasks
- [ ] Identify the most useful VS Code extensions for our project.
- [ ] Add a `.vscode/extensions.json` file to the project with the recommended extensions.
- [ ] Update the project's README file to include instructions for developers on how to install the recommended extensions.

### Additional Context
* The choice of extensions may depend on the specific technologies we are using in our project. For example, if we are using React, we might recommend the "ES7 React/Redux/GraphQL/React-Native snippets" extension.
* We should consider not only extensions for our specific tech stack, but also general-purpose extensions that could be useful, such as "Prettier - Code formatter" for consistent code formatting and ESLint.

### Resources
* [VS Code's guide on Sharing Recommended Extensions with Your Team](https://code.visualstudio.com/docs/editor/extension-marketplace#_sharing-extensions-with-your-team)
* [VS Code Marketplace](https://marketplace.visualstudio.com/vscode) for finding and reviewing extensions.
<img width="948" alt="SCR-20231015-pygn" src="https://github.com/HHS/OPRE-OPS/assets/4629398/952be219-84b7-4d02-9100-a04e8bcccb31">
