### ISSUE TITLE
Step 1 of Procurement Tracker - Acquisition Planning

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#1603]
### User Story
As an authorized editor of an agreement, I want to update and advance a contract through the acquisition planning step of an executing agreement (contracts and AAs) so that I can track deliverables optimally.

### Preconditions
* One or more budget lines of a contract is already in executing status

### Acceptance Criteria
- [x] The user can see a visual understanding of the overall procurement process and the current progress in it
- [x] The user can affirm that they have sent the pre-solicitation package to the procurement shop. This is a required step to complete this step.
- [ ] The user can select the singular OPS user who sent the pre-solicitation package. The list of possible users would be any users associated with the contract including COR, ACOR, team lead(s) and division director(s).
- [x] The user can select the date the package was sent. The date must either be the current or a prior date.
- [x] The user can optionally provide any notes limited to 750 characters
- [x] The user can reset all unsaved form input
- [x] The user can commit their input which will advance the agreement to to the next milestone.
- [x] If any error is encountered in persisting the change(s), that error should be presented to the user
- [ ] The relevant entries should be recorded in the event/history table(s) and be able to be properly rendered properly in the history of changes to the agreement

-----------------------------------------

#### UX
- [x] Review design options with team
- [x] Review design with stakeholders
- [x] Refine steps with stakeholders
- [x] Provide designs to developers
- [x] Write history messages associated to procurement tracker @kimschulke @npage123 @andressacurvelo 

##### OpenAPI
- [x] #4861

##### UI
- [x] Create `ProcurementTracker` page component
- [x] #4868
- [x] #4937 
- [x] Create Step 1 specific form
- [x] #4962 
- [x] #4972 
- [x] #4993 
- [x] #5003 
- [x] #5009 
- [x] #5021 
- [x] Update E2E Tests for Procurement Tracker
- [ ] Add support for history messages from Procurement Tracker

##### Data
- [x] #4864
- [x] #4865
- [x] #4866
- [x] #4867

##### API
- [x] #4899
- [x] #4872
- [x] #4905
- [x] #4872
- [x] #4953
- [x] #4910
- [x] #4954
- [x] #4996 

### Test Plan
* User can navigate to the procurement tracker tab within the agreement's details
* User can view an overview of procurement steps with an indication they are at Step 1. User can open/close all accordions but input fields of all other steps other than the current ones should be disabled excluding target completion dates. (possibly just instruction text for steps and not the components)
* All user input fields but the  affirmation checkbox would be disabled and once the checkbox is checked, the other user input fields would become enabled. 
* User can open the dropdown the list of persons that has sent the pre-solicitation and select one (and only one)
* User can enter a date that is today's date as well as a date prior to the current date (separate tests)
* Notes field should be trimmed.
* Save Changes button should allow a user to click but Vest should throw  errors until validation is complete.
* Cancel: Cancel link is clicked, confirmation dialog is presented and if confirmed, the uncommitted form input is removed
* Once Save Changes is clicked with all required entries filled, a user can see their progress at the next uncompleted step of the Procurement Tracker, even if they've navigated away and come back
* Once Save Changes is clicked with all required entries filled, the viewable history event should record the user who completed step 1, the selected user who sent the out of band email as part of the acquisition planning step and the selected date.
* Once Save Changes is clicked with all required entries filled, step 1 shouldn't be editable any further

### Definition of Done Checklist
- [ ] UI works as designed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* A couple stories pertaining  to the prior step in the contract's lifecycle is #677 and #1671
* Cool drawing

**Comment by kimschulke** [comment]
Here is the outline of each milestone we created with our stakeholders --https://docs.google.com/document/d/1xFzX6TbPemUwfSzd83cUCRzijUQdIR_sXF-9w07Bfkg/edit

**Comment by kimschulke** [comment]
Designs for milestone 1 in Figma: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=7497-94887&mode=dev

**Comment by tdonaworth** [comment]
> Designs for milestone 1 in Figma: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=7497-94887&mode=dev

@kimschulke I don't see any designs in that linked Figma - only a box with placeholders?

**Comment by jonnalley** [comment]
https://lucid.app/lucidchart/fb021f39-168e-49cc-b2a1-0382aac916c2/edit?invitationId=inv_303cff8a-ce97-4eb1-9dfa-c4854c531118&page=n2-.lMrupA.U#

**Comment by jonnalley** [comment]
@weimiao67 @fpigeonjr @johndeange @rajohnson90 @Santi-3rd @josbell I believe this is ready to review and mark of for definition of done items at your convenience  please

**Comment by jonnalley** [comment]
@fpigeonjr @josbell mentioning you here in case you didn't get notified about @npage123's comment just above
