### ISSUE TITLE
Strategic research on unique identfiers for objects and searcing

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1621]
### Goals
* Understand how to alter designs, user interactions, and other aspects of OPS functionality around unique identifiers for objects and data structures
* Generate user stories for speficif user goals to address based on this research

### Tasks
- [ ] Conduct research and investigate how users think of and what needs are met by referencing and using DB or application-level unique  identifiers for various objects or data structures
- [ ] Understand if OPS already meets or addresses those needs in a different way or if it will based on our plans and roadmap
- [ ] Understand need for searching based on identifier

### Additional Context
* Back on 10/12/2023, we heard from OPRE stakeholders that it would be helpful to see our unique identifiers for contracts, BLs, etc.. somewhere on the screen as this is something they're used to seeing, referencing, and searching for now.  See meeting notes
