### ISSUE TITLE
Award milestone of Executing budget lines

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1640]
### User Story
As a COR, I want to upload executed artifacts and relevant contract metadata as part of a contract getting fully awarded in order to track the lifecycle properly in OPS.

### Preconditions
* A contract has one or more budget line in `Executing`` status and the contract has already advanced past the fifth milestone

### Acceptance Criteria
- [ ] The user can see a visual understanding of the overall procurement process and the current progress in it
- [ ] The user can select the OPS user who received the signed award and the date the award was uploaded to OPS. The date must either be the current or a prior date.
- [ ] The user can provide additional details including vendor name, vendor type, CLINs with PoP dates, and the Financial Agreement Number
- [ ] The user can optionally provide any notes limited to 750 characters
- [ ] The user can reset all user input
- [ ] The user can commit their input which will request approval from the budget team
- [ ] If any error is encountered in persisting the change(s), that error should be presented to the user
- [ ] The relevant entries should be recorded in the event/history table(s) and be able to be properly rendered properly in the history of changes to the agreement

-----------------------------------------

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] Usability validated (UX team)
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
A story pertaining to the prior step in the contract's lifecycle is #1518

**Comment by kimschulke** [comment]
in the current design, we have a checkbox for the user to manually attest that they received approval and to add the date... but should the UI already know that it was approved and record that date? Need to discuss/decide best path forward

**Comment by kimschulke** [comment]
Remaining to dos as discussed in team collab today

- [x] When editing a CLIN if you click edit, the CLIN becomes editable in the edit CLIN component, but if you click edit on another budget line, the CLIN component does not currently update to that budget lines CLIN input when it should @josbell 

- [ ] UXers need to confirm with Sheila validation for Contract Number (numerical values only, character length, etc) and validation for Award Date (past, current, future dates or open) @kimschulke 

- [x] Award amount component needs a dollar sign and should match the other $ components we have in OPS (BL Amount) @josbell 

- [ ] UXers to design a modal or alternative for having a user correct missing data while in the step 6 award process - for example when entering a CLIN, but other budget line data is missing (like the MAPS data) @kimschulke

**Comment by npage123** [comment]
@josbell Per feedback from Sheila on 6/30/26, when a COR is adding the needed information to the agreement, please change the  accordion labeled 'Award Information' to read 'Current Award Information'. Figma designs will reflect this as well.

**Comment by josbell** [comment]
@kimschulke @npage123 @andressacurvelo 
1.  _UXers to design a modal or alternative for having a user correct missing data while in the step 6 award process - for example when entering a CLIN, but other budget line data is missing (like the MAPS data)_

Is this needed since we have [5889](https://github.com/HHS/OPRE-OPS/pull/5889), or is this a different item?

2. Can you confirm that this is no longer needed? If i remember correctly from our last meeting we are not applying any validations at the moment.

_UXers need to confirm with Sheila validation for Contract Number (numerical values only, character length, etc) and validation for Award Date (past, current, future dates or open) @kimschulke_

**Comment by kimschulke** [comment]
Thanks @josbell!

I agree that it looks like bullet 1 is covered in 5889 and also that we can leave Contract# without any validation at this point (open-text).
