### ISSUE TITLE
Define metrics of success for OPS

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#168]
### Goals
* We want to have metrics we can track (baseline and deltas) that will help us answer whether we're having the impact we expected.

### Tasks
- [ ] Work with Sheila to define metrics based on the desired impact described in the [Product Brief](https://docs.google.com/document/d/1e5h2M7n2fDhxjawVAlvXgGQypVLnaMKu0-Z42m5sUYg/edit#heading=h.4i3iiwjf4l23)
- [ ] Work with Emily and Camille to get their input and feedback
- [ ] Update the Product Brief

### Additional Context
* These metrics will also get used to fill out the OCIO Intake Form

**Comment by ninamak** [comment]
Sheila requested that Nina set up a mtg to discuss

**Comment by ninamak** [comment]
Update: Co-worked with Sheila on this 9/14 ([doc here](https://docs.google.com/document/d/17bIWmOx5BZBYs52xYR6Ep77x3fe3iBXpw4tHLpLUweI/edit#heading=h.u381a6u2hi5p)).  

Next step: refine, then review with Emily et al (tentatively scheduled for 9/21)
