### ISSUE TITLE
As an OPS team member, I want more clarity on how we work together across roles (PM, Eng, Design) 

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#169]
### Goals

+ Bring OPRE OPS team members more alignment and clarity how we can support each other in our different roles (PM, Design, Eng), be good teammates to each other across roles, and collectively build OPS together.
+ Without documentation and alignment on how we'll work together, we run the risk of misunderstanding or disappointing each other, because of different expectations of how our functions work together on the team.

### Tasks
- [ ] Create outline for a "How we'll work together" doc key questions that need answering 
- [ ] Talk 1:1 with team members about their high-level needs 
- [ ] Write down our current understanding of how work flows from "idea" to "done"
- [ ] Identify any areas of misalignment and figure out if we need facilitation to resolve
- [ ] Ceremonial sign-off of some sort once we have alignment 

### Additional Context
* _Any additional information that would be useful to share about this work (e.g., dependencies, constraints, previous work that's been done, info already known, etc)_

### Resources
* [How product managers and engineers at Asana develop great relationships](https://blog.asana.com/2017/10/product-managers-engineers-develop-great-relationship/#close). Interesting framing: "PMs own the problems and Engineers own the solutions."

**Comment by alexsoble** [comment]
@ninamak We'll need to do fair amount of coworking on this one, since one of the big tasks is sketching out our current flows and processes for how we get work from idea to done. 

I booked us an hour tomorrow, we have an hour on the books already for Monday, and maybe we can use some of next week's coworking time if needed. Appreciate your time and help on this!

**Comment by alexsoble** [comment]
We didn't end up prioritizing this last cycle so we didn't make major progress. 

Going forward, I'll break this into smaller pieces so that we have a higher chance of finishing a piece of this work each cycle.
