### ISSUE TITLE
COR Feedback on Procurement Tracker/Milestones

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1697]
### Goals
Get feedback from CORs on the Procurement Tracker/Milestones

### Tasks
- [x] Identify CORs to meet with
- [x] Email CORs for availability and schedule 1:1's
- [x] Prep interview outline, designs to review and etc
- [x] Conduct interviews
- [x] Prep notes for synthesis
- [x] Outline insights, summary of what we learned, design changes

### Resources
[Outline of milestones](https://docs.google.com/document/d/1xFzX6TbPemUwfSzd83cUCRzijUQdIR_sXF-9w07Bfkg/edit)

**Comment by kimschulke** [comment]
One interview scheduled so far - Thursday (11/30) at 11am est

**Comment by kimschulke** [comment]
Drafting interview questions here:
https://docs.google.com/document/d/1HF7goyV8x4qJ3uNY6SGcAZQk2K5t8fd28Lo0eg_1H6c/edit

Let us know if there is anything else we want to ask from a development perspective / other ideas

**Comment by kimschulke** [comment]
2nd interview scheduled for 12/6 at 4pm est

**Comment by kimschulke** [comment]
Shared research findings during Tuesday stakeholder meeting and discussed next steps, scope for MVP and some improvements we will make to the procurement tracker
