### ISSUE TITLE
[8] Set up continuous deployment to the development site 

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#170]
### Goals
* Set up CircleCI for continuous deployment to our development app 
* Implement deploy via git tag as specified in: https://github.com/HHS/OPRE-OPS/blob/main/docs/how_we_work/deploy_flow.md#continuous-deployment-to-dev

### Tasks
- [ ] Add workflow to trigger a deploy to development app via git tag
- [ ] Create a service instance with deploy keys in cloud.gov; pass keys to CircleCI for continuous deployment 

### Condition of Acceptance 

+ [ ] Reviewing dev can manually deploy a change (e.g. fix typo, change color) via git tag 

### Resources

https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
