### ISSUE TITLE
Switch to use alpine docker image for local development

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#177]
... as recommended by 18F engineering coworkers.

Alpine comes with more handy tools pre-installed, like `nc`.

And it's smaller and faster too:

https://nickjanetakis.com/blog/the-3-biggest-wins-when-using-alpine-as-a-base-docker-image

### Goals

* Faster and more convenient local development 

### Tasks

- [ ] Specify an Alpine Python Docker image in our 
- [ ] Remove the step in our Dockerfile that manually installs `nc`
- [ ] Verify that everything works correctly 

### Resources
https://nickjanetakis.com/blog/the-3-biggest-wins-when-using-alpine-as-a-base-docker-image

**Comment by kbighorse** [comment]
fwiw, by the author in the comments:
"This was written almost 3 years ago. Nowadays I've been using the Debian slim base images for everything."
https://nickjanetakis.com/blog/the-3-biggest-wins-when-using-alpine-as-a-base-docker-image#comment-4760660006

**Comment by kbighorse** [comment]
This one is built `FROM debian:bullseye-slim`:
https://github.com/docker-library/python/blob/master/3.9/bullseye/slim/Dockerfile

just a possibility
