### ISSUE TITLE
Plan initial user engagement strategy

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#18]
### Goals
* Define how we plan to engage with users

### Tasks
- [x] Align on the goals, audience, and channels for a communication plan 
- [x] Draft initial communication plan
- [x] Review plan with partner

### Additional Context
* [Comms plan](https://docs.google.com/document/d/1Z4v5Ruj8SA_RsIQHWkOkQ1M35DFD4Lxm4oUVyc25wx4/edit#heading=h.sge47eowuroy) (work in progress)

**Comment by juliaklindpaintner** [comment]
I suggest we edit this to reflect a smaller scope: 

- [x] Align on the goals, audience, and channels for a communication plan 
- [ ] Draft initial communication plan
- [ ] Review plan with partner

A separate card should be set up to capture creating the resource box and drafting the first emails.

I think these items will go into a fleshed out version of #107 
- Define questions in priority research area(s)
- Identify research areas and priorities
- Sketch out rough idea of research activities
- Sketch out rough idea of protocols

I think this is achieved with the communication plan work we've done:
- Propose engagement strategy
- Figure out how best to communicate with / request input from user groups

These feel hard to do in the abstract: 
- Outline proposed expectations for different levels of engagement
- Think about our goals for user subgroups, how formal we want to be, etc
- Set target number of participants

These are N/A for now:
- Draft comms for Sept 1
- Create any supporting materials (deck, sign-up form, special email address, etc)

**Comment by ninamak** [comment]
@juliaklindpaintner Thanks for that break down!  
- This issue has been updated to reflect the smaller scope
- #139 and #140 have been stubbed out to start executing on the comms plans
- #107 has been updated

**Comment by ninamak** [comment]
@juliaklindpaintner Is this one ready to close?
