### ISSUE TITLE
Establish VPC Peer Connection with two VPCs

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#183]
### Goals

* Derisk the ask we'll make to the vendor, to migrate an Oracle database across different VPCs using DMS 
 
### Tasks
- [x] Review and understand [VPC Peering](https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html)
- [x] Add second VPC (Reuse the VPC from previous db work)
- [x] [Set up VPC Peer Connection](https://docs.aws.amazon.com/vpc/latest/peering/create-vpc-peering-connection.html)
- ~~[ ] Perform schema migration~~ Moved to #202 
- ~~[ ] Perform data migration~~ Moved to #203

### Additional Context
[Original Planning Doc](https://docs.google.com/document/d/1xDtV_M7NbVY4LisNOZ40bUN5IOpoJ4pvL7nB3lAb-bo/edit#heading=h.dyka0lrsukxz)

**Comment by alexsoble** [comment]
@amymok What Oracle DB versions will you be using for the source and target databases in this test? Asking to see if this test can also help us answer #192.

**Comment by amymok** [comment]
@alexsoble Just rereading my notes:
>Version: Oracle 12.1.0.2.v2 (Closest to vendor’s version of 12.1.0.2.0)

When I ran `select * from v$version;` on vendor's test db, I got:
```
Oracle Database 12c Standard Edition Release 12.1.0.2.0 -- 64bit Production
PL/SQL Release 12.1.0.2.0 - Production
CORE 12.1.0.2.0 Production
TNS for Linux: Version 12.1.0.2.0 - Production
NLSRTL Version 12.1.0.2.0 - Production
```

And the oldest version you can go on AWS for our limitation is:
- Oracle Standard Edition Two
- license-included
- Oracle 12.1.0.2.v2

This means there's a minor version difference here:
Vendor: 12.1.0.2.0 vs AWS Oldest available: 12.1.0.2.v2

Is that going to a major problem?  My guess is no, but we can do some research to confirm.

**Comment by amymok** [comment]
I am also moving #192 in and ahead of this card so we can make sure we should continue to proceed down this path.

**Comment by alexsoble** [comment]
Oh wow, that is a verrrrry tiny version difference! 😂 

Agreed with your instinct that this is unlikely to be a major problem. 

Of course free to tackle this first or #192 first, whichever you think makes the most sense! 

If #192 will be really hard to test or won't add much value, then we can drop it // close it out. Just wanted to surface that card as a potential "thing to verify" since it came up in Eng Cowork.

**Comment by amymok** [comment]
Completed and notes in [Database Migration Notes](https://docs.google.com/document/d/1-sC6CKvfy-M8Gx77HWGyCZmmO8ilUTgCyz1yeau1lu0/edit#heading=h.hsiqaktgp895)

Ready for review @carjug

cc @ninamak @alexsoble

**Comment by carjug** [comment]
LGTM, Amy! 💟
