### ISSUE TITLE
Re-assess OPA authz engine

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1851]
### Goals
* Assess if OPA best meets our current and expected future needs for an authz provider, particularly in light of OPS being hosted in Azure, anticipated features for file transmission, retrieval, and storage, and other
* Evaluate any other potentially-better alternatives

### Tasks
- [x] Evaluate options enabled by Azure as a hosting platform
  - [x] B2C Identity providers/service
- [x] Evaluate other new possibilities
- [x] Evaluate what challenges OPA currently presents 
- [ ] Your favorite tasks here

### Additional Context
* OPA was decided as a **tentative** choice for an authz provider to experiment with to be re-examined at a time like this
* Since we first made the assessment discussed in [our ADR](https://github.com/HHS/OPRE-OPS/blob/main/docs/adr/018-use-open-policy-agent-for-authorization.md):
  * We now know more about our authorization and environmental needs and requirements since we originally made that assessment. 
  * New providers have come on the scene and some (OSO) are marching off into the great proverbial digital sunset.

**Comment by jonnalley** [comment]
looking at Entra more now

**Comment by jonnalley** [comment]
devs met a couple weeks ago to agree to stay on the same path of a roll-our-own authz provider

**Comment by jonnalley** [comment]
3/25
