### ISSUE TITLE
Consider Removing Actions from All Agreements List & All BLs List

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1859]
### Goals
* Consider removing actions (edit, delete, send to approval) from All Agreements List & All BLs List
* Improve the All Lists by minimizing the # of disabled actions

### Tasks
- [ ] @kimschulke to discuss with team
- [ ] Remove the edit, delete, send to approval actions from the All Agreements List
- [ ] Remove the edit, delete, send to approval actions from the All BLs List

### Additional Context
* Since adding the "My Agreements" and "My Budget Lines" tabs, we no longer need to display user actions on the "All Agreements" or "All Budget Lines" lists. 
* The purpose of the "My" tab is so users can see what agreements/BLs are within their scope to edit, delete or send to approval. 
* The purpose of the "All" tab is so users can search/filter across OPRE. 
* Each tab should stay focused on its specific use case to simplify the design and reduce the # of disabled actions
* If a user is working on 2-3 agreements, there is no reason to show disabled actions for the other 100+ agreements they have no control over. Best practice would be to shift attention to what the user can do, not what they cannot do.

Reference
<img width="1567" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMHUxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eaf48c6fdb5473c11678eb7f596a61b78b0bf654/Screenshot%202024-01-10%20at%2011.02.45%E2%80%AFAM.png" alt="Screenshot 2024-01-10 at 11.02.45 AM.png" />
