### ISSUE TITLE
[Spike] Evaluate CircleCI alternatives 

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#186]
### Goals

Find out if there are good alternatives to CircleCI as our continuous integration tool.

### Tasks

- [ ] Evaluate GitHub Actions as an alternative including: compliance, ease of setup, stability/quality 
- [ ] Gut check if there are other alternatives we should be considering?? 
- [ ] Present findings to team
- [ ] Document

### Additional Context

[ADR #008](https://github.com/HHS/OPRE-OPS/blob/main/docs/adr/008-use-circle-for-ci-cd.md)

**Comment by alexsoble** [comment]
Learned more about this today and can provide a read-out to teammates during an upcoming cowork. 

Also, RyanA is presenting on GitHub Actions tomorrow!

**Comment by alexsoble** [comment]
I would like to provide a read-out to the whole team like this in one of our meetings, but we have a backlog of topics to cover! Will put it in the eng cowork agenda ...

I think it could be helpful to learn more about the compliance governing HHS GitHub Enterprise (the system I'm using to record this note), note-to-self-to-do-this-in-the-future-if-relevant.

**Comment by tdonaworth** [comment]
Where notes on this ever recorded @alexsoble ?
