### ISSUE TITLE
Evaluate if we want to update our DB migration plan 

### ISSUE THREAD

**Issue by alexsoble** [HHS/OPRE-OPS#188]
### Goals

Evaluate if we want to update our DB migration plan or keep it as-is 

### Tasks
* [ ] Summarize what we've found/learned so far about AWS Database Migration Service 
* [ ] Evaluate pros/cons/alternatives
* [ ] Decide if we want to update database migration plan 

### Additional Context
* _Any additional information that would be useful to share about this work (e.g., dependencies, constraints, previous work that's been done, info already known, etc)_

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_

**Comment by alexsoble** [comment]
Very Simplified Notes from Eng Cowork with @amymok on AWS Database Migration Service:

* AWS DMS can do migrations and replications. 
  * Migration — initial transfer of data from source to target.
  * Replication — ongoing transfer of data from source to target. 
* Replication instance is an EC2 instance that carries out the migration/replication. 
  * Two endpoints, one for source and one for target.
  * Once you have an instance, you set a migration task or a replication task. 
  * The replication task listens to logs to see if new data is flowing into the source DB and copies into the target DB. (We may need the vendor to turn on certain logs if they are not already on.) 
* Migrations and replications cost money. 💵 

Note from @ninamak: 

* We are still testing the assumption that we may need to run MAPS and OPS simultaneously. There is still a world where we might do a cut-over, which wouldn't require ongoing replication. 

Notes from @carjug:

* There may be blob data in the source DB, we might want to check on that because that could affect some AWS DMS settings.

Open questions: 

* Will AWS DMS work with the source database version? <from the DB notes! [AWS docs here](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.Oracle.html#CHAP_Source.Oracle.Self-Managed.Configuration.DbVersion), let's pull this into a task/ticket>
* Ballpark estimates for AWS DMS migration costs? Replication costs? <let's pull this into a task/ticket>
