### ISSUE TITLE
Refine CANs Data Model

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#190]
### User Story
As an OPRE manager, I would like to see some tweaks to the CANs data model to better reflect the language we use and how we do our work.

### Conditions of Acceptance
- [x] "Amount Budgeted" is renamed to "Total FY Funding"
- [x] "Additional Amount Anticipated" is calculated as the difference between "Total FY Funding"  and "Amount Available"
- [x] A new field exists, "Potential Additional Funding" and it is populated with the data that was previously in "Additional Amount Anticipated"
- [x] The order of these 4 budget fields is:
  - Total FY Funding
  - Amount Available
  - Additional Amount Anticipated
  - Potential Additional Funding
- [x] "Team Leader" is renamed "CAN Lead" and there are no restrictions on which Person names can populate the field
- [x] "CAN Lead" is a multi-select field
- [x] "Division" displays the Division for each person listed as "CAN Lead," but only if they're different
  - If this is onerous to implement or would create difficulties for reporting on CANs by Division later on, we can simplify to display only the Division for the 1st CAN Lead.  In all or almost all situations when there are multiple CAN leads, they will be from the same Division anyway. 
- [x] "Source" appears after "Description" and before "Purpose"

-----------------------------------------

### Tasks
- [ ] _Key pieces of work that will need to be done to meet the User Story and CoAs_

### Additional Context & Resources
* This story makes changes to the requirements in #93 
* OPRE also requested some changes around how the CAN Name is displayed.  I would like to hold off on making these changes until we have a design for how they will view CAN info, since it's possible that their underlying needs could be met through visual design rather than changing the fields.

**Comment by alexsoble** [comment]
@ninamak I assigned this one to you for you to flesh out the details // conditions of acceptance, and you've done that, so I'm un-assigning you now! Thanks for fleshing this one out!

**Comment by alexsoble** [comment]
@carjug One thought here as you get started -- I think we should probably rename the actual database fields here as well as the presentation layer. If we just change the presentation layer and keep the database fields the same, that could introduce confusion down the line. ("Why is this thing called X here but Y there?") You might be thinking the same, just wanted to say it out loud!

**Comment by carjug** [comment]
Yes! Was planning on that :)

**Comment by alexsoble** [comment]
@carjug OK great! Since it wasn't spelled out in the issue itself figured it couldn't hurt to overcommunicate a little 😂

**Comment by carjug** [comment]
@alexsoble @amymok ready for your review when you get a sec!

**Comment by amymok** [comment]
LGTM!

**Comment by carjug** [comment]
@ninamak ready for your review. LMK if you'd like a live demo or if the screenshots below are enough.
<img width="1406" alt="Screen Shot 2021-09-27 at 3 00 29 PM" src="https://user-images.githubusercontent.com/10871517/135117185-d947b8fc-c1d8-484c-a33b-062008363757.png">
<img width="1427" alt="Screen Shot 2021-09-27 at 3 00 38 PM" src="https://user-images.githubusercontent.com/10871517/135117206-4b17c6c5-1cbb-4f87-9045-0bff16fc8f32.png">

**Comment by ninamak** [comment]
The screen shots are great @carjug -- LGTM.
