### ISSUE TITLE
Azure Keyvault

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1918]
### Goals
Have Keyvault used by OPS for storage of necessary secrets and potential cryptographic content and be able to access and write to the key vault stores in an efficient but secure manner.

### Tasks
- [x] Determine best Keyvault topology and config
- [x] Build and test IaC
- [x] Determine and build interoperability with Keyvault for DevEx and for the app's usage
 
### Additional Context
*
