### ISSUE TITLE
Strategic research for validating edits/approvals

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1929]
### Goals
* Gather enough requirements for some new stories and any iteration necessary around approval workflow and what can be edited when
* meet with DDs and Team Leaders to re-visit what edits should require an approval and what edits do not require an approval
* further define business rules related to our process for editing and approvals in OPS

### Tasks
- [x] create research plan and any interview materials/diagrams
- [x] schedule interviews with DDs/Team Leads
- [x] conduct interviews
- [x] prep notes
- [x] synthesize research
- [x] share what we learned

### Resources
* Research plan, interview recordings and notes are in G Drive
