### ISSUE TITLE
Design CAN interfaces

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#193]
### Goals
* As a product/development team, we'd like to see some sketches/designs for creating, editing, and viewing CANs.

### Tasks
- [ ] Write draft user stories/requirements for CANs (Nina)
- [ ] Sketch designs for creating a CAN
- [ ] Sketch designs for editing a CAN
- [ ] Sketch designs for viewing a CAN
- [ ] Sketch designs for viewing a list of CANs
- [ ] Sketch designs for exporting CAN info
- [ ] Sketch designs for how the user will navigate from the home page to these screens

### Additional Context
* At this stage, the designs do not need to be high fidelity.  It would be helpful to see options and discuss them as a team before settling on a path forward.
* We will want the final product to be compliant with USWDS and accessibility standards.

**Comment by ninamak** [comment]
@juliaklindpaintner Does this card adequately capture our conversation?  

Also, I realized it will be easier for you to design these screens if you had user stories and requirements to go off of!  So I will write those up tomorrow and share with you.

**Comment by juliaklindpaintner** [comment]
@ninamak Yes this looks good and user stories would be great!
