### ISSUE TITLE
Create a CAN

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#195]
### User Story
As a Budget Officer, I need to input CAN information from UFMS so that OPRE staff know what money is officially available.

### Background
* Money appropriated from Congress is bucketed into CANs (Common Accounting Numbers), and subdivided into funds, allowances, and allotments.  There are requirements/restrictions around what money is available for what purposes and who is authorized to spend it.
* UFMS is the HHS system of record for financial information and where OPRE goes to get CAN info.
* Congress often appropriates money to the same CAN over multiple fiscal years (FYs).
* Some information about the CAN (e.g., the number, description, purpose, source, etc) is constant across FYs.
* Some information about the CAN (e.g., the amount) can vary across FYs.
* Money in the CAN can exist in two states: expected (e.g., Congress has appropriated it but it is not officially available to start spending against) and available (OPRE can start spending that money).
* OPRE needs to know about money in both states, so budget officers typically (but not always) input CAN info when money becomes expected, and then updates the CAN when money becomes available.
* More details available [here](https://docs.google.com/spreadsheets/d/15MpMpSZWMhqMTJJ2akFdtuJy6f6iVJJriSmQ4ERAQ7E/edit#gid=1780400632)

### Conditions of Acceptance
- [ ] Given that I am a budget officer, I should see an option to create a new CAN
- [ ] Given that I am not a budget officer, I should not see an option to create a CAN
- [ ] Given that I am creating a CAN, I should be able to input the following information:
  - CAN Number (combo of letters and numbers)
  - CAN Description (short text)
  - CAN Nickname (short text)
  - CAN Purpose (long text)
- [ ] Given that I am creating a CAN, I should be able to input the Arrangement Type.
  - I should see a single-select field
  - The options should be:
    - OPRE appropriation
    - MOU
    - Cost sharing
    - IAA
    - IDDA
  - The options should be listed alphabetically, except with "OPRE appropriation" always first (because it's the most common)
- [ ] Given that I am creating a CAN, I should be able to input the Source
  - I should see a single-select field

(To be continued)  
-----------------------------------------

### Tasks
- [ ] _Key pieces of work that will need to be done to meet the User Story and CoAs_

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_ 
* _Info already known or found, previous work that's been done?_
