### ISSUE TITLE
Discovery around Editing Agreements with Financial-impacting info requiring Approvals (without a BL status change)

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1964]
### Goals
* Do some initial research and experimentation to gain more understaffing around around editing agreements and BLs while not changing a BLs status but in some cases requiring approvals.
* Understanding LoE for converting what we have now in place to what the user needs are for this

### Tasks
Separate stories to come from this

**UX Tasks**
- [x] Review previous research conducted in https://github.com/HHS/OPRE-OPS/issues/1929)
- [x] Explore design options for editing/approvals outside of status change
- [x] Discuss options with the team and incorporate feedback
- [x] Review designs with OPRE
- [x] Determine if any further research/follow up is needed
- [ ] Schedule time with DDs and Team Leaders for additional feedback/validation
- [ ] Refine design based on feedback
- [x] Provide design assets to developers (Ready for Dev with comments and annotations)

**Dev Tasks**
Frontend

Backend
- [x] #2128
- post-experiment implementation is starting in #2193 for of this:
  - Create a general ChangeRequest model and subclasses for types of changes
  - Change the existing edit endpoints (for BLI and Agreement) to create ChangeRequests conditionally and return 202 instead of 200
  - Create change request endpoints
    - one to query change requests by agreement ID, BLI ID and if pending or not
    - one to get by ID
    - one to approve/deny a change request

### Additional Context
* A more-narrative document outlining potential scenarios and needs being addressed is [here](https://docs.google.com/document/d/1KIx2aFfZ9xvR_IgNNRtd-kOPtZk1_xxzkTP98-2aUSM/edit)
* Currently, in OPS, when a Planned BL is edited, it reverts back to Draft Status. This behavior should now change  so that Planned BLs can be edited, obtain any necessary budgetary approvals, but remain in Planned status
* Any edits on budget-related data require an approval (BL amount, CAN, Need By Date, or Procurement Shop/Fees) 
* All other edits can be made and updated without approval (but the DD will have a chance to review and correct anything before status changes occur)
* Not to be confused with the presently unrefined #1854, which would be for when a user wants to make metadata changes at the same time as a BL status change...if that's even a thing ?
* Original Goals:
  * OPRE needs a way to edit agreements and obtain necessary approvals when budget data has been changed
  * OPS currently has approval points when a status change is being requested (draft to planned, planned to executing, executing to obligated) but, we do not currently have a way to trigger approvals otherwise

### Resources
* https://github.com/HHS/OPRE-OPS/issues/1929
* [Sequence Diagrams](https://lucid.app/lucidchart/1251eaf1-bccf-4e3a-a514-57ec20659621/edit?viewport_loc=-73%2C1385%2C2888%2C1381%2C0_0&invitationId=inv_ec912ed0-07b5-44ca-8086-c9c38b4e1be1)
* interview recording and notes in Google Drive

### Acceptance Criteria 
- [ ]  For a contract with BLs in `Planned` or `Executing` state, users shall be able to alter a BL's amount, CAN, or need by date and that change not revert the BL's status to `Draft`. However, instead, that change should instantiate an approval process for a division director to approve before the change being fully enacted.
- [ ]  For a contract with BLs in `Planned` state, but not more advanced than `Planned`, a change to the contract's procurement shop shall be permitted, but an approval process shall be instantiated for a division director to approve before the change would be fully enacted. In this scenario, any BLs ought not change status as a result of this metadata change alone and should remain `Planned` even when awaiting approval.
- [ ]  For a contract with BLs in `Planned` state, but not more advanced than `Planned`, contract metadata other than the procurement shop (as mentioned above) or the _agreement type_ ought to be mutable by the user without causing any change in BL status. Additionally, no approval process would be engaged for these changes alone.

**Comment by kimschulke** [comment]
Reaching out to some DDs and Team Leaders to get additional feedback on our designs for the edit process and also the reviewer-approver side

**Comment by johndeange** [comment]
Draft of possible solution:

https://lucid.app/lucidchart/1251eaf1-bccf-4e3a-a514-57ec20659621/edit?viewport_loc=-73%2C1385%2C2888%2C1381%2C0_0&invitationId=inv_ec912ed0-07b5-44ca-8086-c9c38b4e1be1

**Comment by jonnalley** [comment]
4/18
