### ISSUE TITLE
NextGen IaC/Infrastructure

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#1987]
### Goals
* Convert all current IaC over to the "next gen" or next iteration of our IaC for our Azure environments.
* Retire prior iteration IaC and any current Azure resources that were created from it

### Tasks
- [ ] Deploy environments:
  - [x] Dev
  - [ ] Staging? 
  - [ ] Prod
- [ ] Update/implement pipelines for application deployments
- [x] Create New DockerFile for data-tools
- [x] Create Data-Tools deployment with schema updates
- [x] Troubleshoot and remediate App Gateway timeouts
- [x] Retire "old" infra

### Additional Context
* This GH issue is really just documenting remaining work. Much effort has already gone on for the so-called next-gen IaC we are standing up before this GH issue was created.  

### Resources
*

**Comment by jonnalley** [comment]
The rest of the staging and other environments will be done in a another item

**Comment by jonnalley** [comment]
4/10
