### ISSUE TITLE
Perform schema migration Oracle to Oracle (Different VPCs)

### ISSUE THREAD

**Issue by amymok** [HHS/OPRE-OPS#202]
### Goals
* Derisk on how to do schema migration across different VPCs

### Tasks
- [x] Research to see if there's difference between schema migration across two VPCs
- [x] Research on how to perform schema migration if databases are not publicly accessible
- [x] Perform schema migration across two VPCs

### Additional Context
* _Any additional information that would be useful to share about this work (e.g., dependencies, constraints, previous work that's been done, info already known, etc)_

### Resources
* [Original Planning Doc](https://docs.google.com/document/d/1xDtV_M7NbVY4LisNOZ40bUN5IOpoJ4pvL7nB3lAb-bo/edit#heading=h.dyka0lrsukxz)
