### ISSUE TITLE
Draft up preliminary database migration needs from vendor

### ISSUE THREAD

**Issue by amymok** [HHS/OPRE-OPS#204]
### Goals
* Create a list of what we need from vendor if we were to perform database migration

### Tasks
- [x] Review Database Migration Notes to pull out questions we need to ask vendor
- [x] Review Database Migration Notes to pull out instructions we need to ask vendor to do
- [x] Draft up preliminary needs

### Additional Context
* _Any additional information that would be useful to share about this work (e.g., dependencies, constraints, previous work that's been done, info already known, etc)_

### Resources
* [Original Planning Doc](https://docs.google.com/document/d/1xDtV_M7NbVY4LisNOZ40bUN5IOpoJ4pvL7nB3lAb-bo/edit#heading=h.dyka0lrsukxz)

**Comment by ninamak** [comment]
@amymok sorry, just realized this still has the "Nina Review" label on it.  As long as you and Carly feel like the documentation is sufficient for either of you to be able to have the conversation with the vendor if needed, 👍
