### ISSUE TITLE
Spike on USWDS Date  picker

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2049]
### Goals
* Understand feasibility of using the [USWDS date picker](https://designsystem.digital.gov/components/date-picker/) instead of what we have now when choosing PoP and need by dates
* Get a feel for what issues or problems it causes to switch to this

### Tasks
UX
- [ ] #2202

Dev
- [x] Review options 
- [x] Date Picker
  - [x] Replace `Need By Date` in the BLI Form
  - [x] refactor CRUD operations
  - [x] #2169
  - [x] refactor validations
- [x] create/edit/update unit and e2e tests
- [x] Tech Debt
  - [x] add validation to Services Components
  - [x] #2185
- [x] UX Review
  - [x] #2204

### Additional Context
* This came up when building #1852
* We'll need to remove uswds javascript since it conflicts with Trussworks and Comet libraries
  * will need to refactor the `CanSelect` Combobox and any other ComboBoxes relying on uswds js

### Resources
* timely Syntax podcast on [UI Component Libraries](https://syntax.fm/show/751/ui-components-shadcn-tailwind-ui-headless-react-aria-radix-ui)
* USWDS [Date Picker](https://designsystem.digital.gov/components/date-picker/)
  * 🟢 working similar to Comet's implementation 
* Comet's [Date Picker](https://github.com/MetroStar/comet/blob/main/packages/comet-uswds/src/components/date-picker/date-picker.tsx)
  * 🟠 got it working but calendar looks a little wonky
  * not consistent with their [storybook example](https://metrostar.github.io/comet/?path=/docs/uswds-forms-date-picker--docs)?
  * re-renders extra white-space on form 😞
* [Trussworks](https://github.com/trussworks/react-uswds) [Date Picker](https://trussworks.github.io/react-uswds/?path=/docs/components-date-picker--docs)
  * 🟠 working but...
  * 🔴 unable to set form state since its an uncontrolled component
* MDN Docs on [input date](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)
* [Adobe's Date Picker](https://react-spectrum.adobe.com/react-spectrum/DatePicker.html) and lower level [React Aria component](https://react-spectrum.adobe.com/react-aria/DatePicker.html)
* [Radix](https://www.radix-ui.com) does not have a DatePicker 🫠
* [AirBnBs Date Picker](https://github.com/react-dates/react-dates) looks pretty good 🤩

**Comment by fpigeonjr** [comment]
Got the `DatePicker` working for both the Comet and Trussworks components.  There is an issue with the alignment on the dates that I am running down.

**Comment by fpigeonjr** [comment]
solved the css issue and working on the embedding on the BLI Form

**Comment by fpigeonjr** [comment]
@jonnalley @kimschulke :
I think the [Date Range Picker](https://designsystem.digital.gov/components/date-range-picker/) may be a good choice for Period of Performance Start and End Dates.

Would it be ok to experiment with that component in this SPIKE for POP start and end dates?

**Comment by jonnalley** [comment]
@fpigeonjr go for it !

**Comment by fpigeonjr** [comment]
👍 will do @jonnalley

**Comment by fpigeonjr** [comment]
DatePicker not updating from state may be related to https://github.com/trussworks/react-uswds/issues/2348

**Comment by fpigeonjr** [comment]
started re-working a custom DatePicker based on Comet's implementation

**Comment by fpigeonjr** [comment]
my custom DatePicker component is working now without re-rendering and were able to set form state
🤩thanks Co-Pilot

**Comment by fpigeonjr** [comment]
- added vest validations to `DatePicker` and `AllServicesComponent`
- found bug in review-mode cancelling out of wizard deletes Agreement

**Comment by fpigeonjr** [comment]
Completed the refactor of CanSelect to CanComboBox using the ComboBox implementation with `react-select` as seen on our other combo boxes in the app. 

Will start e2e testing updates tomorrow

**Comment by fpigeonjr** [comment]
- completed UX review on 4/18/2024 and added task #2204

**Comment by fpigeonjr** [comment]
@jonnalley dev tasks are complete for this user-story

**Comment by jonnalley** [comment]
4/19
