### ISSUE TITLE
ATO Readiness - AC - Access Control

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#2100]
### Goals
* Ensure the outlined controls are compliant for ATO

### Tasks
- [ ] AC-02 - Account Management
- [ ] ac-02-01 - Automated Account Activities
  - [ ] Support the management of system accounts using [Assignment: organization-defined automated mechanisms].
- [ ] ac-02-02 - Automated Temporary and Emergency Account Management
- [ ] ac-02-03 - Disable Accounts
- [ ] ac-02-04 - Automated Audit Actions
- [ ] ac-02-05 - ACCOUNT MANAGEMENT | INACTIVITY LOGOUT
- [ ] ac-02-10 - ACCOUNT MANAGEMENT | SHARED / GROUP ACCOUNT CREDENTIAL TERMINATION
- [ ] ac-02-13 - Disable Accounts for High-risk Individuals
- [ ] ac-03 - Access Enforcement

**Comment by jonnalley** [comment]
related/similar to #432
