### ISSUE TITLE
Perform Schema Migration with MAPS (dev database)

### ISSUE THREAD

**Issue by amymok** [HHS/OPRE-OPS#212]
### Goals
* Understand and mitigate potential issues and risks when migrating the actual MAPS schema with test/production databases

### Tasks
- [x] Create an Oracle AWS RDS using similar spec as MAPS
- [x] Explore how we can migrate MAPS schema to TTS Sandbox AWS
- [x] Perform MAPS schema migration
- [x] Document how to perform MAPS schema migration
- [x] Document any questions, issues that arise during migration

### Additional Context
* Use #202 as reference

### Resources
* N/A

**Comment by amymok** [comment]
@carjug This is ready for review.  Notes in [this section](https://docs.google.com/document/d/1-sC6CKvfy-M8Gx77HWGyCZmmO8ilUTgCyz1yeau1lu0/edit#heading=h.ibzof3dyowqz) of the Database Migration Notes.

**Comment by carjug** [comment]
LGTM, Amy!
Thank you
