### ISSUE TITLE
DEVEX: Add type files for complicated types

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#2137]
### Goals
1. Add type files for complicated types per this [ThePrimeTimeagen](https://www.youtube.com/shorts/tj5VW2xJsqU) 

### Tasks
- [x] Identify complicated types in the codebase ie(agreements, budget-lines, etc)
- [x] Research best practices for creating type files for these types
- [x] Create type files for identified types
- [x] Test the type files to ensure they work correctly
- [x] Document the process for creating and using these type files

### Resources
- https://www.typescriptlang.org/docs/handbook/2/type-declarations.html
- https://www.youtube.com/shorts/tj5VW2xJsqU

**Comment by fpigeonjr** [comment]
```js
/**
 * @typedef {import("./types").Pet} Pet
 */
```

and [JSDOCS](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#typedef-callback-and-param) will help as a POC
