### ISSUE TITLE
Fees on BLIs should not be snapshotted for draft and Planned status

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2139]
### User Story
* As an OPS user, I want procurement shop fees to be always dynamically calculated and not snapshotted/stored when a given budget line is in `Draft` or `Planned` status so that the most-correct and up-to-date fee can always be represented and shown.

### Acceptance Criteria
- [ ] A budget line in draft or planned status does not have a persistently stored fee associated
- [ ] When budget lines are returned to the user, the fee calculation should always be dynamic and calculated ad-hoc
- [ ] BL totals and any agreement totals should use the ad-hoc/dynamic calculation of the fee.
- [ ] BL fees should still be "snapshotted" and persistently captured/stored once a BL transitions to executing status

-----------------------------------------

### Tasks

- [ ] Decide how this will impact CAN balances and their calculation?

#### UX
* shouldn't be any UX changes here ?

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] New design/tech debt documented (if applicable)
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* #2079 could likely be fixed at the same time as this story is implemented
*

**Comment by jonnalley** [comment]
This seems to be in opposition to and an opposing need from #1473, FWIW
