### ISSUE TITLE
Perform Data Migration with MAPS (dev database)

### ISSUE THREAD

**Issue by amymok** [HHS/OPRE-OPS#214]
### Goals
* Understand and mitigate potential issues and risks when migrating the actual MAPS data with test/production databases

### Tasks
- [x] Explore ways to dump data from vendor's database since we may not have enough access to their database to use DMS
- [x] Create an Oracle AWS RDS using similar spec as MAPS in another VPC in TTS AWS Sandbox
- [x] Migrate MAPS schema to another VPC
- [x] Use DMS to migrate existing data and ongoing migration
- [x] Document how to perform MAPS data
- [x] Document any questions, issues that arise during migration

### Additional Context
* Use #203 as reference
* #212 

### Resources
* N/A

**Comment by amymok** [comment]
@carjug This is ready for review: https://docs.google.com/document/d/1-sC6CKvfy-M8Gx77HWGyCZmmO8ilUTgCyz1yeau1lu0/edit#heading=h.me7xmgoql8s3
