### ISSUE TITLE
Onboarding documentation for new hires

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2141]
### Goals
* New team members will be more prepared and able to more meaningfully contribute sooner
* New team members have clear documentation already prepared for them upon starting with the team

### Tasks
- [ ] Construct documentation on development environment recommendations
- [x] Construct info on code base not already apparent in `README`s  that would need to get relayed to a new engineer 
- [ ] Come up with visuals or other other material helpful for a new UX researcher / designer
- [x] Links to specs/docs and tutorials on SQLAlchemy, Flask, marshmallow, gherkin/BDD, JWT, etc...
- [x] Think about training / shadowing / onboarding buddy stuff and come up with schedule/rotation

### Additional Context
* 

### Resources
* #1594 might be related

**Comment by fpigeonjr** [comment]
started a template that we can contribute to here: 
`docs/developers/onboarding.md`

**Comment by fpigeonjr** [comment]
- added some FE topics and tutorials to the `onboarding.md`
