### ISSUE TITLE
Migrate to Date Range Picker

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#2170]
### Goals
* add Date Range Picker based on [comet's implementation](https://github.com/MetroStar/comet/blob/main/packages/comet-uswds/src/components/date-range-picker/date-range-picker.tsx) 

### Tasks
- [x] #2223
- [x] #2224
- [x] add/edit unit-tests
- [x] add/edit e2e tests

### Additional Context
* This came up when building #1852
* We'll need to remove uswds javascript since it conflicts with Trussworks and Comet libraries

### Resources
* timely Syntax podcast on [UI Component Libraries](https://syntax.fm/show/751/ui-components-shadcn-tailwind-ui-headless-react-aria-radix-ui)
* #2049 was for the date (non-range) picker

### UX Review
- [x] better alignment of columns in SC Form

**Comment by fpigeonjr** [comment]
- started new DateRangePicker
- it is a wrapper component for two DatePickers
- the uswds js does not work out of the box

**Comment by fpigeonjr** [comment]
- completed DatePickerWrapper today

**Comment by fpigeonjr** [comment]
- created tasks for replacing `MemorableDate` components in the Services Component Form which I will work on next

**Comment by fpigeonjr** [comment]
- CRUD operations are working for DateRangePicker on the SC Form
- refactor form layout to flex-box

**Comment by fpigeonjr** [comment]
may get some inspiration from BOSS's https://github.com/US-Trustee-Program/Bankruptcy-Oversight-Support-Systems/blob/main/user-interface/src/lib/components/uswds/DateRangePicker.tsx

**Comment by fpigeonjr** [comment]
- resolved keyboard issues by refactoring to an uncontrolled component
- resolved unneeded re-renders by adding memoization
- added some gap in the flex-based layout

**Comment by fpigeonjr** [comment]
- think I found a solution on `needByDate` date picker re-render issue

**Comment by fpigeonjr** [comment]
- 🎉e2e tests are passing on SC Form refactor adding `DateRangePicker`

**Comment by fpigeonjr** [comment]
- UX Review today and received feedback that we need better column spacing 
- added to UX items

**Comment by fpigeonjr** [comment]
- dev tasks are completed and UX review completed today
- assigned to @jonnalley
