### ISSUE TITLE
refactor GET Agreement response schema

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2239]
### Goals
* Eradicate the growing mess of `to_dict` stuff in the backend API response schema
* Use more `marshmallow`

### Tasks
- [ ] Identify the problem
- [ ] Fix It
- [ ] Repeat until all problems are FIXED
- [ ] Leave the code better than you found it

### Additional Context
* Please use `marshmallow.Schema` and not `desert` or `marshmallow-dataclass` - plain `marshmallow` is more fully featured, better documented, and is more supported/mature than the others

### Resources
* #1449 has a small bit of overlap here maybe. GET on agreements is not the only place this needs to be done.
