### ISSUE TITLE
bootstrapping and initial config of new Azure subs

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2253]
### Goals
* Have newly-delivered OPRE Azure tenancy/subscriptions named, configured, and secured properly for later consumption by IaC (TF) and cutover from prior Azure deployment

### Tasks

- [x] cost management o11y
- [ ] Security / configuration management policies and o11y
  - [ ]  subscriptions in management groups? 
- [x] Decide on tag management for resources
- [x] Update CI/CD pipeline to point to this Azure

**Comment by jonnalley** [comment]
This is about as done as its going to get
