### ISSUE TITLE
Step 6 of Procurement Tracker - Award (Approver)

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2280]
### User Story
As a budget team member, I need to insure the accuracy and completeness of all contract artifacts in OPS and obligate budget lines.

### Preconditions
A contract has one or more budget line in Executing status and the contract has already advanced past the fifth step of the procurement tracker

### Acceptance Criteria
- [ ] User can view all artifacts uploaded previously for this contract
- [ ] User can view and edit all budget lines for the contract
- [ ] User can view and edit all contract metadata entered as part of this milestone (that is being submitted for review)
- [ ] User can approve all submissions
- [x] The affected budget lines will get updated to `Obligated` status
- [ ] The COR, project team, team lead, and budget team should all get notified of this final approval
- [x] The contract should be considered `awarded` if not already
- [ ] If any error is encountered in persisting the change(s), that error should be presented to the user
- [x] The relevant entries should be recorded in the event/history table(s) and be able to be properly redered properly in the history of changes to the agreement

-----------------------------------------

#### UX
- [x] Explore design options
- [x] Share design with team to discuss development considerations
- [x] Refine the design based on feedback
- [x] Share designs with stakeholders and other OPRE team members
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
A story pertaining to the prior step in the contract's lifecycle is #1518

**Comment by jonnalley** [comment]
This issue originally existed as #1641

**Comment by npage123** [comment]
@josbell The obligated date should be required before the 'Approve Award' button is enabled please. @kimschulke informed me that that date, if not entered, can't be assumed its the current date which is what happens currently in staging as it is generally first documented in another system.

https://github.com/user-attachments/assets/2d1c163d-8bfb-48b6-a8f2-8215aa0e3895

**Comment by Santi-3rd** [comment]
@npage123 I worked on the issue and this is how it's looking so far. Let me know if you have any thoughts 

https://github.com/user-attachments/assets/004d524f-2b87-4a57-8ba7-9cbdb306b904

**Comment by npage123** [comment]
Looks good @Santi-3rd , please move forward with the PR.

**Comment by npage123** [comment]
@josbell - Upon reviewing, I noticed that when logged in as a budget team user, when reviewing the agreement, after clicking on edit, I'm seeing that I am unable to edit a budget line's CLIN or any of the award info. See https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=34294-22373&t=89oOplX9c9INQU7J-4 for reference.

**Comment by jonnalley** [comment]
@npage123 @andressacurvelo @kimschulke I believe that last feedback has been addressed and deployed out to dev and staging. please review

**Comment by npage123** [comment]
@josbell @jonnalley @kimschulke @andressacurvelo Reviewed in staging and I was able to edit the CLIN and award information successfully!
