### ISSUE TITLE
Onboard Nate Page

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2291]
- [x]  Discussed SOO and client deliverables
- [x]  Discussed visuals/links and such
- [x]  Reviewed project documentation and other links

**Tasks**
- [x] Review project documentation
- [x] Complete Cybersecurity Awareness Training
- [x] Complete Privacy questionnaire

**Comment by kimschulke** [comment]
UX onboarding resources:
 https://docs.google.com/document/d/1tmpYYyQV4Jp81gwh3EM2K5azPQMcnAwqzg-yQzjivps/edit

**Comment by jonnalley** [comment]
5/24
