### ISSUE TITLE
Upload a document

### ISSUE THREAD

**Issue by johndeange** [HHS/OPRE-OPS#2365]
# User Story

As an OPS user, I want to upload a document for an Agreement (Contract).

# Acceptance Criteria

- [x] User can upload a file using the UI or API.
- [x] E2E tests stores the document in temporary/in-memory storage.
- [x] Production app stores the document in Azure Storage.
- [x] A user with the `ADMIN` role can upload a document for any Agreement.
- [x] A user without the `ADMIN` role can upload a document for any Agreement they are associated with, i.e. a team member or project officer of that Agreement.
- [x] A new privilege `UPLOAD_DOCUMENT` (or similar) should be assigned to the standard OPS roles.
- [x] The proper history and event records are created.

# Tasks

## Dev

- [x] Create JS component (based on `FileUpload.jsx`)
- [x] Create initial temporary JS page for this story (add a page with the new JS component for testing purposes)
- [x] Create API `Document Management` module (Flask blueprint) and `/documents` endpoint
- [x] Create marshmallow request/response schemas for `/documents` (and update openapi.json)
- [x] Create service `create_document`
- [x] Create `FakeDocumentRepository` for storing documents in memory (for testing) 
- [x] Create an endpoint (or reuse `/documents`) that can handle file transfer for `FakeDocumentRepository`
- [x] Update history record for the Agreement for uploading a document
- [x] Create `AzureDocumentRepository` for storing documents in Azure.

## Links

https://flask.palletsprojects.com/en/2.3.x/patterns/fileuploads/

[Previous PR](https://github.com/HHS/OPRE-OPS/pull/2089)

**Comment by maiyerlee** [comment]
**Document Types**

1. Certification of Funding
2. Statement of Requirements 
3. ITAR checklist for all IT Procurement Actions
4. Independent Government Cost Estimate 
5. Section 508 Exception Documentation 
6. COR Nomination and Certification Document
7. [additional documents]

**File Formats**

1. PDF
2. Word Document
3. Excel

**Comment by maiyerlee** [comment]
Process visuals: https://lucid.app/lucidchart/c91c0179-3ff6-44a6-aae3-875224955318/edit?viewport_loc=-2022%2C-657%2C2274%2C1149%2C0_0&invitationId=inv_8692244b-e68a-4b0b-bba9-3596a138896c

**Comment by jonnalley** [comment]
8/19
