### ISSUE TITLE
Design Debt To Dos

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2403]
### Goals
* Wrap up a few design debt items before moving onto new features like CANS, IAAs, AAs, MODS

### Tasks
- [x] Add BL ID to For Review Cards
- [x] Add BL status to For Review Cards so DD can see what kind of budget changes are being requested
- [x] Update new For-Review-Cards across all screens
- [x] Review approve/decline buttons for consistency across all scenarios/workflows
- [x] Update Need By column to Obligate By column throughout all screens (@npage123 and @kimschulke on Wed)
- [x] Take a look at the Approval for Budget Change and Approval for Status Change pages to make sure they are consistent review experiences (@kimschulke)
       -  Review Changes moved to top with For-Review-Card design
       -  Notes moved to an accordion
       -  Checkbox affirmation moved to bottom next to primary button
       -  Checkbox affirmation text reviewed and refined for consistency
- [ ] See if modal text should be simplified now that the checkbox affirmation has been refined
- [x] Double check spacing between Cancel and Primary buttons throughout - should be 20 pixels
- [x] Update the Pre-Award and Award For Review Cards to match the new design with BL Status included - make sure they are consistent designs
- [x] Mock up example for over budget CANs when DD is reviewing a budget change/edit (CAN cards displays red and approve is disabled, Only on Executing BL edits)
- [x] Update vendor component on Award Step per discussion on Tuesday 6/4 (open text for Vendor Name and open text for Unique Identity ID, in the future might be dynamic)
- [x] Update agreement details page with scenarios for Executing BLs and Obligated BLs/Awarded agreements
- [x] Incorporate BL IDs into alert banner for In Review (Ask Frank if he already did this)
- [ ] Update designs that can handle changing/dynamic procurement shop fees (Remove the % from the summary card, Tooltip on hover to show what fee rate was applied to each BL or BL expansion panel?, If the fee rate changes mid FY or anytime, display an alert banner on the agreement)
- [x] Review Tabs on Agreement Details - Display Documents and Procurement Tracker tabs alongside Agreement Details and SCs & BLs Tab (procurement tracker can be viewed but disabled actions until there are Executing BLs) (@npage123)
- [x] Update status change review items to blue focus state instead of disabled BLs

### Additional Context
*A few design debt items have come up recently in regards to our updated business rules on edit/approvals and through development work on other github issues

### Resources
*

**Comment by kimschulke** [comment]
Our goal is to address all design debt before Friday 6/14, but the sooner the better :)

**Comment by kimschulke** [comment]
Draft to Planned and Planned to Executing Review Pages need to be re-visited. Since we changed the business rules to review budget change and status change individually, not in groups. However, we'd like to discuss the possibility of having individual For-Review-Cards and then if they click Review Agreement, bundling the changes.

**Comment by kimschulke** [comment]
need to create a tech debt githib issue for updating the Approve/Decline Buttons

**Comment by kimschulke** [comment]
Need to create a tech debt github issue for updating the review/approve planned to executing page.. this includes updating the Review Changes Section

**Comment by kimschulke** [comment]
Updating the designs and dev to match the new business rules on procurement shops could be tracked in its own github issue and completed when prioritized. This is related to our new understanding on procurement shops and how the Fee Rate might change every FY... that means different BLs could have different Fee Rates even if they are all using the same Procurement Shop... the fee will be calculated dynamically when the BL is being executed to account for any potential changes. In our current design we display the Fee Rate on the Agreement Total Summary Card, but that needs to be removed to account for dynamic fees. Instead we will show a hover over tooltip on each BL Fee Column to show what fee rate is being applied to each specific BL.

**Comment by kimschulke** [comment]
Additionally, reviewing our confirmation modals for consistency can be moved to its own github issue and completed at a later date. We need to review our use/approach to confirmation modals to see if we are over-doing it, as well as review the test to see if the explanation is clear and concise or if it could be edited.

**Comment by kimschulke** [comment]
Here are the new github issues I am seeing, but we can discuss..

1. Tech Debt/development updates for Review/Approve draft to planned
     - new Review Changes section to match the For-Review-Card-Condensed used on Budget Changes
     - move notes into an accordion
     - move checkbox affirmation closer to approve/decline buttons
     - update the approve/decline buttons


2. Tech Debt/development updates for Review/Approve planned to executing
     - new Review Changes section to match the For-Review-Card-Condensed used on Budget Changes
     - move notes into an accordion
     - move checkbox affirmation closer to approve/decline buttons
     - update the approve/decline buttons


3. Design/tech debt to update designs and dev to align with new business rules on procurement shop (details above)

4. Design/tech debt to review/improve confirmation modals globally


and the following possible issues, but need to confirm...

5. Tech debt/development updates on Send to Approval Draft to Planned
     - new Review Changes section to match the For-Review-Card-Condensed used on Budget Changes

6. Tech debt/development updates on Send to Approval Planned to Executing
     - new Review Changes section to match the For-Review-Card-Condensed used on Budget Changes

**Comment by jonnalley** [comment]
6/19
