### ISSUE TITLE
Azure VPN gateway

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2404]
### Goals
* Establish Azure VPN gateway

### Tasks
- [x] Establish and configure Azure VPN Gateway
  - [x] IaC
  - [x] store any artifacts in secrets repository
  - [x] document non-IaC actions
  - [x] ADR ?

### Additional Context
* 

### Resources
*

**Comment by jonnalley** [comment]
7/9
