### ISSUE TITLE
Review Existing CAN Research

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2444]
### Goals
UXers will review the existing CAN research from 18F/project start

### Tasks
- [x] Review the research plan, interview notes, draft designs and etc
- [ ] Identify any gaps
- [x] Outline what information aligns with our current understand and where we need to validate with OPRE
- [ ] Make a plan for any needed research and design work to follow

### Additional Context
*
### Resources
* https://docs.google.com/document/d/1ifqv2F6OSN-uMHPwC_9iKpc5RLubUEZz0CKBXTYRotM/edit

**Comment by jonnalley** [comment]
7/3
