### ISSUE TITLE
Tech Debt - Frontend content changes

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2487]
### Goals
*Update the frontend to match some recent design changes from https://github.com/HHS/OPRE-OPS/issues/2403

### Tasks
------- **MODALS** -------
**Update content/text for all editor/submitter confirmation modals - budget changes**
- [x] Update Send to Approval Modal for budget changes

**Update content/text for all approver confirmation modals - budget changes**
- [x] Update Approve Modal for budget changes
- [x] Update Decline modal for budget changes
- [x] Update Cancel modal for budget changes (https://github.com/HHS/OPRE-OPS/issues/2349)

**Update content/text for all approver confirmation modals - status change: draft to planned**
- [x] Update Approval Modal for status change (draft to planned)
- [x] Update Decline Modal for status change (draft to planned)
- [x] Update Cancel Modal for status change (draft to planned) 

**Update content/text for all approver confirmation modals - status change: planned to executing**
- [x] Update Approve Modal for status change (planned to executing)
- [x] Update Decline Modal for status change (planned to executing)
- [x] Update Cancel Modal for status change (planned to executing) 

------- **ALERTS** -------
**Update content/text for all edit/change alerts - budget changes**
- [x] Update success/alert for budget changes sent to approval (editor) (need to add dynamic pending changes bullet list)
- [x] Update in review budget change alert for all users viewing the agreement (global)
- [x] Update success/alert for  approved budget changes (editor)(#2264 )
- [x] Update declined alert for declined budget changes (editor) (#2264 )

**Update content/text for all edit/change alerts - status changes - draft to planned**
- [x] Update success/alert for status changes sent to approval (editor)(need to add dynamic pending changes bullet list)
- [x] Update in review status change alert for all users viewing the agreement (global)
- [x] Update success/alert for approved status changes (editor)(#2264 or other)
- [x] Update declined alert for declined status changes (editor) (#2264 or other)

**Update content/text for all edit/change alerts - status changes - planned to executing**
- [x] Update success/alert for status changes sent to approval (editor)(need to add dynamic pending changes bullet list)
- [x] Update in review status change alert for all users viewing the agreement (global)
- [x] Update success/alert for approved status changes (editor) (#2264 or other)
- [x] Update declined alert for declined status changes (editor) (#2264 or other)

### Additional Context
* Alerts and modals were reviewed and edited to improve consistency and make them slightly more generic so they could be re-used globally in different contexts. This will improve the UX and make updating/maintaining alerts in the future easier
* Designs are updated in Figma!
* There are also updates the procurement tracker, but since that hasnt been developed yet, those changes will be incorporated in the initial build

**Comment by kimschulke** [comment]
Example photo to show what alerts looked like before/after

Before, we had a specific alert for every type of change request.... now we just have one alert that lists the changes (budget changes or status changes)
<img width="962" alt="Screenshot 2024-06-25 at 4 54 49 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/adda854c-ad69-4a73-a7cb-9ffef2174c18">

**Comment by fpigeonjr** [comment]
- updated confirmation modal for approver-side on ReviewCards
- updated Alerts for approver-side on Approve/Decline ReviewCards

**Comment by kimschulke** [comment]
Update Cancel modal for budget changes will be developed after the Review Agreement Page

**Comment by kimschulke** [comment]
Need to add "pending changes" bullet list into success/sent to approval alert

<img width="972" alt="Screenshot 2024-06-28 at 12 21 39 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/77616390-4b65-410c-b335-08c46743bd96">

**Comment by jonnalley** [comment]
8/15

**Comment by fpigeonjr** [comment]
@jonnalley I believe there aren't any more dev tasks for this issue
