### ISSUE TITLE
Tech Debt - Frontend Updates for Status Changes

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2488]
### Goals
*Update the frontend to match some recent design changes from #2403

### Tasks

**------- STATUS CHANGE: DRAFT TO PLANNED -------**

**Update Status Change Draft to Planned - Submitter side**
- [x] Add Review Changes section to match the For-Review-Card-Condensed used on Budget Changes
- [x] Move notes into an accordion

**Update Status Change Draft to Planned - Approver side**
- [x] Add Review Changes section to match the For-Review-Card-Condensed used on Budget Changes
- [x] Add blue focus state for the BL/Status column that is being reviewed
- [x] Do not disable the rows that were not sent for approvala
- [x] Toggle on should show the change request status (Planned Status) 
- [x] Toggle off should show previous state before change request (Draft Status)
- [x] Move notes into an accordion
- [x] Remove the old Review Changes section with the grey squares
- [x] Move checkbox affirmation closer to approve/decline buttons
- [x] Update the approve/decline buttons text (should say approve changes)

**------- STATUS CHANGE: PLANNED TO EXECUTING -------**

**Update Status Change Planned to Executing - Submitter side**
- [x] Add Review Changes section to match the For-Review-Card-Condensed used on Budget Changes
- [x] Move notes into an accordion

**Update Status Change Planned to Executing - Approver side**
- [x] Add Review Changes section to match the For-Review-Card-Condensed used on Budget Changes
- [x] Add blue focus state for the BL/Status column that is being reviewed
- [x] Do not disable the rows that were not sent for approval
- [x] Toggle on should show the change request status (Executing Status) 
- [x] Toggle off should show previous state before change request (Planned Status)
- [x] Move notes into an accordion
- [x] Remove the old Review Changes section with the grey squares
- [x] Move checkbox affirmation closer to approve/decline buttons
- [x] Update the approve/decline buttons text (should say approve changes)

**Comment by kimschulke** [comment]
@andressacurvelo and @npage123 when we update the overbudget CANs for Planned to Executing, we can add those tasks for the devs

**Comment by fpigeonjr** [comment]
@jonnalley I believe the dev tasks here are complete.

**Comment by jonnalley** [comment]
8/9
