### ISSUE TITLE
Tech Debt - Content Changes to Agreement History

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2495]
### Goals
* Update the frontend to match some recent design changes from https://github.com/HHS/OPRE-OPS/issues/2403
* Improve consistency between wording/content on alerts, modals and review pages to align with agreement history (for example changing "edit to BL Amount in review" to "budget changes to amount in review" which will align with the "changes in review" alerts and "budget changes" review card, etc

### Tasks
- [x] Designers explore content options
- [x] Developers meet with designers to discuss new content (posted below)
- [x] Make any adjustments if needed
- [x] UX to update agreement history within context of figma workflows/wireframes (include all types of budget changes and status changes)
- [x] Developers to develop 😀

#### Dev

- [x] investigate changes required

##### FrontEnd
- [x] update titles, messages
- [x] hide log item for the UPDATE after approval

##### BackEnd
- [x] include more to identify change request vs UPDATES
- [x] flag UPDATE after approval

**Comment by kimschulke** [comment]
Content changes to be discussed/developed

<img width="1122" alt="Screenshot 2024-06-27 at 2 05 03 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/b7673aea-4b25-4f44-b9fe-d90dd64f8bb6">

**Comment by kimschulke** [comment]
additionally, in dev we have 2 alerts for updating the agreement and approving it, but from the UX perspective, this should be one alert. the change would be approved and the agreement updated in one alert, no need for 2.

**Comment by jonnalley** [comment]
7/11
