### ISSUE TITLE
Refactor roles

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2560]
### Goals
* Refactor and re-purpose some of the current user roles to match our current understaffing of needed roles

### Tasks
- [x] Get rid of `COR` role - @johndeange 
- [x] Attribute appropriate user roles from COR to another role
- [x] Budget Team role ?

### Additional Context
* 

### Resources
* #2541 took care of the first task

**Comment by jonnalley** [comment]
8/12
