### ISSUE TITLE
initial .gov domain/zone readiness

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2598]
### Goals
* Make any IaC and application accommodations for our a transition to .gov URLs for OPS

### Tasks
- [x] Await determination on whether we'll get a whole zone or have to do individual records
- [x] Build/update existing zone in Azure 
- [x] Update TLS cert handling to accommodate
- [x] Update App Gateway and other infra settings

### Additional Context
* 

### Resources
*

**Comment by jonnalley** [comment]
8/21
