### ISSUE TITLE
Configure Demo Data for Application Presentation

### ISSUE THREAD

**Issue by maiyerlee** [HHS/OPRE-OPS#2626]
### Goals
* Provide a demo mode with pre-loaded data to easily showcase the application’s features to stakeholders.

### Tasks
- [x] Implement services to initialize the database with demo data using a new profile: `data-demo`.
- [x] Update main project [ReadME](https://github.com/HHS/OPRE-OPS/blob/main/README.md)
- [x] Create and include the necessary shell and SQL scripts to:
   - [x] Assign the user "User Demo" (ops_user id = 521) to Agreements 1, 9, and 10.
   - [x] Set "Director Dave"  (ops_user id = 522) as the project officer for Agreements 1, 9, and 10.
   - [x] Update the status of budget line items (BLIs) for Agreement 10 to "PLANNED".

### Additional Context
* Use `docker compose --profile data-demo up --build` to run the application locally to load the database using demo data.

### Resources
* [Docker docs on using profiles with compose](https://docs.docker.com/compose/profiles/)

**Comment by maiyerlee** [comment]
This is an ad hoc item that the team worked on during **OPS Engineers Office Hours** on 7/29/2024.

**Comment by maiyerlee** [comment]
We also removed Director Dave as team members from Agreements 1 and 10.

**Comment by maiyerlee** [comment]
Considerations for future iterations: use Alembic to implement the changes to ensure that events remain up to date.
