### ISSUE TITLE
Initial splunk exploration for non-prod

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2647]
### Goals
* Get non-production OPS environments logging some (not all) key logging telemetry into the ACF Tech non-prod Splunk environment
* Experiment with and build infrastructure to support this in a secure way
* Update documentation/ADRs as necessary

### Tasks
- [x] Create LUP service principal for Azure Splunk plugin and securely store credential info
- [x] Test out necessary telemetry from LAW and/or ACA
- [x] Communicate necessary Azure Database KQL to ACF Tech contacts
- [x] Acquire ACF Tech's  validation on Azure Database telemetry from the KQL
- [x] Test out Azure App Gateway telemetry

### Additional Context
* Required for ATO
* This is just an initial path to walk down for non-production. The same thing will need to be done for production once all this is buttoned up

### Resources
*

**Comment by jonnalley** [comment]
waiting on ACF Tech

**Comment by jonnalley** [comment]
We worked with ACF Tech back in November to insure they're getting what they need and provided them additional info upon request. We also got various Entra ID and Azure Audit logging going into LAW and provided sample KQL queries to them as desired. 

Documentation updated here: 
https://github.com/HHS/OPRE-OPS-Data/pull/19
