### ISSUE TITLE
True-up of existing data visualization

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2648]
### Goals
* Ensure existing charts and data visualization elements are correct, consistent, and are drawing the user's attention to the intended information

### Tasks

- [x] Review each OPS page/wireframe that contains data viz/graphs
    - [x] Define the main purpose/users for each page
    - [x] Determine if the graphs are correctly conveying the most important information
    - [x] Outline possible improvements
- [x] Review all instances of each graph for consistency
    - [x] Outline any differences of inconsistencies
- [x] Discuss and decide on changes/improvements
- [x] Create new Figma components with variants for each graph
- [x] Update new components onto Dev Page

### Additional Context
* This was born out of recent work with CANs

### Resources
*

**Comment by fpigeonjr** [comment]
will there be any `tech-debt` to address here?

**Comment by kimschulke** [comment]
Draft tech debt to review. Lets discuss how to break up into Github https://docs.google.com/document/d/1vwc9J3fVmNtd0vczRLZpbs0_MNoTqcB4ZGUdT74ett0/edit

**Comment by fpigeonjr** [comment]
I can see one `github-issue` for data-viz tech-debt and list items there as discussed on 8/27.

**Comment by jonnalley** [comment]
9/3
