### ISSUE TITLE
Validate BL's SC assignment before moving beyond draft status

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2652]
### User Story
As a team member on a given contract, I want to ensure that any budget line is assigned to a services component once it's ready to be planned in order to have the budget line properly categorized for the eventual contract

### Acceptance Criteria
- [ ] Budget lines in `draft` status are validated to be assigned to a services component before being allowed to be sent for approval to `planned` status
- [ ] Budget lines in any status other than `draft` still may not be unassigned from its services component. Validation should occur on this should a user try to persist that attempted change. This is already the existing behavior.
- [ ] Budget lines in any status can still be re-assigned to another valid services component.

-----------------------------------------

### Tasks

- [ ] update tests

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] Usability validated (UX team)
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] New design/tech debt documented (if applicable)
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* Slack conversation: https://flexion.slack.com/archives/C03LJ0NKZUG/p1722954379661799

**Comment by fpigeonjr** [comment]
@jonnalley is this a #️⃣post-initial release issue?

**Comment by jonnalley** [comment]
pretty sure this is already done
