### ISSUE TITLE
Onboard Guillermo Santiago

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2693]
- [x]  Discussed SOO and client deliverables
- [x]  Discussed visuals/links and such
- [x]  Reviewed project documentation and other links

**Tasks**
- [x] Review project documentation
- [x] Complete Cybersecurity Awareness Training
- [x] Complete Privacy questionnaire

**Comment by jonnalley** [comment]
9/13
