### ISSUE TITLE
Replace React favicon

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#2698]
### Goals
* Replace the default React favicon with a custom favicon that represents our app's branding.

### Tasks
- [x] Design or source a custom favicon for the app.
- [x] Convert the favicon to the appropriate formats (e.g., `.ico`, `.png`).
- [ ] Get approval from OPRE to use
- [x] Update the `public/index.html` file to link to the new favicon.
- [x] Test the favicon across different browsers and platforms to ensure compatibility.
- [x] Commit the changes and push to the repository.

### Additional Context
* The current favicon is the default React logo, which doesn’t reflect our brand. Updating it to a custom favicon will improve the app's professional appearance.
* The favicon should be simple and easily recognizable.
* Consider using multiple favicon sizes for different devices.
* This update is part of our ongoing effort to enhance the visual identity of our app.

### Resources
* [Favicon Generator](https://realfavicongenerator.net/) - Tool to create favicon files in multiple formats.
* [React Documentation - Adding Images, Fonts, and Files](https://reactjs.org/docs/adding-images-fonts-and-files.html) - Information on how to correctly add and link a favicon in a React project.

**Comment by kimschulke** [comment]
@fpigeonjr the icon you sourced below is actually the ACF icon, so I think OPRE might want to use something more specific to their office, but we can ask

![image (7)](https://github.com/user-attachments/assets/6ea8a23e-a358-4e2f-98a8-ecfffec48148)


If we want to use the OPRE icon, we will have to check with their brand team as I don't see any instances where they separate the 3 lines from the OPRE text

See below for social examples
<img width="1158" alt="Screenshot 2024-08-28 at 11 54 27 AM" src="https://github.com/user-attachments/assets/db1114bc-8faf-44ef-b013-8c02b0754c8f">

<img width="1291" alt="Screenshot 2024-08-28 at 11 54 21 AM" src="https://github.com/user-attachments/assets/0390df3e-e931-4566-9b97-077607668f10">

<img width="1312" alt="Screenshot 2024-08-28 at 11 54 06 AM" src="https://github.com/user-attachments/assets/18cd3296-193c-4f98-bddb-bbf25dd46244">

**Comment by kimschulke** [comment]
OPRE logos and guidelines: https://drive.google.com/file/d/1SpKn2BN7PBQHjlqdsA_gR6uyJfGzBy4X/view?usp=sharing

**Comment by fpigeonjr** [comment]
confirmed that the OPRE website does use the ACF icon

![Image](https://github.com/user-attachments/assets/72709309-4ef6-4459-b44f-2829e0b36a2f)

**Comment by fpigeonjr** [comment]
maybe we could use the thee lines for favicon but that may violate the terms and conditions, don't wanna get a call from the Attorney General

![Image](https://github.com/user-attachments/assets/9fbe325b-d144-42ef-8648-e3959a698c47)
