### ISSUE TITLE
Implement Actual Data for CANs Outside Division in AgreementCANReviewAccordion

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#2708]
### Goals
* Replace hardcoded data with actual data for CANs Outside Division
* Improve the accuracy and usefulness of the AgreementCANReviewAccordion component

<img width="649" alt="image" src="https://github.com/user-attachments/assets/660452e0-9578-4ddb-b7fc-e858d6dc86b9">

### Tasks
- [ ] Identify the correct data source for CANs Outside Division
- [ ] Update the AgreementCANReviewAccordion component to fetch the actual data
- [ ] Remove the hardcoded dummy data
- [ ] Update the component to properly display the fetched data
- [ ] Add error handling for cases where the data fetch fails
- [ ] Update unit tests to reflect the changes
- [ ] Perform manual testing to ensure the component works as expected with real data

### Additional Context
* The current implementation uses hardcoded data for CANs Outside Division
* This tech debt is located in the AgreementCANReviewAccordion component

**Comment by fpigeonjr** [comment]
not yet @jonnalley 

<img width="774" alt="Image" src="https://github.com/user-attachments/assets/9855b92f-ec47-417e-98ea-17f93883a4d4" />
