### ISSUE TITLE
Complete the Portfolios/PeopleAndTeams tab

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#2713]
### Goals
* Implement a fully functional PeopleAndTeams component
* Display relevant information about people and teams within the portfolio

<img width="526" alt="SCR-20240823-nfbf" src="https://github.com/user-attachments/assets/431f40aa-6936-43bf-8384-55dfe88de71f">

### Tasks
- [ ] Design the layout for the PeopleAndTeams component
- [ ] Implement the necessary data fetching logic (e.g., API calls)
- [ ] Create subcomponents for displaying individual team members and teams
- [ ] Write unit tests for the component and its subcomponents
- [ ] Update the component's CSS module (PeopleAndTeams.module.css) with appropriate styles
- [ ] Document the component's props and usage

### Additional Context
* The current implementation is a placeholder and needs to be fully developed
* Consider integrating with existing user management systems or APIs
* Ensure the component aligns with the overall design system of the application

**Comment by fpigeonjr** [comment]
may be related to #727

**Comment by jonnalley** [comment]
@fpigeonjr Eager to hear more of your perspective on this at some point. no rush though.  I'm curious about whether this is more of just a feature/story we haven't gotten to yet vs. tech debt.  Maybe the tech debt is that we have a tab that maybe we shouldn't right now ?

**Comment by fpigeonjr** [comment]
> Maybe the tech debt is that we have a tab that maybe we shouldn't right now ?

When I created this I was documenting fake/no data in the app so we wouldn't forget to come back to it. So through that lens this may story that we haven't started. 

Suppose we could hide this tab behind a feature flag? So far our approach has been to show hard-coded data but could be a bigger discussion with the team @jonnalley @kimschulke.
