### ISSUE TITLE
Data Viz Graph Updates

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2763]
### Goals
* Update UI to match changes as a result of UX Data Viz Audit

### Tasks
**Adjust graph card padding**
- [x] Top 20px
- [x] Right 30px
- [x] Bottom 30px
- [x] Left 30px

----------

**Re-order FYs/dates on the Budget Lines by FY graph**
- [x] Future dates come first (top)
- [x] Current dates come next
- [x] Past dates come last (last)
- [x] Make sure this is consistent across all pages and workflows

----------

**Swap order of Budget Lines by FY graph and Agreement Total Summary Card**
- [x] Create agreement workflow
- [x] Budget Lines List
- [x] Agreement details
- [x] Edit agreement/budget change workflow
- [x] Status change workflow
- [x] Review/approve budget change workflow
- [x] Review/approve status change workflow

-------

**Update font size on Agreement Total Summary Card**
- [x] Change large font size to 32 px
- [x] Make sure this is consistent across all pages and workflows

-------

**Change colors of Budget Lines by FY graph**
- [x] Bar 1 (top) = #A5174C
- [x] Bar 2 = #C94576
- [x] Bar 3 = #EB6A94
- [x] Bar 4 = #F492BD
- [x] Bar 5 (bottom) = #D393B3
- [x] Make sure this is consistent across all pages and workflows

-------

**Change background color on all card components, accordions and table hover states**
- [x] Change from #F0F0F0 to #F5F5F5
- [x] Make sure this is consistent across all pages and workflows (summary cards, review/approve cards, accordions, table hover state and expanded row)

--------

**Change obligated color from green to purple**
- [x] Change from #3A835B to #8B4687
- [x] Make sure this is consistent across all pages and workflows

-------

**Create new graph to show Available Budget**
- [x] Edit existing graph that shows Remaining Budget to new graph that shows Available Budget
- [x] Update new graph on status change workflow (Review CANs accordion)
- [x] Update new graph on review/approve budget change (Review CANs accordion)
- [x] Update new graph on review/approve status change (Review CANs accordion)
- [ ] Make sure caption for graph is updated on all Review CANs accordions
- [ ] Make sure instructional text is updated on all Review CANs accordions

------

### Resources
* updates have been made on the Dev Page in Figma
* images below for context
* Reach out to UXers for pairing/collaboration 👍

**Comment by kimschulke** [comment]
<img width="1080" alt="Screenshot 2024-09-04 at 9 50 21 AM" src="https://github.com/user-attachments/assets/d991dd98-1284-4522-96de-6aafb5cf3529">

**Comment by kimschulke** [comment]
Color styles in [Figma](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=2267-7108&t=FLBENBEHnj2nij9n-1)

<img width="510" alt="Screenshot 2024-09-04 at 10 00 54 AM" src="https://github.com/user-attachments/assets/984f42aa-0fb0-4e48-9f8d-558f1a06c86d">

**Comment by kimschulke** [comment]
**Current graph showing Remaining Budget**
<img width="1006" alt="Screenshot 2024-08-30 at 9 27 45 AM" src="https://github.com/user-attachments/assets/ec9f84ae-8f19-4af5-b69c-16e511b19ccd">


------

**New graph showing Available Budget**
<img width="785" alt="Screenshot 2024-09-04 at 10 15 22 AM" src="https://github.com/user-attachments/assets/7a2c247c-7e96-4447-bfd2-3828502bed0d">

**Comment by fpigeonjr** [comment]
> Change large font size to 32 px

This is the current value of the large dollar amount

![Image](https://github.com/user-attachments/assets/0863c984-db34-49d6-ad58-02fb94c41d26)

**Comment by fpigeonjr** [comment]
> Make sure this is consistent across all pages and workflows (summary cards, review/approve cards, accordions, table hover state and expanded row

@kimschulke Can I get confirmation on the accordion bg-color? I am seeing #F0F0F0 in Figma.

**Comment by npage123** [comment]
I can help @fpigeonjr. Yes, please use #F5F5F5. We haven't updated those yet but will soon.

**Comment by fpigeonjr** [comment]
Thanks @npage123 will continue on with the updates.

**Comment by fpigeonjr** [comment]
UX review conducted on 9/10/24'

**Comment by jonnalley** [comment]
9/10
