### ISSUE TITLE
Configuration Management Plan

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2797]
### Goals
* Get an approved Configuration Management Plan pushed through

### Tasks
- [x] Author up the required portions of the CM plan for OPS
- [x] Publish and seek review/approval
- [x] Link in our CM 800-53 controls
- [x] Attain approvals

### Additional Context
* ACF Tech has their template to use

### Resources
*
