### ISSUE TITLE
Set-up a Work Tracking Board

### ISSUE THREAD

**Issue by stvnrlly** [HHS/OPRE-OPS#289]
### Goals
- Have a work tracking board that works for both OPRE and Flexion.

### Tasks
- [x] Send Domenic a request to set it up
- [x] Domenic sets it up?
- [x] Flexion tries GH Projects
- [x] Add ZenHub to the mix
- [x] Flexion customizes it
- [x] Might require #297 to be completed first?

### Context
- Possible options are...
  - The classic GitHub Project interface.
  - The [new beta GitHub Project interface](https://docs.github.com/en/issues/trying-out-the-new-projects-experience).
  - [ZenHub](https://www.zenhub.com).

**Comment by stvnrlly** [comment]
@DomenicCaruano I think you might be the right person to ask about the beta GitHub Projects. It looks like only an admin can create one. Would it be okay to request one of those on here, or would you prefer it to go through email?

**Comment by jonnalley** [comment]
GH projects was sub-optimal. maybe one day. ZenHub is light years beyond it presently so pivoting to that

**Comment by jonnalley** [comment]
Customized to the extent that we intend to for now
