### ISSUE TITLE
OpEx: Get cloud.gov IAA drafted and signed

### ISSUE THREAD

**Issue by stvnrlly** [HHS/OPRE-OPS#290]
### Goals
* Be engaged in a procurement process with cloud.gov.

### Tasks
- [x] Hold discussions with cloud.gov staff and relevant staff from ACF OCIO
- [x] Acquire IAA particulars
- [x] Complete cloud.gov survey form
- [x] Acquire execution on IAA with cloud.gov

### Additional Context
* Sheila and Amare to lead this
* dependent on #300 to the extent that cloud.gov continues to be the path forward

**Comment by jonnalley** [comment]
Amare has begun conversations on the draft IAA

**Comment by AmareB441** [comment]
1. Obtained HHS/ACF guideline and other sources of information for the Interagency Agreement (IAA) lifecycle, which includes preparing, recording, and closing out.

2. Contacted GSA ( cloud.gov) for information about the requirements and on how to initiate the process. 
3. GSA ( cloud.gov) sent us a Survey Form  to be completed and sent out to them for IAA form preparation.
4.  GSA ( cloud.gov) has emailed me their readiness to discuss the requirements and initiate the process.  
     The following are the time slots they proposed: 
          Friday 7/22: 12pm - 2:30pm EST
          Monday 7/25: 11-11:30 am, 4-5pm EST
          Tuesday 7/26: 11-12pm, 3:30-5pm EST

**Comment by AmareB441** [comment]
### **The following are the summary of main points that had been discussed with GSA cloud.gov representative team on Friday 7/22: 12pm - 2:30pm EST. Jonathan, Peter, Amare Beza OPRE participated in the meeting with the GSA cloud.gov team Mark Head and Kelly Confer.** 

- The cloud.gov team provided an overview of the cloud.gov describing it as Platform as a Service (Paas) with a Provisional Authority to Operate (P-ATO) at the Moderate impact level. 

- Explained and confirmed cloud.gov FISMA Moderate can fully support all OPRE requirements for the development, staging, and production environments. In addition, the platform supports Python, relational databases (PostgreSQL, MySQL, and Oracle), S3 storage and other wide range of applications. 

- Responded to the technical issues raised related to cloud.gov’s support for DNSSEC, Microservices and others. In this respect, they provided the following relevant links for additional clarification and understanding.  

1. https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#internal-routes
2. https://cloud.gov/docs/management/space-egress/
3. https://github.com/cloud-gov/cg-cli-tools
4. https://cloud.gov/docs/services/external-domain-service/
5. https://cloud.gov/docs/compliance/domain-standards/

- They confirmed that they will prepare the IAA purchase agreement. Providing information for completing the IAA form and designating a person that will work with them is the responsibility of OPRE. They underscored the process could take from 3-5 weeks but after the agreement, access to the service will be within 24 hrs. 

- Finally, they expressed their willingness to work closely with our team and promised to give additional explanation and support whenever it is needed. 

### **The following are updates after the meeting:** 

- Received an updated IAA preparation Survey form to gather the necessary information for the Interagency Agreement (IAA). 
- Obtained cost estimator prepopulated with monthly package access fee for FIMSA Moderate and memory usage fee assuming a usage of 10GB memory.  
- Assigned Matt Yoko-Young, Agreements Team Lead as our point of contact for support to the IAA process. 

**### Next Steps:**   

- Complete the preparation survey form 
- Define the OPS memory usage requirement with Flexion.
- Finalize the IAA purchase Agreement

**Comment by jonnalley** [comment]
@AmareB441 we provided some input from our standpoint on the memory footprint in the slack channel. Thanks!

**Comment by AmareB441** [comment]
- [ ] August 4, 2022, completed survey form has been sent to GSA cloud.gov. The following are included in the form: Prototyping package, with a 5GB memory usage requirement, for the first 1 year ( 12 months) and to move to a FISMA Moderate package (Production) thereafter. 
- [ ] August 9, 2022, received a confirmation feed back that states they have already started drafting the IAA agreement

**Comment by AmareB441** [comment]
**### Cloud.gov IAA Update, August 29,2022**

- [ ] CLOUD.GOV Development Environment IAA documents ready for approval.

**Comment by jonnalley** [comment]
Amare and Sheila shared that IAA was sent off and we are awaiting the provisioning

**Comment by AmareB441** [comment]
**### Cloud.gov Final Approval Received**
Coud.gov IAA approval completed form both sides on the 9/12/2022. The remaining task is only service provisioning and for this to happen we are expecting user credential distribution from GSA. As per the agreed SOW, this task may take 10 business days since the final approval of the IAA. Efforts to expedite remining the processes will continue.
