### ISSUE TITLE
Copy of Postgres update

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#2912]
### Goals
* Be running the latest supported major version of Postgres in Azure
* Match the same major version of postgres we specify for developing locally

### Tasks
- [ ] Update terraform and merge PR
- [ ] Plan and apply, monitor destruction and re-creation
- [ ] if not done automagically, fire off data_tools again for non-prod environments?
- [ ] Any Prod initial data staging ?

### Additional Context
* 

### Resources
*
