### ISSUE TITLE
Discuss & update OPS roadmap/strategy

### ISSUE THREAD

**Issue by stvnrlly** [HHS/OPRE-OPS#292]
- [x] Review and update product strategy @kimschulke @jonnalley 
- [x] Review and update technical strategy @halprin
  - [x] Create the initial document.
- [ ] Discuss and handoff to OPRE Tech Lead

**Comment by halprin** [comment]
Technical write-up is coming along nicely.  It is nearly done.

**Comment by kimschulke** [comment]
Attached below is an initial approach for the UX Product Strategy - let me know your thoughts/feedback

[OPRE OPS UX Product Strategy - Initial Approach.pdf](https://github.com/HHS/OPRE-OPS/files/9102708/OPRE.OPS.UX.Product.Strategy.-.Initial.Approach.pdf)

**Comment by jonnalley** [comment]
Discussed and reviewed with OPRE team this morning.
