### ISSUE TITLE
Strategic Research on OPS Reporting

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#2930]
### Goals
* better understand reporting needs at OPRE

### Tasks
- [x] Draft a research plan
- [x] Conduct research
- [x] Summarize research
- [x] Share and discuss research findings
- [ ] Create a new github issue for design and development

### Resources
[Research plan](https://docs.google.com/document/d/1y67hj0fo8IpOCbstWx8ZrBhyC1KO777eYjOdV-Rhp_s/edit?usp=sharing)

**Comment by kimschulke** [comment]
Reporting requirements gathered from our initial research with the Budget Team: https://docs.google.com/document/d/1rgV8AxhzoIE1pg5jRS0ncE5DwKQNpxhWmgnOp5ebXQs/edit?tab=t.0

**Comment by kimschulke** [comment]
Just need to set up an epic for reporting (if we haven't already) and then add in some of these user stories

**Comment by jonnalley** [comment]
@kimschulke #2996 is a larger epic on "Reporting" the we can make GH Sub-issues for as needed. #3067 is a story on "exporting" raw data as distinguished from "reporting"
