### ISSUE TITLE
Add Flexion to HHS GitHub Organization and Teams

### ISSUE THREAD

**Issue by halprin** [HHS/OPRE-OPS#297]
### Goals
- Give Flexion access to the repository (and other related repositories) in a sustainable manner.

### Tasks
- [x] Add Flexion to the [HHS organization](https://github.com/HHS).
  - [x] @tdonaworth
  - [x] @jonnalley
  - [x] @halprin
  - [x] @kimschulke
- [x] Create an "OPRE Ops" team and add Flexion to it.
  - [x] @tdonaworth
  - [x] @jonnalley
  - [x] @halprin
  - [x] @kimschulke
- [x] Create an "OPRE Ops Admin" team underneath the aforementioned "OPRE Ops" team and add the following people.
  - [x] @tdonaworth
  - [x] @halprin
- [x] Give "OPRE Ops" team write access to this repository.
- [x] Give "OPRE Ops Admin" team admin access to this repository.

### Additional Context
Flexion has access to the GitHub repository, but there's a preference 

### Resources
- Expands from #287.

**Comment by jonnalley** [comment]
@halprin On a related note, Sheila advised that us having access to the MAPS repo would require #291 occurring first as well as supplementary conversation to determine whether or not the access is warranted.

**Comment by halprin** [comment]
Waiting to meet with Dominic to get the DL on how this could work.

**Comment by jonnalley** [comment]
Sounds like the HHS org part isn’t going to happen but maybe we can do Teams still ? Dunno

**Comment by jonnalley** [comment]
still waiting on HHS folks to get Tim in the fold

**Comment by tdonaworth** [comment]
@jonnalley Curious why this was re-opened? All tasks are complete.

**Comment by jonnalley** [comment]
@tdonaworth Maybe it was to keep all the things for this sprint in the done column on ZenHub until the end of sprint when presumably they'll move to closed?  That was one gripe I had about ZenHub that issues in its "Done" column still show "Open" on regular GH.
