### ISSUE TITLE
Deliver write-up on cloud.gov to OPRE Tech Lead

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#300]
### Goals
* For Flexion to enumerate identifiable and potential concerns, risks, known issues, and limitations with using cloud.gov

### Tasks
- [x] Meet with Wes Dean.
- [x] Get response back from Cloud.gov on its "prognosis".
- [x] Dig deeper into on-call with Cloud.gov.
- [x] Synthesize into a document.
- [x] Update [the existing LADR](https://github.com/HHS/OPRE-OPS/blob/main/docs/adr/002-use-cloud-dot-gov.md) via pull request if not using the LADR itself
- [x] Deliver findings to OPRE Tech Lead.

**Comment by halprin** [comment]
Created a meeting to meet with Wes Dean, someone in Flexion who has Cloud.gov experience.  Also invited Amare and @jonnalley.

**Comment by halprin** [comment]
Met with Wes.  Got a lot of great insight.  I started a document for this write-up.  I'm waiting for a response from cloud.gov (through Wes) about their future.  I also need to dig into on-call capabilities for stuff deployed into cloud.gov.

**Comment by halprin** [comment]
Sent the document to Amare.  He agreed with the conclusion in the document.  Specifically...

> Cautiously proceed forward with Cloud.gov.  We will want to integrate with them as fast as possible to discover any showstoppers quickly.
