### ISSUE TITLE
Story: View Funding Status of a CAN

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#304]
### User Story
As an CAN lead, manager, or budget officer, in order to know what funds are available, what has been spent, and what needs to be allocated, I want to see a funding status for a CAN in FY 2022.

### Pre-conditions
- A schema is in place in the database for a CAN's spending plan and other funding attributes. 
- Existing CAN data and related data structures are in place

### Acceptance Criteria
- [x] User can view a CAN's funding status total fiscal year funding (assuming FY 2022).
- [x] User can view a CAN's funding status funded YTD amount.
- [x] User can view a CAN's funding status pending funds.
- [x] User can clearly distinguish any negative dollar amounts from positive dollar amounts. - @haprin

-----------------------------------------

### Tasks

- [x] Backend
  - [x] Implement OESA in backend Django project.
  - [x] Figure out unit tests (they seem finicky when run outside of Docker)
  - [x] Get code coverage checks implemented. @tdonaworth 
  - [x] Get an end-to-end test created. @tdonaworth 
  - [x] Load testing. - @halprin 
  - [x] Figure out what `ops_site/admin.py` is all about
  - [x] Add linting (tox, PEP8?)
  - [x] Add additional code to support viewing elements mentioned in the AC and wireframes
- [x] Frontend
  - [x] Move UI to React project.
  - [x] Allow frontend to call backend in deployed environment.
  - [x] Remove the weird extra appended values to the frontend domain in cloud.gov
  - [x] Add UI elements to support viewing elements mentioned in the AC and wireframes
  - [x] Unit tests. - @halprin 
  - [x] Get code coverage checks implemented. - @halprin 
  - [x] Add linting (ESLint, Prettier?)
- [x] DevOps
  - [x] Pivot to GitHub Actions for CI.
  - [x] Pivot to GitHub Actions for CD.
  - [x] Add and configure Renovatebot.  Disable Dependabot.
  - [x] Ensure Dependabot is doing dependency vulnerability scanning.
  - [x] Have CD process do some set of testing before deploy - @halprin 
- [x] Other
  - [x] Update and create new ADRs.
  - [x] Update READMEs. - @haprin

### Definition of Done
- [x] Usability validated
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests passed
- [x] ~Automated integration tests passed~
- [x] Automated quality tests passed
- [x] Automated load tests passed
- [x] Automated security tests passed
- [x] ~Automated a11y tests passed~
- [x] 90%+ Code coverage achieved
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added

**Comment by kimschulke** [comment]
Here is some additional context into what the current labels mean according to 18F Designer who created the original wireframes. Please note these labels (phrasing, wording) might change as we iterate on the design.

<img width="491" alt="Screen Shot 2022-07-14 at 12 56 11 PM" src="https://user-images.githubusercontent.com/65555918/179039157-44f35a39-d9a2-4c32-ac5a-cfe4d7d46765.png">

**Comment by kimschulke** [comment]
Snapshot of additional rows we will be adding to test environment --

<img width="940" alt="Screen Shot 2022-07-14 at 1 01 36 PM" src="https://user-images.githubusercontent.com/65555918/179039933-e773432b-6fdd-408e-8f0c-f0a39df2ae1b.png">


Link to full screen prototype for Viewing a CAN --
https://www.figma.com/proto/PKFlN0Bq23KkpNI325XSZk/OPS-CAN-wireframes?node-id=1377%3A9247&scaling=min-zoom&page-id=1366%3A4240&starting-point-node-id=1377%3A9247

**Comment by jonnalley** [comment]
@halprin and others: One thing I read more than once in the user research findings were that it was more challenging to make sense of the fields/attributes when the various amounts of money (i.e. spent vs. remaining) didn't mathematically equate as they should.

**Comment by tdonaworth** [comment]
`Implement OESA in backend Django project.` OESA options were discussed between @halprin and myself. We will refactor in an upcoming story, but in the meantime will utilize the Django Rest Framework (DRF) for a very simplistic `controller`.

**Comment by tdonaworth** [comment]
We need additional research to determine the `spending plan` details.

**Comment by jonnalley** [comment]
As discussed today, these aspects of the funding status described in the story and  AC should just be static attributes for now @halprin @tdonaworth
