### ISSUE TITLE
Address certificate management

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#3083]
### Goals
* Address imminent staging environment TLS cert expiration on the listener for the SDLC app gateway (and any other certs expiring)
* Have automated renewal of TLS certs in all environments in place
* Documentation in place for cert management in the private repo in a markdown document or private repo wiki

### Tasks
- [ ] Investigate and experiment with necessary terraform to re-apply AppGW config to target the cert renewal only--ideally without messing up storage account output/parameters that 
  - [ ] If that doesn't plan out, form other options and experiment.
- [ ] Merge and apply any TF changes
- [ ] Document

### Additional Context
* 

### Resources
*
