### ISSUE TITLE
Import Phase 0 users to staging

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#3174]
### Goals
* Have users intended for migration phase 0 created in staging that will persist and not be part of sample/test data committed to the repo

### Tasks
- [ ] create a tsv 
- [ ] place TSV in correct place
- [ ] execute script pointed against the location above
- [ ] Verify users correctly created in staging

### Additional Context
#2861, #3077, and #3111 are all related and pre-requisites

**Comment by jonnalley** [comment]
John reported this was done on 12/5/2024
