### ISSUE TITLE
Update portfolio descriptions

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#3175]
### Goals
* Have portfolio descriptions in the OPS databases updated in all environments 
* Users don't see inaccurate / wrong descriptions for the OPRE portfolios

### Tasks
- [x] Solicit correct descriptions from each division
- [x] Refine and get approval on the correct text
- [x] Include the descriptions in the initial_data load when the portfolios themselves get created?
- [x] Import that text to staging ?
- [x] Import that text to the production environment?

### Additional Context
* 

### Resources
*

**Comment by jonnalley** [comment]
12/19
