### ISSUE TITLE
draft and send out phase 0 email

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#3201]
### Goals
* Draft and send out email to initial phase 0 participants

### Tasks
- [x] Verify feedback mechanism with Amare
- [x] Draft up email inviting users, cover, who, why, what, feedback, etc...
- [x] get any OPRE approval and decide who will send it out
- [x] send out

### Additional Context
* 

### Resources
*
