### ISSUE TITLE
Move Research Type & Special Topic/Population Components from Status-Change to Create-Agreement

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#3242]
### Goals
Remove Research Type and Special Topic/Population Studied Components from BL-Status-Change-Planned-to-Executing and add as metadata to Create-Agreement.

### Tasks
**UX**
- [ ] Explore design options for how to incorporate Research Type and Special Topic/Population Studied Components into Create Agreement (what order in the list, etc)
- [ ] Add Research Type and Special Topic/Population Studied Components into Create-Agreement on Dev Page
- [ ] Remove Research Type and Special Topic/Population Studied Components (and the Additional Info accordion) from Planned-to-Executing on Dev Page
- [ ] Update any annotations or business rules as needed (data should be required after draft to planned, same as the other agreement data, can be left blank with drafts BLs, but not with Planned BLs)
- [ ] Update Edit Agreement Screens to make sure new components are added
- [ ] Update View Agreement Details to make sure new components are added
- [ ] Let devs know when ready for dev

**Dev**
- [ ] Update to match new designs

### Additional Context
Details on improvement/why
- Simplifies status change on planned-to-executing
- Allows us to capture data Sheila needs for reporting (applied research vs evaluative)

### Resources
* https://docs.google.com/document/d/1rgV8AxhzoIE1pg5jRS0ncE5DwKQNpxhWmgnOp5ebXQs/edit?tab=t.0

**Comment by kimschulke** [comment]
Current design for status change planned to executing
<img width="665" alt="Image" src="https://github.com/user-attachments/assets/eb8fec0c-458f-4332-a779-c7718c859339" />

Move components to create agreement
<img width="498" alt="Image" src="https://github.com/user-attachments/assets/6e0e45b2-5fec-47c2-8aa0-2f8cbf90ed6e" />

**Comment by jonnalley** [comment]
This is a dupe of #1931 although not with the same UX tasks. I moved the tasks over to that existing story.
