### ISSUE TITLE
Update Review CANs Accordion on Status Change

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#3243]
### Goals
* Update Review CANs accordion on status change to match intended design/interactions
* When there is no data displayed in the Review CANs accordion (no BLs have been selected yet), then nothing should show in that accordion

### Tasks
UX
- [ ] Add mock up to show Review CANs accordion before any BLs are selected
- [ ] Include annotations to explain intended interactions
- [ ] Lets devs know when ready for dev

Dev
- [ ] update dev to match designs

### Resources
* Figma

**Comment by kimschulke** [comment]
Currently in dev
<img width="1083" alt="Image" src="https://github.com/user-attachments/assets/2a070dde-bfc6-4eb5-aeec-635553c2d2b7" />

**Comment by rajohnson90** [comment]
Scrolling through looking at this task and I can't find the design for what should be done? Nothing comes up on the CAN page when I search for Review CAN. Is the design done for this or should we take off the dev frontend ready? I will be the first to admit I'm bad at searching through our Figma designs so just let me know if I missed it.
