### ISSUE TITLE
Story: Create role-specific CAN view for _____

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#329]
### User Story
_As a ___, I want to only see CAN attributes relevant to my role so that I can be more efficient

### Preconditions
A user will have one and only one role.  This will need to be modified in a later story.

### Conditions of Acceptance
- [ ] User should be able to see the ____ attributes 
- [ ] User should not be able to see attributes not relevant to their role such as ____

-----------------------------------------

### Tasks
- [ ] Create data structure/mapping around the view/CAN attributes that are needed for different roles
- [ ] Introduce logic to check user role for the request and return CAN attributes accordingly

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_ 
* _Info already known or found, previous work that's been done?_

**Comment by fpigeonjr** [comment]
not sure about the AC here. We are filtering the CANs by:
_based on the user's division and the CANs portfolio division id_

**Comment by fpigeonjr** [comment]
saw this in the figma![Image](https://github.com/user-attachments/assets/aafceefc-3977-443e-baf7-ac16f0b39d34)

**Comment by fpigeonjr** [comment]
@jonnalley @kimschulke should we send this back to `needs-refinement`?

**Comment by jonnalley** [comment]
@fpigeonjr i believe I did on ZenHub at least

**Comment by fpigeonjr** [comment]
ok I'll send it back in GH Projects as well

**Comment by kimschulke** [comment]
This was always included in the original designs for CANs - to include a My CANs list just like the other list pages. It just has not been implemented.

Removing tags for design, draft and changing to frontend ready and backend ready in the backlog column

Let me know thoughts @jonnalley @npage123 @andressacurvelo 

[Designs in Figma](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=12012-119869&t=2WiNHcxDwqnzohcp-1)

**Comment by npage123** [comment]
@jonnalley @kimschulke @andressacurvelo Question, would this get implemented with out new restrictions on what users see?
