### ISSUE TITLE
Investigate cloud.gov organization sharing

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#33]
As engineers, we would like to know whether we will share a cloud.gov organization with OFA/TANF or have our own separately managed organization inside cloud.gov and what are the related security considerations and costs/benefits of both.

We want to know whether production data cans be adequately siloed so that TANF doesn't have access and admin privileges to OPRE data and vice versa.  We also want to know whether OPRE and TANF desire this degree of siloing.  We would like to surface some of the risks of not siloing the data to help OPRE and TANF make this decision.

What we propose for prototyping may be different than what we propose for production, and we should identify those options and the differences.

**Tasks**

- [x] Review cloud.gov documentation on roles and permissions across orgs and spaces and propose potential arrangements and tradeoffs.  
- [x] Distinguish how we might use cloud.gov differently between prototyping and production arrangements.
- [x] Document potential security risks/scenarios that OPRE and TANF should consider before deciding whether or not to share an org
- [x] Document potential costs and/or savings for both scenarios
- [x] Create draft memo, share with cloud.gov consulting software engineer
- [ ] Create cloud.gov sharing recommendations with a memo to Lauren at OFA and Sheila

**Resources**
https://docs.cloudfoundry.org/concepts/roles.html
https://docs.cloudfoundry.org/concepts/roles.html#activeroles

**Comment by carjug** [comment]
Documentation on roles and permissions in cloud.gov spaces

- https://cloud.gov/docs/orgs-spaces/roles/

Types of roles:
`OrgManager` - Invite and manage users, select and change plans, and set spending limits
`BillingManager` - Create and manage the billing account and payment info
`OrgAuditor` - Read-only access to org info and reports

`SpaceManager` - Invite and manage users, and enable features for a given space
`SpaceDeveloper` - Create and manage apps and services, and see logs and reports
`SpaceAuditor` - View logs, reports, and settings on this space

There will need to be at least one Organization-level user who has access to all users and their roles, this person would have the`OrgManager` roles. This person will be able to create users and assign their permissions at either the Organizational level or the Space level. This means that they have access to all users, regardless of the office they exist in within ACF.

At the space level the `SpaceManager`. has permissions to create users and assign their permissions at just the Space level.

My initial thought is to have one and only one `OrgManager` given the view they have into all Spaces in the Organization. At the Space level, I'm not as worried about having more than one `SpaceManager` since they don't have admin permissions outside the Space itself, but open to discussion here.

The one issue I see with having one `OrgManager` is that if that person is out, becomes sick, etc. then they are a blocker to being able to manage features for Spaces if that's needed.

**Comment by carjug** [comment]
This comment addresses the third task:
>Document potential security risks/scenarios that OPRE and TANF should consider before deciding whether or not to share an org

As stated in my above comment, there would need to be at least one account in the shared cloud.gov Organization that had access to every Space in the Organization. The security risk this presents is that there would be one additional user/account with access to production data in _both_ applications, in a siloed situation wherein OPRE and TANF were separate, would not exist.

**Comment by carjug** [comment]
WIP This comment addresses the fourth task:
** still need to find out the current average GB usage for the TANF application so we can get some more solid estimates.

>Document potential costs and/or savings for both scenarios

According to [cloud.gov documentation](https://cloud.gov/pricing/), a FISMA Moderate system costs $9300 / month plus $130 / GB memory per month

**Shared scenario**:
Both TANF and UNICORN are/will be FISMA Moderate systems, which means that both OPRE and OFA could share the OFA Organization, as well as the $9300 base cost and then pay their share of memory used per month as well.
There is no additional cost for additional Spaces inside a cloud.gov Organization.
This would mean a **savings of $4650 / month per application** and a **savings of $55800 / year per application**

**Separate scenario**
In the case that OFA and OPRE do not share an Organization, both offices would pay $9300 / per month plus $130 / GB memory per month, which factors out to be **$111600 / year base cost** plus variable memory costs

**Comment by carjug** [comment]
Sharing the draft memo 
https://docs.google.com/document/d/1qR4CoOLxBeFUoBzwxHF2y_xIV0YeQOzPJD7oVU1tUjQ/edit#

**Comment by carjug** [comment]
The draft memo has been sent to @smcnu82 , but she is out for the long weekend today, so we will pick this back up next cycle/week.

**Comment by carjug** [comment]
Still waiting on feedback from Sheila w/r/t this memo. She had verbally stated that it looked good, so will confirm with her tomorrow what she thinks next steps are.

**Comment by smcnu82** [comment]
Want to discuss with my management, but needed to prioritize other items this week due to procurement deadlines.  WIll schedule time to review after the meeting on 7/9.  Need to be able to frame the list of decision I need from them, so we can reduce the number of mtgs required

**Comment by ninamak** [comment]
In our Check In with Emily and Sheila today, it was requested that a time be scheduled next week to discuss this further.  @smcnu82 will catch Emily up to speed in the mean time.

Moving this back into To Do.

**Comment by amymok** [comment]
Based on conversation with Sheila yesterday, she wants to defer this conversation to after September.

**Comment by alexsoble** [comment]
Confirmed with our OPRE partners today that we won't be sharing. Cost savings are small; software tools are (often) team; developer and PM and PO time is (often/usually) expensive and a rare commodity. OPRE will get its own Org.
