### ISSUE TITLE
Story: CAN Status

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#344]
### User Story
As an OPRE staff member, when viewing an individual CAN I want to see a CAN's binary active status: active vs. inactive, so that I can quickly assess if it has funds in the current fiscal year 

### Acceptance Criteria
- [ ] User should be able to see the correct active/inactive status for a given CAN being viewed
- [ ] As an active CAN's funding is consumed or removed in a given FY and drops to $0, viewing that CAN's status should reflect inactive
- [ ] As an inactive CAN's funding is supplemented or changed in a given FY, and goes above $0, viewing that CAN's status should reflect active
- [ ] A CAN's status should dynamically change with the available funding toggling back and forth. 

-----------------------------------------

### Tasks
- [ ] Develop logic that determines the active or inactive state of a CAN based on if there is available funding in the current fiscal year
- [ ] Develop user interface elements that clearly but accessibly denotes a CAN's dynamically-discerned status

### Definition of Done Checklist
- [ ] Usability validated
- [ ] Design QA passed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] PR(s) have been merged to main with all the automated tests (load, quality, a11y, unit, etc..) and security scans that are a pre-requisite
- [ ] 90%+ Code coverage achieved
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* Some CANs receive no incoming funding in some fiscal years. Thusly, they would go inactive in those years. It's possible for CAN to both go active (receive funds) and inactive (lose/consume all funds) within the same calendar year
* How does multi-year funding affect this story description and AC?
