### ISSUE TITLE
Story: View list of CANs

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#346]
### User Story
_As a [type of user], I want to [do something] so that [this outcome]_

### Acceptance Criteria
- [ ] _How will we know when this story is done?  List here the desired behavior that must be enabled for this story to be considered done_
- [ ] _Consider positive behavior (this user can do this thing in this situation)_
- [ ] _Consider negative behavior (this user should not be able to do this thing in this situation)_

-----------------------------------------

### Tasks
- [ ] _Key pieces of work that will need to be done to meet the User Story and CoAs_

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests passed
- [ ] Automated integration tests passed
- [ ] Automated quality tests passed
- [ ] Automated load tests passed
- [ ] Automated a11y tests passed
- [ ] Automated security tests passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_

**Comment by fpigeonjr** [comment]
🤔 did we decided that the summary cards are not part of this story?

![Image](https://github.com/user-attachments/assets/ac0b0b4a-9c12-48b4-801f-f8345af11ba5)

**Comment by fpigeonjr** [comment]
Engineering Hours discussion 9/16/24 artifacts:

![Image](https://github.com/user-attachments/assets/e4dedbc4-22fe-4e53-bb9b-f24f50b84d1b)
![Image](https://github.com/user-attachments/assets/e740ab75-bcd8-439f-a364-a732cd91c47b)

**Comment by fpigeonjr** [comment]
> 🤔 did we decided that the summary cards are not part of this story?
> 
> ![Image](https://github.com/user-attachments/assets/ac0b0b4a-9c12-48b4-801f-f8345af11ba5)

@jonnalley did we have a separate issue for the summary cards?

**Comment by jonnalley** [comment]
@fpigeonjr just realized I never replied in GH to your comment above, Yes it's #2842

**Comment by fpigeonjr** [comment]
update from ENG Collab **10/8/24**:

![Image](https://github.com/user-attachments/assets/55840bc2-c440-421e-8b08-23e2833054b7)

**Comment by jonnalley** [comment]
10/11
