### ISSUE TITLE
Outline High-Level OPS Navigation

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#350]
**Goals**
Outline a high-level navigation for OPS to build a better understanding of the key functionality and main pages required to complete tasks. 

**Tasks**

- [x] Schedule time to discuss navigation with Sheila and Camille
- [ ] Consider possible approach (activity, format) for navigation discussion
- [ ] Create any activity templates or materials, as needed
- [ ] Facilitate discussion on navigation
- [ ] Create outline or visual to document navigation

**Additional Context**
This outline will serve as a starting point and will evolve and change as we continue to learn more.

**Resources**
[18F OPS Roadmap](https://app.mural.co/t/gsa6/m/gsa6/1630248640188/3105c3b385f17e2cedbc6c5bff2111ba59785520?sender=kschulke5503) includes some broad strokes of key functionality.

[Current navigation for MAPS](https://app.mural.co/t/gsa6/m/gsa6/1642820125533/1bdbb7c0148e41fee3770198e6daca5d1c359f74?sender=kschulke5503)

[18F Wiki on User Needs and Use Cases](https://github.com/HHS/OPRE-OPS/wiki/04-User-needs-and-pain-points)

**Comment by kimschulke** [comment]
Planning to discuss on Thursday, August 4th at 10am est

**Comment by jonnalley** [comment]
re-doing as #464
