### ISSUE TITLE
Outline OPS MVP / Product Roadmap

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#351]
**Goals**
Synthesize older 18F murals and collateral into a new Mural on features in scope for an MVP to propose and discuss with OPRE.  The intent would be to get a simple idea of what high-level features we'll plan to work on in what order and be able to add and move things around in the familiar "sticky note" Mural fashion.

This Mural can live on throughout the contract as a place for new ideas and proposals to be recorded for later discussion, refinement, prioritization, and eventually turn into stories here.

**Tasks**

- [x] Review and discuss 18F product roadmap
- [x] Create new Mural space to identify our own MVP and make changes
- [x] Draft MVP
- [x] Facilitate discussion with Sheila, Camille and Amare
- [x] Document decisions; create epics to track features
- [x] Create a space to track future ideas and features

**Comment by kimschulke** [comment]
**Resources**

[Slide deck on OPS transition](https://github.com/HHS/OPRE-OPS/wiki/01-Background-and-introduction-to-OPRE,-MAPS,-and-OPS) (at bottom of wiki page)

[18F OPS Roadmap Mural](https://app.mural.co/t/gsa6/m/gsa6/1630248640188/3105c3b385f17e2cedbc6c5bff2111ba59785520?sender=kschulke5503)
