### ISSUE TITLE
Conduct Initial Research for Portfolios

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#353]
**Goals** 
Conduct user research to better understand needs related to viewing a portfolio.

**Tasks**
- [x] Conduct initial research with Sheila and Camille
- [x] Identify additional questions or gaps to validate with end users (ongoing)
- [x] Summarize findings to inform design exploration

**Comment by kimschulke** [comment]
Mural board for research synthesis on portfolios: https://app.mural.co/t/flexion6734/m/flexion6734/1659968818171/331dc801759bfc90c65671aa12695bce671ec097?sender=kschulke5503

**Comment by kimschulke** [comment]
**Summary of feedback for initial design requirements**

- The long-term goal is to be able to view a portfolio and see the associated funding streams AND research projects, as well as any additional information related to that portfolio
- Sometimes people need to see funding/CANs across more than one portfolio
- Portfolios can be divided up by Team Leaders. Each Team Leader manages one portfolio.
- There's a need for better transparency (without meetings) and to be able to view the current status of a portfolio (including active vs inactive)
- It would be helpful to see notifications or visual indicators for action items and deadlines
- Every portfolio should have a description or link to the bio on the website
- It would be helpful to see when funds are going to expire
- It would be helpful to see who the COR is and who is on the Project Team which could later connect to a workforce management module
- It might be helpful to see the division level for all portfolios
- Portfolios are pre-defined and users don't need the ability to create new ones (although new portfolios might emerge in the future)
- It would be helpful to be able to pick and choose which portfolios you wanted to see side by side and possibly save those custom views
