### ISSUE TITLE
Explore Design Options for Viewing Portfolios

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#354]
**Goals**
Come up with 2-3 design options for viewing a portfolio

**Tasks**

- [x]  Research UI patterns and design inspiration
- [x] Mock up design options
- [x] Review options with team for feedback
- [x] Review / discuss options with Sheila, Amare and Camille
- [x] Identify additional questions or gaps for end users
- [x] Create additional user stories for further research and design iteration, as needed

**Comment by kimschulke** [comment]
Reviewed 3 initial design options with Sheila, Camille and Amare on August 16.

Round 1 design options included:
- Card view
- Left grid / right grid view
- Table view

**Comment by kimschulke** [comment]
Summary of feedback and next steps for continued design iteration is here: https://app.mural.co/t/flexion6734/m/flexion6734/1660681824129/685a073c4c9b1d239723340c9646b27f433db323?sender=kschulke5503
