### ISSUE TITLE
Story: CAN Status based on available balance

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#357]
### User Story
As an OPRE staff member, when viewing an individual CAN I want to see a CAN's binary active status: active vs. inactive based on available monetary balances, so that I can make more-rapid assessments about CANs

### Acceptance Criteria
- [ ] As an active CAN's funding is consumed/appropriated/removed in a given FY and drops to $0, viewing that CAN's status should reflect inactive only if it has no transactions in the given FY
- [ ] As an active CAN's funding is consumed/appropriated/removed in a given FY and drops to $0, viewing that CAN's status should stay active if transactions for the given FY are present.
- [ ] As an inactive CAN's funding is supplemented or changed in a given FY, and the available balance goes above $0, viewing that CAN's status should reflect active
- [ ] A CAN's status should dynamically change with the available funding toggling back and forth. 

-----------------------------------------

### Tasks
- [ ] Develop logic that determines the active or inactive state of a CAN based on the criteria outlined here
- [ ] Develop user interface elements that clearly but accessibly denotes a CAN's dynamically-discerned status

### Definition of Done Checklist
- [ ] Usability validated
- [ ] Design QA passed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] PR(s) have been merged to main with all the automated tests (load, quality, a11y, unit, etc..) and security scans that are a pre-requisite
- [ ] 90%+ Code coverage achieved
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* **A CAN is active if there have been any transactions in the fiscal year or if funding has been fully appropriated in the current fiscal year.**
* Some CANs receive no incoming funding in some fiscal years. Thusly, they would go inactive in those years. It's possible for CAN to both go active (receive funds) and inactive (lose/consume all funds) within the same calendar year
* How does multi-year funding affect this story description and AC?  it does not.
