### ISSUE TITLE
Story: CAN status based on funding source

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#358]
### User Story
As an OPRE staff member, when viewing an individual CAN I want to see a CAN's binary active status: active vs. inactive based on the source entity of its funding, so that I can make more-rapid assessments about CANs

### Acceptance Criteria
- [ ] As an active CAN that is funded by OPRE itself, as funds are fully appropriated, its status should remain active. 
- [ ] As an active CAN that is funded by OPRE itself, if no transactions are present for a given FY, its status should remain active. 

-----------------------------------------

### Tasks
- [ ] Develop logic that determines the active or inactive state of a CAN based on the criteria outlined here
- [ ] Develop user interface elements that clearly but accessibly denotes a CAN's dynamically-discerned status

### Definition of Done Checklist
- [ ] Usability validated
- [ ] Design QA passed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] PR(s) have been merged to main with all the automated tests (load, quality, a11y, unit, etc..) and security scans that are a pre-requisite
- [ ] 90%+ Code coverage achieved
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* CANs with funds from OPRE (as opposed to other offices or agencies) should always stay active and never go inactive.
* How does multi-year funding affect this story description and AC?  it does not.
