### ISSUE TITLE
Story: My Favorite Portfolios

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#382]
### User Story
As an OPRE staff member, I want to mark certain portfolios as ones I'm more interested in or preferred than others so that I can, both now and on an ongoing basis, consume additional details faster about the portfolios I care most about.

### Pre-conditions
* The terms "preferred", "favorite", and "selected" will be used interchangably in this story and are not necessarily prescriptive of any labeling in the user interface.

### Acceptance Criteria
- [ ] User can clearly discern which portfolios (in the list of all) are preferred/selected and which ones are not.
- [ ] User prominently can consume an expanded, but not exhaustive, set of details for portfolios marked as favorite/preferred.
- [ ] User does not see expanded set of details for portfolios not marked as preferred.
- [ ] The expanded set of details for a portfolio is hidden or removed from the user when that same portfolio is de-selected as a favorite.
- [ ] User's selection(s) of preferred portfolio(s) is at least partially persisted when user comes back to the list of portfolios in the same or new browser session.

-----------------------------------------

### Tasks
- [ ] Develop front-end code and other assets for completing the AC based on the agreed-upon design
- [ ] Populate database with sufficient seed data
- [ ] Develop back-end code for facilitaing the functionality described in the AC
- [ ] Add or update existing testing to accommodate this portfolio viewing

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests passed
- [ ] Automated integration tests passed
- [ ] Automated quality tests passed
- [ ] Automated load tests passed
- [ ] Automated a11y tests passed
- [ ] Automated security tests passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* Most of the user research is recorded in #381, #353, and #354.
* The persistence of the favorites/selection of projects will be limited since there is no concept currently of distinct users or authn/authz. This functionality and its persistence should be re-visited later once those larger features are present.
* Should there be a limit on the number of portfolios a user can favorite?
