### ISSUE TITLE
Story: Quotes and Humor on User Log In

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#383]
### User Story
As an OPRE staff member, I want to be prompted with meaningful and/or enjoyable content when I log in to OPS so that my experience is more pleasant and my positivity can be increased.

### Acceptance Criteria
- [ ] Upon user log in, the user is prompted with an inspirational quote if the day of the week is not Friday.
- [ ] Upon user log in, the user is prompted with a humorous but appropriate comic, meme, or other graphic of some kind if the day of the week is Friday.

-----------------------------------------

### Tasks
- [ ] Conduct research on inspirational quotes that would be the most meaningful and appropriate to the user base
- [ ] Schedule interviews with additional end users
- [ ] Synthesize research findings to identify design opportunities
- [ ] Revise design based on feedback

- [ ] Develop front-end code and other assets
- [ ] Develop back-end code or components

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests passed
- [ ] Automated integration tests passed
- [ ] Automated quality tests passed
- [ ] Automated load tests passed
- [ ] Automated a11y tests passed
- [ ] Automated security tests passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* Should consider leveraging any quality 3rd party APIs or services to return the quote or meme
* Should consider what limitations or restrictions need to be on the content of the quotes or meme

**Comment by kimschulke** [comment]
@jonnalley .... 😆 are we still planning to do this? might be able to close..?
