### ISSUE TITLE
Research on Portfolio Details

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#388]
### Goals
The goal of this research is to determine what information/functionality user's need on the Portfolio Details page

### Tasks
- [x]  Draft more design/layout options
- [x]  Review those options with Sheila and Camille
- [x]  Create research plan to validate design options
- [x]  Schedule and conduct interviews with additional end users
- [x]  Cross-synthesize research findings to identify user needs and potential solutions

### Additional Context
* 

### Resources
*

**Comment by kimschulke** [comment]
Research plan attached:

[Research Plan - Portfolio Details - August 2022.pdf](https://github.com/HHS/OPRE-OPS/files/9463226/Research.Plan.-.Portfolio.Details.-.August.2022.pdf)

**Comment by kimschulke** [comment]
Started to schedule user interviews. Our goal is to have all 7 interviews completed by 9/15 or sooner.

**Comment by kimschulke** [comment]
Status of the 7 interviews we'd like to complete for this research ---
2 interviews complete
3 interviews scheduled (9/6, 9/8, 9/12)
2 interviews pending availability (will follow up on 9/6)

**Comment by kimschulke** [comment]
Share out of research on Tuesday 9/20

**Comment by kimschulke** [comment]
Link to research synthesis and summary of findings - https://app.mural.co/t/flexion6734/m/flexion6734/1662136863597/564abb495b72f06592b13c50ea898cfaba5ffa43?sender=kschulke5503
