### ISSUE TITLE
Security Compliance Documentation

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#432]
### User Story
As a Security Engineer, I want to fully document how OPS complies with all Security Compliance needs so that any it is clear what security controls are being adhered to, and maintain a higher security posture.

### Acceptance Criteria
- [ ] User can easily view what Security Controls are being met, and how.
- [ ] User can easily see whether any current or past _Executive Orders_ are behind met.
- [ ] Auditor can see alignment to [FISMA moderate systems](https://csrc.nist.gov/CSRC/media/Projects/risk-management/documents/02-Categorize%20Step/NIST%20RMF%20Categorize%20Step-FAQs.pdf) requirements

-----------------------------------------

### Tasks
- [ ] Document Security Controls and any mappings required
- [ ] Document Incident Response processes
- [ ] Create easy to "read" diagrams that represent the application architecture and pipelines
- [ ] Document any additional _Executive Orders_ which are present.

### Definition of Done Checklist
- [ ] Usability validated
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Documentation updated or added

### Additional Context & Resources
Examples of a good representation of this exists here: [HHS/TANF-app Security-Compliance](https://github.com/HHS/TANF-app/tree/main/docs/Security-Compliance)

**Comment by jonnalley** [comment]
This is ongoing little by little and will be so for months now

**Comment by jonnalley** [comment]
Although we've made multiple passes through the full set of 800-53 controls already, we've recently heard that for the time being we'll just be focusing on ACF Tech's selection of "critical" controls
