### ISSUE TITLE
Spike: Explore user "groups"

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#442]
### User Story
As an OPS System Admin, I want to manage groups of users so that later administration of authorization can be easier.

### Acceptance Criteria
- [ ] A user can create a "group" after providing relevant inputs
- [ ] A user can add existing user accounts as belonging to, associated with, and "members" of a group
- [ ] A user can remove user account(s) that presently are members of a given group
- [ ] A user can view a list of groups
- [ ] A user can view the members of a given group
- [ ] A user can remove a groups without negatively affecting the user accounts

-----------------------------------------

### Tasks
- [ ] Create persistent store schema related to the concept of groups
- [ ] Create backend code related to the retrieval, listing, and updating of groups
- [ ] Create frontend code related to the retrieval, listing, and updating of groups in keeping with the design system

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests passed
- [ ] Automated integration tests passed
- [ ] Automated quality tests passed
- [ ] Automated load tests passed
- [ ] Automated a11y tests passed
- [ ] Automated security tests passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* This story does not cover topics related to using the users for anything or tying to 3rd party auth services, etc...

**Comment by jonnalley** [comment]
doubtful this will happen. can always resurrect if so
