### ISSUE TITLE
Investigate & Experiment with Permission Frameworks

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#448]
### Goals
* Have enough knowledge to make a decision on **what "permissions" model / package to use** based on our functional and security needs.
* Generate an ADR about the final decision.

### Tasks
- ~~[ ] Research [Django REST - Access Policy](https://github.com/rsinger86/drf-access-policy)~~
- ~~[ ] Research [Composed Permissions](https://www.django-rest-framework.org/api-guide/permissions/#composed-permissions)~~
- ~~[ ] Research [DRY Rest Permissions](https://www.django-rest-framework.org/api-guide/permissions/#dry-rest-permissions)~~
- ~~[ ] Research [Django REST Framework API Key](https://www.django-rest-framework.org/api-guide/permissions/#django-rest-framework-api-key)~~
- ~~[ ] Research [Django Rest Framework Roles](https://www.django-rest-framework.org/api-guide/permissions/#django-rest-framework-roles)~~
- [x] Research [Open Policy Agent (OPA)](https://www.openpolicyagent.org/), along with Flask Extension [flask-opa](https://github.com/EliuX/flask-opa)
- [x] Research [OSO](https://docs.osohq.com/index.html)
- [x] Research [SqlAlchemy-Auth](https://github.com/dhiltonp/sqlalchemy_auth)
- [x] Research [flask-authorize](https://flask-authorize.readthedocs.io/en/latest/)
- [x] Author the ADR
- [x] Clean up some `path to production` items like enforcing login, checking for JWT validation for each endpoint, manual list of allowed login.gov users, etc..

### Additional Context

The idea is to spin up a few branches experimenting with each different permission framework, and determine which we "feel" is better.

Updated to remove Django specific options, after the switch to Flask. Added new Flask options to look into.

**Comment by jonnalley** [comment]
Team intends today to mob on creating initial structure of the backend endpoint that would do the second call. See [Lucidchart diagram](https://lucid.app/lucidchart/d36f95e3-7e29-4182-95ea-f7829d777470/edit?viewport_loc=-166%2C18%2C1611%2C764%2C0_0&invitationId=inv_e89efce7-3a69-4d26-ae41-1301d8213e3c#)

**Comment by jonnalley** [comment]
@tdonaworth what's left here?  Are these tasks up to date in terms of what needs to be done in particular?

**Comment by jonnalley** [comment]
ADR is drafted [here](https://github.com/HHS/OPRE-OPS/blob/authz-documentation/docs/adr/018-use-open-policy-agent-for-authorization.md).

**Comment by jonnalley** [comment]
The branch `opa-experiment` has the most up-to-date work on this issue thus far

**Comment by jonnalley** [comment]
From Tim: got a lot updated in the frontend to facilitate our backend jwt needs, created a basic “User” page for additional testing.

**Comment by jonnalley** [comment]
tentatively thinking of OPA for now. Pausing on any further review or bakeoff until we have more real-world rules and policies to apply. An ADR is drafted in the branch mentioned above
