### ISSUE TITLE
Create UI color palette, fonts, and style guide

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#463]
### Goals
OPS needs a defined and standard color palette, font(s), and style guide.

### Tasks
- [x] Produce and document color palette
- [x] Document accepted font(s)
- [x] Document annotation style - @andressacurvelo 
- [x] Produce and document style guide - @andressacurvelo 

### Additional Context
* 

### Resources
*

**Comment by jonnalley** [comment]
Kim and Andressa reviewing color palette choices

**Comment by jonnalley** [comment]
color palette being chosen and tested for a11y
