### ISSUE TITLE
Portfolio Team Leader(s)

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#466]
### User Story
As an OPRE team member, I want to know the Team Leader(s) for each portfolio so that I know who has overall responsibility for that portfolio

### Acceptance Criteria
- [x] User can see the Team Leader(s) for any chosen portfolio

-----------------------------------------

### Tasks
- [x] Communicate leads for each portfolio @kimschulke
- [x] Provide design assets @kimschulke 
- [x] Create frontend components for the AC
- [x] Create backend components for the AC
- [x] Create a11y tests
- [x] Create e2e tests

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests passed
- [x] Automated integration tests passed
- [x] Automated quality tests passed
- [x] Automated load tests passed
- [x] Automated e2e tests passed
- [x] Automated a11y tests passed
- [x] Automated security tests passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* ~~There's only 1 team leader per portfolio~~
* Could there ever be a single human being a team leader for more than one portfolio?

**Comment by jonnalley** [comment]
@kimschulke @andressacurvelo  Can/should we grab headshot pictures from the OPRE website?

**Comment by kimschulke** [comment]
A little background information on Team Leaders and what they do:
- Allocate, monitor and track team funding for their specific research portfolio
- Serve as a Subject Matter Expert (SME) to advance research in their area
- Coordinate with budget team
- Understand project staffing
- Manage procurement of contracts and activities within each contract
- Collaborate across other research portfolios to utilize available funding

**Comment by kimschulke** [comment]
<img width="362" alt="Screen Shot 2022-10-11 at 2 45 18 PM" src="https://user-images.githubusercontent.com/65555918/195174089-bef9c470-6f4a-45d0-b8ee-2d1e5b020a5a.png">

<img width="847" alt="Screen Shot 2022-10-11 at 2 45 28 PM" src="https://user-images.githubusercontent.com/65555918/195174111-8aebf5b2-ac71-474a-b273-1af124b8f2f3.png">

**Comment by kimschulke** [comment]
For now, we can use a placeholder avatar for people's profile photo

**Comment by kimschulke** [comment]
Program Support and Data Governance are being combined into one portfolio called Social Science Research Demonstration (SSRD). This portfolio will list two Team Leaders: Nicole Deterding and Valeria Butler

**Comment by kimschulke** [comment]
Current design for Portfolio Team Leaders here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details-2?node-id=706%3A12865

**Comment by jonnalley** [comment]
might defer on avatar discussion and decisions till Tim gets back
