### ISSUE TITLE
Change Fiscal Year

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#467]
### User Story
As an OPRE staff member, I want to see details for a portfolio based on different fiscal years in order to have a picture of the funding beyond the boundary of a single fiscal year.

### Acceptance Criteria
- [x] User should be able to select a fiscal year to view information on
- [x] Once chosen, the user should be able to discern which fiscal year they're currently viewing and data currently displayed to the user should update to reflect the fiscal year chosen
- [x] The default fiscal year (if none is explicitly chosen by the user) should be the current fiscal year (advances on 10/1 at 00:00 ET of each calendar year)
- [x] User should not be able to select more than one fiscal year at a time
- [x] The fiscal year need not persist for a session or across (peer) pages
- [x] However, subordinate pages should persist the chosen fiscal year. i.e. overall Portfolio Detail's research project page and then going to an individual research project's details... 

-----------------------------------------

### Tasks
- [x] Refactor front-end as needed to deal with state and other issues
- [x] Move Fiscal Year selector to above the tabs
- [x] Craft the React component(s) necessary in keeping with the style and color scheme
- [x] Create any other frontend code for achieving the AC
~- [ ] Create any backend code for achieving the AC~
- [x] Create e2e tests
- [x] Create a11y tests

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests passed
- [x] Automated integration tests passed
- [x] Automated quality tests passed
- [x] Automated load tests passed
- [x] Automated a11y tests passed
- [x] Automated security tests passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
~- [ ] Build process updated~
~- [ ] Documentation updated or added~
~- [ ] Feature flags/toggles created~

### Additional Context & Resources
* The UI Component would ideally be reusable across other pages that will need the same thing later on (i.e. CAN)
* Are people & staffing info different across fiscal year ?

**Comment by jonnalley** [comment]
@andressacurvelo @kimschulke could use a review on this that the UI works as designed please.

**Comment by kimschulke** [comment]
<img width="887" alt="Screen Shot 2023-01-06 at 3 14 52 PM" src="https://user-images.githubusercontent.com/65555918/211092466-625a46cc-6b4f-42cc-94ad-289ade07909e.png">

**Comment by kimschulke** [comment]
There are some other issues with spacing but they relate more to other user stories so we can adjust those then (spacing between the tabs and spacing between section header and instructional text)

**Comment by jonnalley** [comment]
@kimschulke I'm so sorry, I don't know how I missed this update.  Did this already get fixed in the dev environment?

**Comment by fpigeonjr** [comment]
[PR641](https://github.com/HHS/OPRE-OPS/pull/641) should resolve spacing issues @kimschulke.

**Comment by kimschulke** [comment]
@fpigeonjr Looks great! Thank you!
