### ISSUE TITLE
View a Portfolio's CANs

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#479]
### User Story
As an OPRE team member, I want to view the internal CANs of a portfolio, so that I can make better decisions about funding for a portfolio.

### Preconditions
The portfolio's current fiscal year funding is all that needs to be handled for the time being.

### Acceptance Criteria
- [x] User can see all internal CANs being utilized within the portfolio
- [x] User can see the total (aka original) FY funding for each internal CAN
- [x] User can see planned, obligated, in execution, and remaining funds for that internal CAN
- [x] User can see the expiration date for each CAN (the date money needs to be obligated but not spent before)

-----------------------------------------

### Tasks
- [x] Update wireframe to remove filter and search components - @kimschulke @andressacurvelo 
- [x] Exploring options for layout of the CANs to accommodate column requirements
- [x] Build backend code to satisfy AC @tdonaworth 
- [x] Build frontend code to satisfy AC @johndeange 
- [x] Format dollar amounts properly

### Definition of Done Checklist
- ~~[ ] Usability validated~~
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated & passed
- [x] Automated integration tests updated & passed
- [x] Automated quality tests updated & passed
- [x] Automated load tests updated & passed
- [x] Automated a11y tests updated & passed
- [x] Automated security tests updated & passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [ ] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
~~* Need to decide if search/filter should be its own story or combined with the CANs table~~
~~* Need further research/design on the interaction for a possible search feature. If a user searches, does the table narrow its results? Does search make sense for CANs table or do they typically want to see all the CANs/funding sources?~~

**Comment by kimschulke** [comment]
As discussed on 10/11, we are creating an additional status for "In Execution" and this column will need to be added to the CANs Table

**Comment by kimschulke** [comment]
Need to make sure it's okay to remove the "appropriation term" column in order to fit the "in execution" column.

Also need to discuss changing any instance of "funding" to "budget" to account for the fact this lists shows CANs for the portfolio budget and is not reflective of other CANs that might be used from other portfolios to fund cross-collaboration research projects.

**Comment by jonnalley** [comment]
It is ok to remove that column that Kim mentioned in the previous column. Additionally, CAN number should be listed as a separate column from CAN description (aka name)

**Comment by kimschulke** [comment]
We have 3 options for layout/design of the CANs Funding YTD information. We are planning to review with our stakeholders on Tuesday 10/25.

**Comment by kimschulke** [comment]
Current design of Portfolio CANs here: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details-2?node-id=706%3A12865

**Comment by jonnalley** [comment]
Initial iteration deployed to dev!
