### ISSUE TITLE
SPIKE: Investigate `django-simple-histor` for History

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#480]
### Goals
* Determine if `django-simple-history` would work for our needs to maintain `transaction history` within the system.

### Tasks
- [ ] Install `django-simple-history`
- [ ] Enable `history` on at least one model
- [ ] Determine whether the 'history' is enough for our audit needs
- [ ] Generate basic reports

### Additional Context
* We had internal discussions around the needs to maintain transaction records, for security and audit purposes, as well as user defined needs to know what changed, when.

### Resources
* https://django-simple-history.readthedocs.io/en/latest/signals.html

**Comment by jonnalley** [comment]
no longer needed as moving away from Django
