### ISSUE TITLE
Create User Engagement Strategy

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#484]
### Goals
* Outline a process and strategy for engaging OPRE as we design and build OPS

### Tasks
- [x] Create activity/mural for team discussion
- [x] Brainstorm/discuss engagement options
- [x] Document decisions/experiments to try
- [x] Outline how we will engage OPRE as we continue work on Portfolios and later user stories

**Comment by kimschulke** [comment]
Draft activity for creating a user engagement strategy: https://app.mural.co/t/flexion6734/m/flexion6734/1665681359696/e3fb208152052b25d42c45c75b9989a3f02e6316?sender=kschulke5503
