### ISSUE TITLE
Sorting of Portfolio CANs

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#488]
### User Story
As an OPRE budget officer, I want to re-order the internal CANs for a portfolio to more easily see where there are resource constraints.

### Acceptance Criteria
- [ ] User can change the sorting of a portfolio's internal CANs from the default sorting.
- [ ] Any attribute of the list of CANs should be a sortable index.
- [ ] The sorting should be in ascending or descending order.

-----------------------------------------

### Tasks
- [ ] Build frontend components to satisfy AC

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_

**Comment by jonnalley** [comment]
This is likely no longer needed based on current design

**Comment by jonnalley** [comment]
I think our current design removed the need for this?

**Comment by jonnalley** [comment]
regardless of the current design, this should also get resolved by #976. Closing as dupe unless there's an objection.
