### ISSUE TITLE
Portfolio CAN expiration awareness

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#489]
### User Story
As an OPRE staff member, I want to be alerted to portfolio funding that expires immintently so that funds are not lost or expired unintentionally

### Acceptance Criteria
- [ ] The user should receive an indication when a portfolio's internal CANs are nearing expiration. 

-----------------------------------------

### Tasks
- [ ] Determine what the threshold(s) is/are for imminent expiration
- [ ] Create frontend code to render portfolio's CANs differently based on imminent expiration

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* Having a different color for expiring funds would be helpful...but don't break a11y
* Email notifications are not in scope for this story and will be post-MVP
