### ISSUE TITLE
Portfolio Research Projects

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#491]
Following the higher-level research and knowledge gathering that took place in #388 on research portfolios, focused but strategic research is needed specifically on (OPRE) research projects that belong to a portfolio.

### Goals / Questions to answer
* Naming / Terminology to use that will be the most helpful
* What other funding sources within OPRE contribute to my research project
* What percent of a specific portfolio budget is used across that specific portfolio's research projects?
* Where is the money for this portfolio being used in other research projects?
* Have enough information to write informed stories based on user needs

### Tasks
- [x] Prep design options for user feedback @kimschulke @andressacurvelo 
- [x] Create research plan to outline what we hope to learn / draft any questions or activities as needed
- [x] Identify who we will include in this research
- [x] Iterate on ideas and options based on initial feedback
- [x] Schedule interviews to share design options for feedback
- [x] Facilitate interviews
- [x] Synthesize / summarize feedback
~- [ ] Refine design based on feedback~ (will be added as tasks on the stories created below)
- [x] Create user stories to outline specific user needs

**Comment by kimschulke** [comment]
Making some changes to the design based on feedback from stakeholders. Planning to iterate some more before sharing with end users for feedback and ideas.

**Comment by kimschulke** [comment]
Made improvements to the design based on stakeholder feedback. Planning to share this week!

**Comment by jonnalley** [comment]
Shared and got great feedback from stakeholders

**Comment by kimschulke** [comment]
Making a few design changes based on stakeholder feedback. Will share updates via slack and then starting scheduling user interviews next week

**Comment by kimschulke** [comment]
1 interview completed so far

**Comment by jonnalley** [comment]
Research thus far has not been conclusive and more is needed. Additional interviews scheduled and requested for next week.
