### ISSUE TITLE
Research Project Assignees

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#496]
### User Story
 As an OPRE team lead, I want to see what team members are assigned to what research projects so that I can help ensure that research projects have the right quantity of  and mixture of staff members allocated for the portfolio's 

### Acceptance Criteria
- [ ] For each portfolio's research project(s), a listing of assigned staff should be visible to the user

-----------------------------------------

### Tasks
- [ ] Build frontend components needed to meet AC
- [ ] Build backend components (data structures, business logic, database schema, etc...) needed for staff members to be associated to research projects

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_

**Comment by kimschulke** [comment]
Don't we already have this need met via Team Members on each Agreement? @jonnalley

**Comment by jonnalley** [comment]
@kimschulke well, that would show up on a per-agreement level now, yes, but to me, it sounds that the user need is to see this aggregated at the project level.  As in the people & teams tab or something. 

And that info could all come from the team members for each contract, but that's only part of the total solution unless I'm missing something.

**Comment by jonnalley** [comment]
#668 already addresses this, 🎉 🌮
