### ISSUE TITLE
DevEx: Flask Migration

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#499]
### Goals
* Reduce backend bloat and footprint

### Tasks
- [x] Get docker container issues resolved @tdonaworth 
- [x] Migrate Auth endpoints @tdonaworth 
- [x] Migrate Portfolio Model @xlorepdarkhelm 
- [x] Migrate Portfolio dependencies @xlorepdarkhelm 
- [x] Handle Tests @xlorepdarkhelm 
- [x] Restructure as needed. @xlorepdarkhelm 
- [x] Author new ADR and update & deprecate existing ADR 5 for the move from Django to Flask @xlorepdarkhelm 
- [x] Update repo README @xlorepdarkhelm 
- [x] Repopulate DB
- [x] PR issued and merged @xlorepdarkhelm 
- [x] Cutover frontend
- [x] Remove Django remnants
