### ISSUE TITLE
Understand AWS and OCIO options

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#5]
### Goals

To be able to validate the db migration plan, we need to know which AWS to request access to and which OCIO to work with.  Specifically:

- Better understand which AWS environment (ACF or HHS) we'd prefer for validating db migration strategy (and later for building)
  - Confirm that HHS AWS exists
  - What are Sheila/Z’s concerns about ACF AWS?  Personnel?  Security?  Reliability?
  - Do Sheila/Z expect ACF OCIO to make a fuss about using HHS AWS instead of ACF AWS?
  - Do Sheila/Z expect it to cause complications if the cloud.gov org is owned by ACF and the AWS is owned by HHS, esp for ATO?
  - Does Sheila/Z known anyone using HHS cloud?  Can they put us in touch?
- Confirm which OCIO we'd be working with
  - Does HHS OCIO even grant ATOs?
  - When/why does ACF OCIO need to be involved?  Is it based on where the org sits?  Or based on which tech is used?
  - If we use HHS AWS and HHS cloud.gov, would we still need to work with ACF OCIO?
- Determine how to request access, who to work with in OCIO

### Tasks

- [ ] Document which ACF/18F systems use cloud.gov and/or ACF or HHS AWS
- [ ] Document from 18F perspective how they approached OCIO to request access, who they worked with, what they care about, what challenges they ran into, etc
- [ ] Document from Lauren F (TANF) same as above
- [ ] Meet with Sheila/Z to discuss AWS and OCIO, determine next steps
- [ ] Pre-schedule meeting with OCIO since it's hard to get on their calendar
