### ISSUE TITLE
Tech Debt - Make updates so that code can be released to new cloud.gov environment.

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#503]
### Goals
* Make all updates needed to ensure the application can be released to the new cloud.gov environment.

### Tasks
- [x] Update manifest.yml
- [x] Update deployed_run.sh
- [x] Update account credentials
- [x] Troubleshoot frontend <> backend communication
- [x] Documentation update

### Additional Context
* With the new cloud.gov org created, we'll need to make updates to the code and CD processes to ensure the automated release jobs can push updates to the new location.
