### ISSUE TITLE
Prep for OPRE staff meeting - Dec 2022

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#536]
### Goals
* Be prepared for the OPRE all-hands meeting on Dec. 7th

### Tasks
- [x] Outline agenda ( topics to cover and talking points)
- [x] Assign presentation roles (who will present what)
- [x] Create slides or visuals, as needed
- [x] Prep OPS test environment to demo with possible use cases to walk through? 
- [x] Prepare Menti/survey questions
- [x] Prepare intake method for future involvement 
- [x] Send PDF of slides to stakeholders
- [x] Send FAQ to stakeholders based on questions submitted

### Additional Context
Agenda to include:
- Preview of whats coming next
- Call to action - how people can get involved

**Comment by kimschulke** [comment]
Draft agenda as discussed during Thursday OPRE check-in ---

- Intro to our team
- Overview of OPS MVP
- Quick overview of HCD- iterative process, users at center, etc
- Provide a place to contribute ideas for OPS, challenges, etc (google form, email, mentipoll, etc)
- What we’re doing now; portfolios
- Activity on budget tab and research projects tab
- Future ways to get involved; sign up for certain topics over next few months
- Propose a future (maybe Jan) HCD overview and design principles workshop; see who’s interested

**Comment by kimschulke** [comment]
Draft slides here: https://docs.google.com/presentation/d/1buy82-fB02wAckr_XFM8hUhIcC3_Jh73e0lwlghs34Q/edit#slide=id.g192ec899012_0_0

**Comment by jonnalley** [comment]
menti results sent
