### ISSUE TITLE
Handling over and under budget scenarios

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#556]
### User Story
As a OPRE budget officer, when viewing portfolio details I want to clearly see if I'm currently or on track to be exceeding the budget for my portfolio so that I can ultimately rectify the situation of being over budget. 

### Acceptance Criteria
- [ ] User can clearly and accessibly see when the remaining total funds for a portfolio is less than zero as distinguished from when the remaining total is greater than 0. 

-----------------------------------------

### Tasks
- [ ] Add frontend changes to facilitate the AC
- [ ] Add backend changes to facilitate the AC

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* External notifications can come later in a different story
