### ISSUE TITLE
User help, guidance, and clarifications

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#557]
### User Story
As an OPRE staff member, I want clarification on terms and concepts when viewing portfolio details so that I don't make wrong judgements about a portfolio's funding.

### Acceptance Criteria
- [ ] User has a means to access on-demand definitions and clarifications on terms used when viewing budget information on a portfolio's details. 
- [ ] User can opt to remove these extra definitions and clarifications if and when desired. 

-----------------------------------------

### Tasks
- [ ] Design options for tool tips or other solution (consider global application)
- [ ] Write copy / explanatory text for each term/concept 
- [ ] Share design options with stakeholders and team for feedback
- [ ] Provide design assets / components to developers to implement
- [ ] Add frontend components and code to facilitate the AC
- [ ] Add backend components and data to facilitate the AC

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
*

**Comment by jonnalley** [comment]
#2929 and #3416 seem to be taking care of the spirit if not the everything else for this story. Feel free to clarify and re-open if needed.
