### ISSUE TITLE
Total portfolio funding breakdown by CAN

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#561]
### User Story
As an OPRE staff member, I need to see the breakdown of a portfolio's total funding grouped by each managed CAN so that I can make judgments as to the funding diversity. 

### Acceptance Criteria
- [x] The user can see at a glance, the contributions each CAN makes towards the total funding for a given portfolio

-----------------------------------------

### Tasks
- [x] Decide how existing components will be altered to accommodate this new component
- [x] Make frontend changes to accommodate the new component 

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
~- [ ] Design/tech debt eliminated~
~- [ ] Build process updated~
~- [ ] Documentation updated or added~

### Additional Context & Resources
* This is basically bringing back the donut or pie chart we had originally that had a breakdown of a portfolio's funding by CAN.

**Comment by jonnalley** [comment]
[Direct link to wireframe](https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details-2?node-id=1062%3A21891&t=eHZ4Uetezwm2DFh1-4)

![Screen Shot 2022-11-29 at 10.43.10 PM.png](https://images.zenhubusercontent.com/62d197f3ac3c133657ebc448/3611f1af-25be-4e71-9771-bc54e56d74e0)

![Screen Shot 2022-11-29 at 10.44.17 PM.png](https://images.zenhubusercontent.com/62d197f3ac3c133657ebc448/16c1af67-5423-4ee6-8c9e-a4d8a2014369)

**Comment by kimschulke** [comment]
Here is the design: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details-2?node-id=1244%3A23423&t=Brhv0pBYfmSuXLIo-1
