### ISSUE TITLE
CAN Appropriated Year

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#562]
### User Story
As an OPRE staff member, when viewing a portfolio's CANs, I need to clearly know what fiscal year a given CAN was appropriated so that I can use that as part of other decision-making efforts. 

### Acceptance Criteria
- [ ] When viewing portfolio details, the listing of CANs should include the fiscal year appropriated for each CAN.

-----------------------------------------

### Tasks
- [ ] Create design options/recommendation for displaying the appropriated year
- [ ] Create database and backend schema to accommodate this new attribute
- [ ] Create frontend code/components to display this CAN attribute

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* The FY appropriated will never change. By contrast, the "expiration" of a CAN can definitely change over time if it's ever de-obgliated an re-obligated.

**Comment by jonnalley** [comment]
Some of the designs being discussed for #597 may make this moot
