### ISSUE TITLE
Carry-forward funds as part of Total Funding

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#571]
### User Story
As an OPRE staff member, I want to know how much of a portfolio's total funding is new in this fiscal year vs. carried forward from a prior fiscal year so that I can be aware of options I have for spending and fund renewal.

### Preconditions
* We only need to accommodate the current/default fiscal year as part of this story. Accommodate viewing a separate fiscal year isn't technically part of the criteria for this story.

### Acceptance Criteria
- [x] User can quickly see at a glance, and separately: the total funding, new funding in the current/default fiscal year, and how much money was carried-forward from prior fiscal years aggregated across all CANs the portfolio manages. 

-----------------------------------------

### Tasks
- [x] Build any backend logic, data structures, table columns, and code to support the concept of funds carried forward from prior fiscal year at a CAN level. See additional notes below.
- [x] In our sample dataset json files, have some 5-year CANs utilizing this concept for demonstration purposes
- [x] Build new and modify existing frontend components to display the new carried forward funds on a portfolio's detail.
- [x] Add unit tests for funding calculation
- [x] Modify API endpoints and refactor backend to be more adherent to REST standards and remove unneeded code, tech debt @johndeange 
- [x] Add versioning to API @johndeange 

### Definition of Done Checklist
- [x] UI works as designed
- [ ] ~OESA: Code refactored for clarity~
- [ ] ~OESA: Dependency rules followed~
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
~- [ ] Design/tech debt eliminated~
~- [ ] Build process updated~
~- [ ] Documentation updated or added~

### Additional Context & Resources
* Some CANs gets new funds every fiscal year, aka 1-year money.  In that case, that is always "new money".
* "5-year CANs" carry forward money from year-to-year, at precisely the fiscal year boundary. The carried forward amount will be loaded/handled manually by hand, with no automation. 
* A team leader needs to know that they have 15 million to spend total, but that only 12 million is new in that fiscal year.
* This is related to #562, which communicates the similar idea but at a CAN level as opposed to the whole portfolio.
* See the opening 5 minutes of the 11/14 meeting recording for more info.

**Comment by jonnalley** [comment]
[Direct link to wireframe](https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details-2?node-id=1062%3A21891&t=eHZ4Uetezwm2DFh1-4)

![Screen Shot 2022-11-29 at 10.47.57 PM.png](https://images.zenhubusercontent.com/62d197f3ac3c133657ebc448/97528524-f170-4bbf-a3c5-50fec52c805e)

**Comment by kimschulke** [comment]
Here are the designs: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/View-Portfolio-Details-2?node-id=1244%3A23423&t=Brhv0pBYfmSuXLIo-1

**Comment by jonnalley** [comment]
@kimschulke @andressacurvelo Can we get a review on the DoD for this that the UI works as designed ?

**Comment by kimschulke** [comment]
@jonnalley @johndeange - the layout looks good in the staging environment - a minor fix to the labels/wording -

Per the Figma design, labels should read "FY 2022 New Funding" (FY is dynamic to the drop down selection) and "Previous FY Carry-Forward

**Comment by jonnalley** [comment]
@kimschulke thanks, fixed in #598

**Comment by kimschulke** [comment]
Sorry all @jonnalley @tdonaworth @johndeange  - still not quite right - the middle card should read "FY 2023 New Funding" not "FY 2023 New Budget"

**Comment by jonnalley** [comment]
@kimschulke my apologies. The dev environment has the fix and is codified in PR #600
