### ISSUE TITLE
clean up zero-dollar formatting and display

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#595]
### User Story
As an OPRE staff member, I want to see zero-dollar amounts consistently and clearly displayed.

### Acceptance Criteria
- [x] Zero dollar amounts should still include a US dollar sign across all components
- [x] Display a single-digit dollar amount (0) with no cents after the decimal.

-----------------------------------------

### Tasks
- [x] Go through the components where currency is displayed and modify to insure AC is met

### Definition of Done Checklist
- [x] UI works as designed
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
~- [ ] Design/tech debt eliminated~
~- [ ] Build process updated~
~- [ ] Documentation updated or added~
~- [ ] Feature flags/toggles created~

**Comment by kimschulke** [comment]
Reviewing UI Design, but this is still showing as $ 00.00 instead of $ 0
