### ISSUE TITLE
Work with OCIO to get access to AWS

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#6]
### Goals

To be able to validate the migration plan, we need access to AWS.  Specifically:
- Carly needs to be able to log in herself (via CLI not just console), have API privileges, have permissions to spin up instances, change settings, etc.
- OCIO needs to set up a VPC for us, or allows Carly to (less likely)

### Tasks

- [ ] Prepare what we want OCIO to do
- [ ] Make case for why this is all ok
- [ ] Meet with OCIO

### Risks
- OCIO may not be ok with the open connection (VPC peering) to the source db
