### ISSUE TITLE
Experiment on Figma Components

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#644]
### Goals
* Determine if Figma components ease the iterative and creative design process
* Determine how much current reusability there is with our design
* Assess what tasks will be on future stories, or totally net-new stories should result 

### Tasks
- [x] Meet with and learn from other Flexioneers about design systems in Figma
- [x] Create reusable Figma component and adapt current pages to use that component.
- [x] Make judgements on time savings, if any

**Comment by fpigeonjr** [comment]
saw [this](https://www.youtube.com/watch?v=hnx5UWaP_jo) on YouTube and is some Figma inspiration for components from my boy Kevin Powell.

**Comment by fpigeonjr** [comment]
started working on fonts and color styles
