### ISSUE TITLE
DevEx: Styled Components

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#647]
### Goals

- [ ] Integrate styled components into my React components.
- [ ] Refactor existing CSS classes to styled components in order to gradually move the project towards using only styled components for styling.
- [ ] Continue to use and maintain the Styled-Components going forward to ensure a consistent design throughout the project.

-----------------------------------------

### Tasks
- [ ] Research Styled-Components and how it can be integrated into a React project.
- [ ] Install the Styled-Components library by running the command `npm install styled-components`.
- [ ] Create styled components using the `styled` function.
- [ ] Test the project to ensure that the styling is being applied correctly and that there are no conflicts with existing styles.

**Comment by fpigeonjr** [comment]
seem to be ok with styled modules for now, may re-open if we could benefit from this library.
