### ISSUE TITLE
OpEx: Database Schema Migration

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#650]
### Goals
* Provide a way to migrate DB schema from one version to another

### Tasks
- [x] Investigate and experiment adding [Alembic](https://alembic.sqlalchemy.org/en/latest/) to our stack.
- [x] Perform any other experiments and changes ?
- [ ] Author and merge a PR with an ADR and any other code changes

### Additional Context
* We need a better way to upgrade DB schema between deployments, eventually without destroying the data each time
* To avoid confusion with the title, this is not directly instigated by or related to the migration of MAPS data

**Comment by jonnalley** [comment]
2/29
