### ISSUE TITLE
Update global footer

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#651]
### Goals
* OPS footer should be functional and in keeping with ACF Tech and HHS requirements

### Tasks
- [x] Assess current footer on MAPS
- [x] Coordinate with OPRE Tech Lead to see if any changes should be implemented
- [x] Submit and merge PR for OPS footer changes

**Comment by jonnalley** [comment]
should have been closed a couple months back
