### ISSUE TITLE
Object-level security in the persistence layer

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#652]
### Goals
* To experiment with and understand the benefits or drawbacks of utilizing object-level security features of the persistent layer and implement them in a desired way, if appropriate. 

### Tasks
- [ ] Assess PostgreSQL object-level security features
- [ ] In a determined test bed, implement desired object-level security, knowing that multiple options might exist
- [ ] Come up with test cases for the object-level security implemented
- [ ] Execute those test cases and discern outcomes from the results
- [ ] If appropriate, implement any decided-upon configuration in all environments
- [ ] Author and merge an ADR accordingly

**Comment by jonnalley** [comment]
The notion of something like this came up recently with discussions on #5627. That being said, I don't see any realistic need or bandwidth for this to be worked on given current circumstances. will close for now.
