### ISSUE TITLE
Look into React based permissions frameworks

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#653]
### Goals
* Investigate and experiment with permissions frameworks implemented by and within the scope of React

### Tasks
- [ ] Assess landscape of what React permissions frameworks exist and would be appropriate for our application and needs
- [ ] Decide on experiments to use and tests to run
- [ ] Implement those experiments and tests
- [ ] Author/update and merge any ADRs

**Comment by jonnalley** [comment]
The notion of something like this came up recently with discussions on #5627. That being said, in order to adhere more to OEA, we likely won't go down this path for that impetus or any other in the lifetime of this work. And even if we do, we can reopen at that time.
