### ISSUE TITLE
Temporary User Account

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#655]
### User Story
As an OPRE System Admin, I want users without an active PIV to log in to OPS if the need arises so that they can use the app while their PIV situation is being resolved independently.

### Acceptance Criteria
- [ ] System Admin can create/provision OPS user accounts which can have an end date set. The end date may not be more than 60 days from the current date and that date 60 days out should be the default.
- [ ] The account will no longer be usable for authentication/authorization after the set date.
- [ ] These accounts will utilize a 2FA method other than PIV that will be regulated and handled by the authn provider (AMS)

-----------------------------------------

### Tasks
- [ ] _Key pieces of work that will need to be done to meet the User Story and CoAs_

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* In our compliance documentation, these are known as "temporary accounts"

**Comment by jonnalley** [comment]
This need no longer exists. Temporary account management will be done solely within AMS
