### ISSUE TITLE
Ensure all utilization of JWTs is secure and adheres to best practices.

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#660]
### User Story
As a Security Engineer, In order to provide secure utilization of JWTs for API access and/or Session use, I'd like to validate that the JWTs follow all the proper best practices.

### Acceptance Criteria
- [ ] _Users shall only be able to have a single active Session available at any given time [Sidejacking Attack]._ Ref #659
- [ ] _The JWT is stored securely on the Client Side_

-----------------------------------------

### Tasks
- [ ] Research the best way to store the JWT on client side (`sessionStorage` vs. `Secure Cookie`)
- [ ] Research whether a Revocation List is needed, or whether "User Context" (sidejacking prevention) would [facilitate this](https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html#no-built-in-token-revocation-by-the-user) need. 
- [ ] Implement [secure client-side storage](https://cheatsheetseries.owasp.org/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.html#token-storage-on-client-side) of JWTs
- [ ] Implement tests/mechanisms to ensure only a single active user-session is available
- [ ] Create automated tests to ensure JWTs are secured.

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_
