### ISSUE TITLE
Logging of New/Modified Budget Lines

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#676]
### User Story
As an OPRE System Admin, I want all budget line creation transactions to be recorded for later reporting and analysis purposes within OPS.

### Acceptance Criteria
- [x] OPS persistently logs/stores metadata and transaction info when new and modified/updated budget lines are created including the user requesting/making the budget line, timestamp, and values supplied. 
- [x] Storage of budget line modifications should include the old and new values.
- [x] These records should be immutable by an OPS user
- [x] These records should be retained for indefinitely for OPRE audit/investigation log purposes, independent of NIST/FedRAMP logging requirements

-----------------------------------------

### Tasks
- [x] Experiment and decide on systems, frameworks, or any tooling needed to implement the needed logging or other storage needed
- [x] Implement IaC or backend changes to meet the AC
- [x] Create or update ADRs as needed
- [x] #1194
- [x] #1201 @xlorepdarkhelm 

### Definition of Done Checklist
- [x] OESA: Code refactored for clarity
- [x] OESA: Dependency rules followed
- [x] Automated unit tests updated and passed
- [x] Automated integration tests updated and passed
- [x] Automated quality tests updated and passed
- [x] Automated load tests updated and passed
- [x] Automated a11y tests updated and passed
- [x] Automated security tests updated and passed
- [x] 90%+ Code coverage achieved
- [x] PR(s) have been merged to main
- [x] Design/tech debt eliminated
- [x] Build process updated
- [x] Documentation updated or added
- [x] Feature flags/toggles created

### Additional Context & Resources
* When a workflow/approval process is added to budget line creation/updating, that approval process will need to be logged and recorded as part of the overall transaction of the creation/update--but that is all a separate story
* Users consuming and using this stored metadata is covered in #679 and #680

**Comment by jonnalley** [comment]
Some other decisions need to be discussed and made by devs regarding this

**Comment by stevtek** [comment]
I did some experiments with triggers and with SQLAlchemy and can demo/discuss this.
Here's a few notes:
* I am thinking we want a log of diffs, like JSON of what changed and by who and when for each save
```json
{
  "id": 1,
  "updated_by": "userid?",
  "update_on": "2023-05-11T10:13:21.765",
  "changes": {
    "name": {
      "from": "the name before",
      "to": "the new name"
    },
    "notes": {
      "from": "the notes before",
      "to": "the new notes"
    }
  }
}
```
* You can also do this with save copies of the row on every create/update/delete and calculate the DIFFs on the fly. 
  However, since the goal is just to show who change what/when, logging diffs seems to have to most PROs
* This can be approached from the SQLAlchemy/ORM side of the database side (triggers)
* Database side (triggers)
  * we can use something like this https://github.com/stevtek/pg-json-audit-trigger 
  * all changes are logged into a central audit.log table
    * includes JSON of diff - what fields changed and from/to what 
    * columns/indices so that you can 
      * query for all changes to certain record (assuming the table has simple PK)
        * find changes to budget_line_item with id=1
      * query for all changes by a user across all tables
  * would need to add a column for `updated_by` similar to `created_by`
  * handles changes that bypass app/ORM
* SQLAlchemy/ORM
  * before commit/flush we can get both old and new values using `get_history` (from sqlalchemy.orm.attributes),
    except for new IDs,
    and after the flush we can get the new ID, but we can no longer can old values
    * OpsDbHistory is missing the IDs of newly created records
    * is there a good solution to this?
      * can't use strict relationships since the logs need to stay after deletion
  * currently there's not a column for who made the edit (updated_by)
  * any changes that bypass the ORM will not be logged
  * could enhance OpsDbHistory for a solution to all tables
    * add columns/indices similar to the audit table use above

**Comment by tdonaworth** [comment]
We discussed this some today and the takeaways are as follows:
* Our current `history` systems supports insertion of records based on specific event types (sa session state), and records the `event_type`, `event_details` (the objects state at the time of change), and `created_by` (who requested the event). 
  * This is a manual implementation that is a place holder until something like [SQLAlchemy-Continuum](https://sqlalchemy-continuum.readthedocs.io/en/latest/) is updated to support SA v2.0
  * It's initial inception was just a PoC, and can/should be expanded to support what we need, like expanding out some of the details for better query-ability.
* We discussed the use of DB Triggers as well, and saw a few good use-cases (specifically for monitoring anomalies outside the application, or ETL events that occur outside the app, which would be unavailable via an SA ORM method (above).
  * In the meantime, we'll have to create a small PoC to demonstrate this. We all agree its also a good solution, but would need special attention for data-migration actions, and could become redundant for day-to-day audit logging, so might only resort to it for special cases - TBD.

Moving forward, the plan should be to further build out the ORM method, expanding the `history` model to make it easier to query, and add query abilities to the GET endpoint for history.

**Comment by stevtek** [comment]
WIP: https://github.com/HHS/OPRE-OPS/pull/1163

**Comment by tdonaworth** [comment]
Notes from discussion with @stevtek:

For creating the `GET` endpoint for the ops_db_history;
* Create a generic `GET` that takes a search parameter, to return back any possible `history` record
* Create dedicated endpoints for different types of `history` queries, like `getAgreementHistory`, that would be able to do per-endpoint permission checks more easily, than a large/complex permission check in a single endpoint.
* Instead of querying a `history` simply return the History data along with the base object query; ie: if you query for an Agreement, also return the Agreement history records. This would piggyback any permission checks that are performed on the `Agreement` itself, which should have the same permission requirements.

**Comment by jonnalley** [comment]
Is our path forward here any different now with the advent of #1204 ?

**Comment by jonnalley** [comment]
review on 8/11
