### ISSUE TITLE
[8] Create database from sample database's exported schema/data (Oracle)

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#71]
### Goals
* Mimic having an Oracle database in an AWS environment using a sample DB so that we do not need to access the vendor's DB or worry about data security

### Tasks
Assuming TTS Sandbox can be used
- [x] Create Oracle DB in TTS Sandbox
- [x] Load exported schema and data from sample DB script into new TTS DB
- [x] Verify you can access the new TTS DB and things copied over correctly (e.g., can write select statements, etc)

### Resources
* [Sample DB](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_GettingStarted.html)

### Dependencies
* We need to determine if we can perform this in the TTS Sandbox (#61) 
* If we cannot perform this under TTS sandbox, we can do it when we have access to the ACF/HHS AWS environment

### Additional Context
Overall purpose of testing with a sample DB:

- Identify the steps and effort it takes to do the migration by practicing it
- Identify the AWS services we need to use
- Identify more targeted asks on getting ACF/HHS AWS permission, and add to our previous request
- Identify what we need from the vendor
- Identify the potential issues we may run into when migrating and perform early mitigation

**Comment by amymok** [comment]
I noted everything I did for this task in the [Database Migration Notes](https://docs.google.com/document/d/1-sC6CKvfy-M8Gx77HWGyCZmmO8ilUTgCyz1yeau1lu0/edit#heading=h.7pg4e9cnshrl).

Everything looks good to move forward to the next step.  It wasn't intuitive to verify because there's no criteria defined by the [sample DB](https://github.com/aws-samples/aws-database-migration-samples/tree/master/oracle/sampledb/v1).  So I came up with the steps I did to verify the source database.  At least this is good enough to continue with the next steps of the milestone.

@carjug @ninamak if you want to take a look at this to review.

@alexsoble this is FYI for you if you are interested.

**Comment by ninamak** [comment]
@amymok Awesome documentation!  LGTM!

**Comment by carjug** [comment]
I can't wait to hear about all this tomorrow! Looks good to me 🚢

**Comment by carjug** [comment]
I'd say this one can be moved to "Done"!
