### ISSUE TITLE
Portfolio Research Project Spending Summary

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#727]
### User Story
As an OPRE staff member, when viewing a portfolio's research projects, 

### Acceptance Criteria
- [ ] _How will we know when this story is done?  List here the desired behavior that must be enabled for this story to be considered done_
- [ ] _Consider positive behavior (this user can do this thing in this situation)_
- [ ] _Consider negative behavior (this user should not be able to do this thing in this situation)_

-----------------------------------------

### Tasks
- [ ] _Key pieces of work that will need to be done to meet the User Story and CoAs_

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* _Any additional information that would be useful to share about this work_
* _Dependencies, constraints?_
* _Info already known or found, previous work that's been done?_
