### ISSUE TITLE
[8] Perform homogeneous migration of schema with sample database (Oracle to Oracle)

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#74]
### Goals
* Test if we can use the AWS DMS (database migration service) to migrate the schema when the databases are in the same VPC and are of the same type (easiest case).

### Tasks
- [x] Create 2nd Oracle DB in TTS Sandbox
- [x] Migrate schema (determine if the schema conversion tools need to be used)
- [x] As a dev, I want to know the specific Oracle user privileges for the target database to be able to copy in the schema from a source database.

### Acceptance of Criteria
- There is an Oracle DB in our TTS sandbox with a schema that matches the sample DB schema

### Resources
- [Migrating your source schema to your target database using AWS SCT](https://docs.aws.amazon.com/dms/latest/userguide/CHAP_GettingStarted.SCT.html)

### Additional Context
Overall purpose of testing with a sample DB:

- Identify the steps and effort it takes to do the migration by practicing it
- Identify the AWS services we need to use
- Identify more targeted asks on getting ACF/HHS AWS permission, and add to our previous request
- Identify what we need from the vendor
- Identify the potential issues we may run into when migrating and perform early mitigation

**Comment by amymok** [comment]
I migrated the database using two methods, and they are now in the target Oracle database.  Notes and screenshots are documented in [Steps to migrate database schema (Oracle to Oracle) section in Database Migration Notes](https://docs.google.com/document/d/1-sC6CKvfy-M8Gx77HWGyCZmmO8ilUTgCyz1yeau1lu0/edit#heading=h.yrghlqb0cz00)

In the section on [Verify Oracle target database](https://docs.google.com/document/d/1-sC6CKvfy-M8Gx77HWGyCZmmO8ilUTgCyz1yeau1lu0/edit#heading=h.34y1ipyxfnba), you can see how the two schema compare at the high level for source and target.

This is ready for review: @carjug @ninamak, cc @alexsoble

**Comment by carjug** [comment]
@amymok so sorry this fell off my radar! Can you remind me again what the resources I should fill out in the body are?

**Comment by amymok** [comment]
@carjug I don't remember either!  I will just add a link to the AWS instruction I used!

**Comment by carjug** [comment]
LGTM, Amy!

**Comment by ninamak** [comment]
@amymok Is there anything in particular it would be helpful for me to pay attention to when reviewing?  I read through the doc (super comprehensive!), and if the other devs feel it meets their needs, then LGTM!

The only thing I can think of: in the "Additional Context" section of this card, it says that some of the overarching goals of this migration testing work include:

> Identify the AWS services we need to use
Identify more targeted asks on getting ACF/HHS AWS permission, and add to our previous request
Identify what we need from the vendor

Did work on this particular card help you identify any of those things?
