### ISSUE TITLE
See Agreement's vendor when adding Budget Line

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#772]
### User Story
As an OPRE COR or Team Lead, when adding a budget line for an agreement (that has at least one existing BL) in in execution status, I want to know the associated partner/vendor/grantee for that agreement so I can see who the work is being completed with and where funds in these budget lines are going to.

### Pre-condition
The partner/vendor/contractor/grantee field has already been added as an attribute to agreements as part of #774 and #775

### Acceptance Criteria
- [ ] User can see or understand what the partner/vendor/contractor/grantee is for a chosen agreement in the process of creating a budget line

-----------------------------------------

### Tasks
- [ ] Determine how many vendors per agreement
- [ ] Add new information to agreement summary card and provide design assets to developers
- [ ] Update ProjectAgreementSummaryCard and StepCreateBudgetLines.jsx as needed

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

**Comment by kimschulke** [comment]
Need to add a field for vendor/contractor/partner. Known as vendor now. Consider "Partner" which encompasses the various types OR make it dynamic to type the of agreement.

Grants = Grantees
Contracts = Vendor
IAAs = Trading Partner

Determine how many partners per agreement

**Comment by jonnalley** [comment]
@kimschulke regarding the first two tasks above, that will actually get done as part of #775, which has to be done first. 

> Need to add a field for vendor/contractor/partner. Known as vendor now. Consider "Partner" which encompasses the various types OR make it dynamic to type the of agreement.
> 
> Grants = Grantees Contracts = Vendor IAAs = Trading Partner
> 
> Determine how many partners per agreement

**Comment by jonnalley** [comment]
I think we need to come back and revisit the need or text for this

**Comment by tdonaworth** [comment]
Is this not already completed on other `Create Agreement` / `Create BL` tasks? (shows in the Agreement Summary at the top of the BLI page)?

**Comment by jonnalley** [comment]
@tdonaworth No--At the time of an agreement's creation, let's say for a contract in example, the vendor that the contract has been awarded to wouldn't be known yet, so thusly couldn't possibly be displayed yet.  This is for adding a BL to an existing agreement where the agreement has already been at least partially awarded away to a 3rd party of some kind and now a new budget line is being added.

This is something not present in MAPS today and was a request from the PO.

**Comment by kimschulke** [comment]
I think this might be accomplished through the updated expanded row for budget lines #5459 @jonnalley @npage123 @andressacurvelo let me know what you think

We now show the vendor on the expanded row of budget lines within an agreement and it includes vendor, if there is a vendor added.

<img width="900" height="430" alt="Image" src="https://github.com/user-attachments/assets/379c05f2-7315-4286-b68f-5906e41a221e" />
