### ISSUE TITLE
Dynamic BL attributes

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#773]
### User Story
As an OPRE COR or Team Lead, when creating budget lines I want to see or be able to provide atomic/normalized information that varies based on the type of agreement and procurement shop chosen instead of trying to put in structured data in a non-structured place.

### Acceptance Criteria
- [ ] When creating a budget line, once a user has selected an agreement and a procurement shop, the user can provide input for base/option years and/or Service Components.

-----------------------------------------

### Tasks
- [ ] Procure OPRE business rules around which agreement types and procurement shops handle service components, CLINs, and severable/non-severable contracts
- [ ] Build logic into Gherkin/BDD rules

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* Currently in MAPS and before this story, users would be putting in according to arbitrary non-uniform rules
* Sheila will ask the procurement team to send us a matrix of what procurement shops will have what options based on which agreement types
