### ISSUE TITLE
Create an Assisted Acquisition (AA)

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#788]
### User Story
As an OPRE staff member, I want to create a new assisted acquistion so that I can facilitate research or program work in support of a project goal or topic.

### Acceptance Criteria
- [x] Users can specify to create an agreement of type Partner: AA and as part of the process select who the partner agreement is between. 
- [x] User can provide other required agreement attributes for creating an agreement (of type Partner: Assisted Acquisition) and that it is persistently stored
- [x] User should see an indication of some kind that the creation was successful
- [x] User can add budget line(s) and SCs to the agreement at the time of agreement creation.
- [ ] All relevant agreement history messages are created for BL and agreement creation

-----------------------------------------

### Tasks
- [x] Conduct research as needed
- [x] Explore options and outline workflow
- [x] Get feedback from OPRE
- [x] Design
- [x] Share designs with stakeholders and other OPRE team members for feedback
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

##### BE
- [x] Update backend model
- [x] #4090
 - [x] #1061 @xlorepdarkhelm
 - [ ] BDD/Gherkin for Assisted Acquisition 
    - Create business logic rules
    - Validate business logic against any created rules.
 - [ ] Create 5-10 test AA agreements for E2E testing purposes
 - [x] #4560
 - [x] #4479
 - [x] #4503
 - [x] #4129
 - [x] #4181

##### FE
- [x] Create helper function to control which Agreement attributes to render for a given Agreement Type
- [x] Refactor EditAgreement component to use helper function for conditionally rendering Contract attributes
- [x] Add support to EditAgreement component to use helper function for conditionally rendering AA attributes
- [x] Remove existing hacks for AAs
- [x] Tech Debt: Add SC support to `AgreementHistory` #3674 

##### API
- [ ] Update OpenAPI spec

##### Data
- [x] #4189

**DEV DISCUSS** - Determine how we want to change the controls displayed for different Agreement Types

### Definition of Done Checklist
- [ ] UI works as designed (UX team)
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] New design/tech debt documented (if applicable)
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* There are AA-specific attributes that will need to be added on to both the agreement and any BLs that belong to the AA.

**Comment by kimschulke** [comment]
"final" designs are just about ready for another run through with OPRE ✅

**Comment by kimschulke** [comment]
Designs are [ready for dev in Figma](https://www.figma.com/design/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?node-id=19445-47366&t=jdYDOSM9JPmyoA9y-1)! This includes creating an AA, viewing an AA, editing/approvals, and status change.

Let us know if developers want to walk through the designs when you are ready to get started.

**Comment by fpigeonjr** [comment]
need to add some Test Criteria as mentioned in our last team-collab

**Comment by jonnalley** [comment]
@fpigeonjr the backend allows for that possibility, yes. Realistically though, I can't envision how that would ever realistically happen.

**Comment by kimschulke** [comment]
Not sure if this is ready for UX/UI Review, but in testing create an AA in staging, there is an error on step 2 of the create wizard when attempting to add a services component

**Comment by npage123** [comment]
I just tested as well and got the same results of successfully being able to create an AA in both environments.

https://github.com/user-attachments/assets/82984f42-6ff4-4a99-aa6c-9a2ed5b3196e
https://github.com/user-attachments/assets/13e6af38-d5cf-425e-8635-096ef814241d
