### ISSUE TITLE
Create BLI Details - "Total Summary Cards" Components 

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#809]
### Goals
Create 3 Total Summary Cards that go under the Preview table #747 .

### Tasks
- [x]  Draft Total Summary Card
  - Total of the draft/new budget lines they are entering
- [x] FY Total Summary Card
  - Total of the budget lines within the current FY only. "FY 2023" text should change depending on what FY is current.
- [x]  Agreement Total Summary Card
  - Total of all budget lines on the entire agreement - everything in the table

### Additional Context
* dependencies #747 

### Resources
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/4629398/229550333-b8664aef-525a-4c47-b341-82b8951248aa.png">
