### ISSUE TITLE
More robustly-calculated procurement shop fees

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#815]
### User Story
As an OPRE staff member, when entering a new agreement, I want the procurement shop fee to be calculated correctly and dynamically so that I can be confident OPS will store correct data about the agreement

### Acceptance Criteria
- [ ] User can add a procurement shop on a budget line belonging to an agreement of varying types and the amount is correct for the given agreement type.

-----------------------------------------

### Tasks
- [ ] Acquire fee logic and possibilities from the budget team. In other words, find out rates for each agreement type and shop and if there's any rate changes based on dollar amount (range).
- [ ] Change backend model
- [ ] Change backend logic
- [ ]  Update frontend

### Definition of Done Checklist
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
* In current efforts for the procurement shop fee, each shop has an assigned rate and the fee amount is calculated  based on the assigned rate * BL amount.

**Comment by jonnalley** [comment]
I believe this is being done with #2167, it's pre-requisites, and related subtasks.
