### ISSUE TITLE
Dynamic population of new grant budget lines

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#817]
### User Story
As an OPRE staff member, when creating a new grant, I want new budget lines to be automatically generated based on details I provide about the new grant agreement itself so that I can minimize my time on error-prone data entry. 

### Acceptance Criteria
- [ ] OPS will pre-populate budget lines for a new grant based on the amount of individual grants, total dollar amount of the grant(s), and the number of years for the grant(s).
- [ ] OPS will not be expected to create those budget lines automatically if the user has omitted the number of years or a dollar amount
- [ ] The dates/FY of the resulting budget lines should be set correctly as a default for the successive year(s) they represent of the full set
- [ ] The amount of money on each budget line should be equal for all grants and years on the draft BLs. Any shortcoming should be deducted from the final year

-----------------------------------------

### Tasks
- [ ] Update frontend component behavior when user reaches the correct step of creating a grant
- [ ] Determine if there needs to be any santity checking on the values for number of years and implement accordingly

### Definition of Done Checklist
- [ ] Usability validated
- [ ] UI works as designed
- [ ] OESA: Code refactored for clarity
- [ ] OESA: Dependency rules followed
- [ ] Automated unit tests updated and passed
- [ ] Automated integration tests updated and passed
- [ ] Automated quality tests updated and passed
- [ ] Automated load tests updated and passed
- [ ] Automated a11y tests updated and passed
- [ ] Automated security tests updated and passed
- [ ] 90%+ Code coverage achieved
- [ ] PR(s) have been merged to main
- [ ] Design/tech debt eliminated
- [ ] Build process updated
- [ ] Documentation updated or added
- [ ] Feature flags/toggles created

### Additional Context & Resources
*
