### ISSUE TITLE
Add budget lines from Agreement selection to <PreviewTable />

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#819]
### Goals
Add budget lines from Agreement selection on step one to <PreviewTable /> as seen here:

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/4629398/230106162-b29e1e69-2a2c-44ac-9997-5d6b63b43a97.png">

### Tasks
- [x] Refactor `frontend/src/pages/budgetLines/PreviewTable.jsx` to add any budget lines from `./AgreemenSelect` 
- [x] Update edit icons to only show duplicate
- [x] copy icon to right
- [x] on duplicate existing bl, change to logged-in user.

### Additional Context
When they click the arrow, it will change directions and an expansion row will appear. For draft budget lines, the options to edit, delete or duplicate will float to the bottom of the row. _For existing/current budget lines, the only action is to duplicate. They cannot edit or delete existing/current budget lines from the Create a Budget Line workflow._

### Resources
#674
