### ISSUE TITLE
Add Project and Agreement Summary Box 

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#844]
### Goals
Add Project and Agreement Summary Box.

### Tasks
- [X] add agreement data from state
- [X] add project data from state
- [X] add procurement shop data from state

### Additional Context
- Displays the project and agreement selected from the previous page.
- We also removed the procurement shop data field from creating the budget line user flow.
- If the agreement has existing/current budget lines, the procurement shop will auto-select what procurement shop is being used. The user will be unable to edit or change it. All budget lines on an agreement have to use the same procurement shop.

### Resources
<img width="936" alt="image" src="https://user-images.githubusercontent.com/4629398/231304668-420d324c-4188-45c1-bcdb-ea661396715a.png">

**Comment by fpigeonjr** [comment]
:thinking: I noticed that the Procurement Shop select is not present anymore.
Does that mean that it will be set by the Agreement selected in Step One?

**Comment by jonnalley** [comment]
> 🤔 I noticed that the Procurement Shop select is not present anymore.
> Does that mean that it will be set by the Agreement selected in Step One?

Yes, thank you!
