### ISSUE TITLE
[8] Create a "Hello World" application in 18F cloud.gov sandbox

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#85]
### Goals
* Verify that we can set up a minimal application using our chosen tech stack that can be pushed to cloud.gov

### Tasks
- [x] Choose a Django version to use and create a "Hello World" app
- [x] Manually push to 18F cloud.gov sandbox
- [x] Create a Postgres DB and link it to the app
- [x] Give access to the app to others on the team

### Conditions of Acceptance
* Any member of this team can access the app and see "Hello World"
* People who are not members of this team cannot access the app

### Additional Context
* If we get a decision about how OPRE wants to set up their cloud.gov org & space before this issue is ready to be taken on, we will set up this application in that space rather than in the 18F sandbox.

**Comment by carjug** [comment]
@amymok @alexsoble I was planning on just going with the latest version of Django (3.2.5). Is there any reason I shouldn't do this by y'all's estimation?

**Comment by amymok** [comment]
@carjug Looking at [the LTS releases](https://www.djangoproject.com/download/#supported-versions), 3.2.x is the best option.  So yes, 3.2.5 sounds good!

**Comment by carjug** [comment]
Not totally sure the 4th task can happen without me just sharing my TTS sandbox credentials directly with other devs. @amymok do you have any ideas here?

**Comment by carjug** [comment]
@amymok ready for review!

**Comment by carjug** [comment]
@ninamak ready for your review, see https://opre-ops-test.app.cloud.gov/hello_world/

**Comment by ninamak** [comment]
Can confirm I can access it! :tada: 
How would I confirm that someone who is not on the team cannot access it?

**Comment by carjug** [comment]
Oh @ninamak the URL is public, the task above is meant to give access to the developers (I can also give you access if you have a cloud.gov account) to the cloud.gov dashboard for the application.

**Comment by ninamak** [comment]
Ok, that was a misunderstanding then.  As we start building the app, let's keep an eye out for when we need to make the URL non-public and make sure we have a story for that.
