### ISSUE TITLE
[4] Set up automated test framework and test coverage tooling

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#88]
### Goals
* Set up coverage.py to check for test coverage
* Set up automated test framework

### Tasks
- [x] Determine what automated test framework to use
- [x] Write a basic/dummy test using the test framework
- [ ] Update CircleCI config file to run automated tests with coverage.py as part of CI/CD
 
### Conditions of Acceptance
- [x] Test suite runs
- [ ] Coverage stats are returned (expect 0% coverage)

### Resources
* https://engineering.18f.gov/python/ (advises pytest as the default choice)

**Comment by alexsoble** [comment]
@ninamak This isn't the decision we came to. We decided not to use any third-party services to visualize code coverage & code quality for now. We'll use Python libraries like https://coverage.py/ to measure and report instead within our CI/CD.  

https://github.com/18F/OPRE-Unicorn/issues/35#issuecomment-880242858

**Comment by ninamak** [comment]
Tagging at @amymok as I was just the documenter :)

**Comment by amymok** [comment]
@alexsoble I read [this comment](https://github.com/18F/OPRE-Unicorn/issues/35#issuecomment-880131684) thinking we are going to CodeClimate Quality, and the "another option" is a point, but not the decision, but only briefly looking at the later comments.  Sorry, to have misunderstood that.  I understand the point now, we want to start with coverage.py first.  I am good with that.

So the change would be Set up Coverage.py
