### ISSUE TITLE
[4] Set up GitHub Dependabot for dependency scanning

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#90]
### Goals
* Set up dependency scanning to ensure we're checking for vulnerabilities with any of the libraries we use. 

### Tasks
- [x] Research how other 18F teams have set up GitHub Dependabot (e.g., TTAHub)
- [x] Research on GitHub docs on how to configure it
- [x] Set it up

### Conditions of Acceptance
* We receive confirmation that we're set up
* [We don't get any errors when it runs](https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/troubleshooting-dependabot-errors)

### Additional Context
* We don't want to set this up in the 18F repo; we'd want to set this up in the HHS repo #83 

### Resources
* #36

**Comment by carjug** [comment]
<img width="989" alt="Screen Shot 2021-08-13 at 12 39 39 PM" src="https://user-images.githubusercontent.com/10871517/129422318-a6751573-bee7-4c9d-9407-7e3a3a0f3e5c.png">

Dependabot has been enabled on the repository, but I have yet to see it work yet. I merged a test PR with a package in the requirements.txt that is out of date and has a security vulnerability (according to this snyk page: https://snyk.io/vuln/SNYK-PYTHON-KERAS-1536745), and I'm not sure how often dependabot runs, so I'm going to leave as is over the weekend and see if we get any alerts by Monday.

**Comment by carjug** [comment]
<img width="843" alt="Screen Shot 2021-08-17 at 12 31 00 PM" src="https://user-images.githubusercontent.com/10871517/129781184-7d66e763-3435-497a-abc9-e35267e5b69a.png">
Woo!! 

Deleting Keras from the requirements.txt as it was just done as a test of dependabot

**Comment by carjug** [comment]
@amymok @alexsoble @ninamak dependabot set up! verify at https://github.com/HHS/OPRE-OPS/pulls where you can see an automated dependabot PR for updating the django package.

**Comment by alexsoble** [comment]
@carjug Woooohoooo! LGTM! As well as checking out the automated dependabot PR I took a look at https://github.com/HHS/OPRE-OPS/pull/128, looks good! 🎉

**Comment by amymok** [comment]
Yay!  LGTM! 🎉 ❣️

**Comment by ninamak** [comment]
I don't have much to add here, so if everyone else is 👍 , then LGTM!
