### ISSUE TITLE
Design CANs-related data table(s)

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#91]
### Goals
* Design and understand the data tables needed to allow OPRE to view CAN information

### Tasks
- [x] Design an [Agencies table](https://airtable.com/tblGGRgffwAm6oV3h/viw42XXeFHzgoXwuB?blocks=hide) 
   - Name (short text)
   - Nickname (short text)

- [x] Design a [Personnel table](https://airtable.com/tblPe0l9XDDPor9ED/viwzRcyxs9S8Ikn3C?blocks=hide) 
   - Name ( [First Name] + [Last Name] )
   - First Name (short text)
   - Last Name (short text)
   - Role (multi-select)
       - The value options are unlikely to change often, though it would be useful for the user to be able to make changes themselves rather than make a dev request 
       - Current options = COR, Non-COR/Contractor, Team Leader, Division Director, Budget Officer, Administrator
   - Division (single-select)
       - The value options are unlikely to change often, though it would be useful for the user to be able to make changes themselves rather than make a dev request 
       - Current options = DCFD, DDI, DEI, DFS, OD

- [x] Design a [CANs table](https://airtable.com/tblC1gcLbcE5wou4Z/viwkZHevQYTEb1rRF?blocks=hide)
   - CAN Name ( [CAN Number] + "(" + [CAN Nickname] + ")" )
   - CAN Number (short text)
   - Fiscal Year (single-select)
      - The user is typically going to select the current fiscal year, but occasionally will want to select fiscal years into the future
      - There will be data from past fiscal years (I don't know how far back MAPS goes)
      - They would ideally not have to add additional fiscal years to the options list as times goes by
   - CAN Description (short text)
   - CAN Nickname (short text)
   - CAN Purpose (long text)
   - Amount Available (currency)
   - Amount Budgeted (current) (currency)
   - Additional Amount Anticipated (currency, inc negative values)
   - Arrangement Type (single-select)
      - The value options are unlikely to change.  They are: OPRE Appropriation, Cost Share, IAA, IDDA, MOU (with OPRE Appropriation being the most commonly selected value)
   - Source (single-select)
      - The value options are the agencies listed in the Agencies table
   - CAN Authorizer (single-select)
      - The value options are the agencies listed in the Agencies table
   - OPRE Team Leader (single-select)
      - The value options are the people listed in the Personnel table with Role = Team Leader or Budget Officer
   - OPRE Division (pulls in the Division associated with the Team Leader selected)
   - Notes (long text)

### Additional Context
* We want to do as best we can to set this up the way we think it will be for real, but details around field names, field types, value options, etc should be expected to change as we get user feedback.
* This issue is purely focused on understanding and clarifying all the details before the actual implementation, those will be in separate issues

### Resources
* [All about CANs and CAN Management](https://docs.google.com/spreadsheets/d/15MpMpSZWMhqMTJJ2akFdtuJy6f6iVJJriSmQ4ERAQ7E/edit#gid=1780400632) (background, user stories, data model)

**Comment by amymok** [comment]
@ninamak under Personnel, Role (multi-select), does that mean each personnel can have more than one role?

**Comment by ninamak** [comment]
@amymok Below are responses to your questions.  FYI that I spent the most time working out requirements around the CANs table, and the requirements around Personnel and Agencies have been less worked out and are bare minimum to support the CANs table and start getting feedback.

> Personnel: Role (multi-select) -- does that mean each personnel can have more than one role? Up to the amount of available roles?

Yes.  Currently, people in MAPS are only allowed to be assigned to one role, and it's a challenge because (for example) sometimes a Team Leader is also a COR.  There are two main reasons I'm aware of why someone would care what a person's role is: so they know who is responsible for what/who to contact, and because it affects their permissions in the system.  We haven't yet done enough user research to figure out how to model the relationship between people and roles moving forward, so this single Role field as a multi-select was meant to be an MVP implementation that we can use to move forward and elicit feedback.   

> Personnel: Do you see personnel to be different from user of the system? What I mean is that will all personnel have access to the system, and are all users personnel?

Currently, there are personnel who are not users of the system.  I don't know yet if that will be the case moving forward.  But looking ahead, we know that OPRE will want to use this system for workforce planning, which means being able to track all personnel's activities and expenses regardless of whether or not they're a user.  

Not all users are OPRE personnel.  For example, they have test users, and the devs are users, we are users, etc.  

I can also imagine a case where they want to enter info about people who are neither personnel nor users.  E.g., people from other agencies whose signatures they need on requisitions.  They may want to capture who those people are, their email addresses, etc. 

There are many, many user stories around what tracking they want to do around people, and we haven't dived into those yet.  So this is again meant to be just enough to support CANs, and we will likely have to come back and make changes as we tackle other user stories.  Even the use of the word "personnel" to name this table is MVP.  

> CAN: Fiscal Year (single-select) -- this means that each CAN will only happen in one Fiscal Year? There will not be CAN with same name/number but with different Fiscal Year?

CANs that span fiscal years do keep the same number.  A unique row would be the combo of CAN # and Fiscal Year.  

> CAN: Amount Available (currency), Amount Budgeted (current) (currency), Additional Amount Anticipated (currency, inc negative values) -- do they add up to each other?

No.  Amount available is the portion of the Amount Budgeted that has been added to their account and is available to spend.  Additional Amount Anticipated is money beyond the Amount Budgeted that is being talked about but hasn't been confirmed yet.  Ideally, at the end of the fiscal year, Amount Available and Amount Budgeted will be the same, and Additional Amount Anticipated will be $0.

> CAN: Source (single-select) -- Some Airtable entries are showing more than one source, should this be multi-select?

Good call.  Only the IAA CAN will have multiple sources (because they decided to create one CAN to contain all their IAAs).  I'm still not sure this is the right long-term solution, because it makes it impossible to see how much money came from which sources (since all the IAA money is lumped together), but it is their current state and not a high priority for them to fix at the moment.

**Comment by amymok** [comment]
@ninamak Thanks for the clarification.  I am mostly gathering information to see if there are more "caveats" we should implement.  If those info is unknown yet, that's totally fine!  Some more questions:

Roles: COR, Non-COR/Contractor, Team Leader, Division Director, Budget Officer, *Administrator*
- Do these roles dictate what access they have in the system?
- "Administrator", is this an administrator in the system or nothing related to that?
- So only COR cannot be Non-COR/Contractor then?  Any other restrictions?

>What difference does it make if all personnel are users or not? 
Django has a user model out of the box, I am trying to understand how related Personnel is to it, i.e. if they have some user actions and also auth included, or just purely informational.  This will help me understand if there's should be some linkage (relationship, and what kind of relationship) between the two.  If we don't really know yet, we can revisit as well.  And we can make it simple for now where Personnel has no user actions for now and no linkage to user.

>CANs that span fiscal years do keep the same number. A unique row would be the combo of CAN # and Fiscal Year.
If that's the case, what information will actually be the same across all the same CAN # regardless of the Fiscal Year?

>CAN:Budget Lines
This is included in Airtable but not in the information above, are we leaving that out for now?  If not, tell me more about this field.

>No. Amount available is the portion of the Amount Budgeted that has been added to their account and is available to spend. Additional Amount Anticipated is money beyond the Amount Budgeted that is being talked about but hasn't been confirmed yet. Ideally, at the end of the fiscal year, Amount Available and Amount Budgeted will be the same, and Additional Amount Anticipated will be $0.
So this sounds like there is some validation checks that need to happen, may be we can think about that later as well.  But at the mean time, it sounds like (Amount Available is smaller or equal to Amount Budgeted) and (Amount Available is smaller or equal to Amount Budgeted + Amount Anticipated)?
Do we anticipate a check that runs at the end of the fiscal year to show amount available = amount budgeted, and amount anticipated = 0?

>Good call. Only the IAA CAN will have multiple sources (because they decided to create one CAN to contain all their IAAs). I'm still not sure this is the right long-term solution, because it makes it impossible to see how much money came from which sources (since all the IAA money is lumped together), but it is their current state and not a high priority for them to fix at the moment.
How do we tell if the CAN is IAA CAN right now?

**Comment by ninamak** [comment]
@amymok 

Re: roles & personnel & users & permissions: We don't have requirements around all this yet.  Primary goal here was to have some dummy tables and dummy data so we could see what the Django Admin interface looks like.

To avoid scope creep, I'd suggest just keeping this as a Personnel table so that we don't have to answer questions about user roles & permissions yet.  And we can keep the Personnel table requirements to a minimum, just what's needed to support CAN reporting and not worry about people/role management.  In other words, let's not use the Django user model, and let's not worry about restrictions on what values can be assigned to a person.  And, to answer your question about "Administrator," that was meant to be an OPRE admin (e.g., Naomi), not a sys admin.  I'm not sure "Administrator" is the word they'd like to use, though, so it's a placeholder.

> what information will actually be the same across all the same CAN # regardless of the Fiscal Year?

Things like CAN Description, CAN Purpose, CAN Authorizer, basically everything other than Fiscal Year and the Amounts, will be the same across fiscal years.  Do you think, given this info, that this would be better to model as 2 tables?

> CAN:Budget Lines

That field is an artifact in AirTable that basically indicates two tables are linked.  Since we're not implementing Budget Lines right now, you can ignore it completely.

> So this sounds like there is some validation checks that need to happen, may be we can think about that later as well

In general, I'm inclined to wait on validation checks until we are implementing create/edit workflows.  But (Amount Available is smaller or equal to Amount Budgeted) is probably a reasonable check.  Not sure there's value to (Amount Available is smaller or equal to Amount Budgeted + Amount Anticipated).  And a check that runs at the end of the fiscal year to show amount available = amount budgeted, and amount anticipated = 0 is definitely beyond the scope of this story.  We'd want to find out what kind of budget reconciliation processes they do and how best to support that broadly rather than one-off.

> How do we tell if the CAN is IAA CAN right now?

G99IA14 is the general IAA CAN.  FYI that, for some reason, they do have a couple IAAs that are their own individual CANs.  That's going to be another question they'll have to resolve when we talk about data cleanup.

**Comment by amymok** [comment]
@ninamak 

>Do you think, given this info, that this would be better to model as 2 tables?

Yes.  I am breaking it out into two models in the database, CAN Info (which is those info that is the same across fiscal year). and CAN Amount (which is those amount and other fields you mentioned that's different).  For the admin interface, we can have a display model that combines both models together for admin to edit all in one place.

>IAA CAN - Source

For Source right now, I am going to keep it multi-select for now.  Let me know if you think it shouldn't be.

**Comment by amymok** [comment]
I have created a [spreadsheet](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=1007464314) to keep track of all the models.  In addition, a corresponding [ER diagram](https://docs.google.com/drawings/d/106BT0UIW_-zmocmNWMoGbe4nVmHGU1fYfsQWnTccsiI/edit) to visualize their relationships.

These are ready for review.  @ninamak I am happy to walk you through them since we have mostly doing this async.

@carjug feel free to ask me questions about these.

I am planning to do the following:
- Compiles a list of questions and things that we will need to think about.  I am not sure where to best store that.  I can continue to add it in the spreadsheet unless y'all have some other place you think that fits better.
- Adds new issues that will actually implement those models (after you review the above).  During eng co-work, we decided that we should break the task up into smaller tasks, and with this task focuses more about designing and clarifying what needs to be implemented.

**Comment by ninamak** [comment]
@amymok FYI that I've been gathering questions we have about requirements [here](https://docs.google.com/spreadsheets/d/15MpMpSZWMhqMTJJ2akFdtuJy6f6iVJJriSmQ4ERAQ7E/edit#gid=1780400632) (starting at row 79) and have been incorporating questions that you raised, though I may have missed some.

I noticed the spreadsheet has some of the same questions that are in this thread, but without the responses.  Which do you want to be the source of truth / reference?

Would be great to get a walk through!

**Comment by amymok** [comment]
@ninamak Nice, thank you!  Yes, it seems more fitting to include in your document.  I will take a look to see if there's more.

**Comment by carjug** [comment]
Hi Amy!! This all looks good to me. The only question I still have is about the need for a Division table. It doesn't seem like those things would change/need to be updated that often in order to justify its own table. Wondered if we could get clarity on this?? Thanks for the good. thorough work here!

**Comment by amymok** [comment]
@carjug Thanks for the reminder!  Will discuss.  I will still research a little bit more about having multiple roles.  I may just stumble upon a possible alternatives that can allow us to start multiple choices.  Will update here soon.

**Comment by ninamak** [comment]
Responding to: 

> The only question I still have is about the need for a Division table. It doesn't seem like those things would change/need to be updated that often in order to justify its own table. Wondered if we could get clarity on this??

Divisions (and roles) are unlikely to change very often, though they may change occasionally as the organization grows, and there is some chance that OPRE may make some changes in the next year or two.

**Comment by ninamak** [comment]
@amymok I was thinking about the validation checks on the Amounts and thinking we should wait on implementing any at all.  I have 2 reasons for this:

1. We haven't even confirmed with users beyond Sheila that these are the right Amounts to be showing people
2. We haven't incorporated spending yet and the impact that should have on these amounts

I'm in particular thinking of one scenario Sheila told us about, that we will need alignment from OPRE before deciding how to implement: Sometimes, OPRE signs an IDDA with another agency to _give_ them money.  This is basically just another way to spend money, _except_ unlike other times when money is spent, UFMS literally takes that money out of OPRE's CAN and gives it to another agency.  So the data and reporting around this are a bit complicated.  I can explain more when we meet if you want, it's hard to do in text.

**Comment by amymok** [comment]
After discussion with @ninamak today.  Here're my recommendations:
- We will not implement Division as a model at this point.
  - Since there's no additional information more than an abbreviated name for now, and it is infrequently enough that we will validate later if there's a use case to actually turn this into a table.
- We will still implement Role as a model because Person can have multiple roles.
  - It is easier to implement a table and use ManytoManyField to represent than using other options.  Other options such as [django-multiselectfield](https://pypi.org/project/django-multiselectfield/), or [Postgres Specific Arrayfield](https://docs.djangoproject.com/en/3.2/ref/contrib/postgres/fields/) may be used.  But to keep it simple, I would recommend we use Many-to-Many relationships, which means Role will stay as a model.  The django-multiselectfield allows us to do so but it is a 3rd party library, and it may make query/editing operations unnecessarily complicated down the line.  While the Postgres Specific Arrayfield also works, I prefer database-agnostic implementation.  So given that,  we will stick with implementing Role as model.
- We will not implement validation at this point.
  - We will show what we have for now and get more user feedback on what validations make sense.

I also cleaned up the spreadsheet a bit to answer any open questions or indicate questions that need to be revisited later.

I think this is ready to close.

@ninamak @carjug, any other thoughts?

**Comment by ninamak** [comment]
LGTM!

**Comment by carjug** [comment]
LGTM, Amy!
