### ISSUE TITLE
[8] View CANs

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#93]
### User story
As a PM/PO, I want to see what it would look like to view and edit CAN data in the Django interface so that I can provide feedback on how well it meets our needs.  

As a PM, I want to show our PO our initial data model so that we can feedback and refine it.

### Conditions of Acceptance
- [x] I can use Django Admin in the dev environment to see how much money is available to OPRE and for what purposes (based on dummy data).
- [x] I can test out the different out-of-box viewing and editing functionalities (or lack thereof).
- [x] It would be ok if the PM can only view the interface on a dev's local.

### Tasks
- [x] Implement CAN Info model based on [CAN Info tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=1853066578)
- [x] Implement CAN Amount model based on [CAN Amount tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=979139056)
- [x] Populate the tables with the dummy data in [AirTable](https://airtable.com/tblC1gcLbcE5wou4Z/viwkZHevQYTEb1rRF?blocks=hide)
- [x] Display the dummy data as a single table using the admin interface ([see CAN (Display Only) tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=1040321356))

**Comment by alexsoble** [comment]
Discussing this issue in Grooming with @ninamak. Nina is thinking that CANs are probably the most high value data for Sheila to start seeing and interacting with in development mode. For that reason, @ninamak is proposing a flow something like:

1. tackling CANs views first without all of the Agency, People, Roles relationships in place
2. next, implement Agency, People, Roles tables and views
3. associate CANs with Agency, People, Roles tables

We want your feedback on this idea @amymok, let's discuss either during coworking tomorrow or eng coworking Wednesday!

**Comment by ninamak** [comment]
@carjug Yesterday, Sheila mentioned a slight tweak that would improve the CANs view.  For "name" ([row 3 on the CAN (Display Only) tab](https://docs.google.com/spreadsheets/d/190drEOaOFH7cwCBM7eNB6vmnjICDiiShQiut7B55HCY/edit#gid=1040321356)), the requirements currently ask for this to be a concatenation of "number" + "nickname".  Could we also add "fiscal year"?  So, for example, a name might be "G994426 (HS) - 2021"

**Comment by carjug** [comment]
@ninamak should be easy enough!

**Comment by carjug** [comment]
@amymok @alexsoble ready for review when y'all are :)

**Comment by ninamak** [comment]
Recap of co-work convo on work remaining here:
* Incorporate PR feedback
* Create a list page with one row per CAN-FY, that looks like (has the columns displayed on) the [AirTable](https://airtable.com/appcKAO2OCBnHzgz8/tblC1gcLbcE5wou4Z/viwkZHevQYTEb1rRF?blocks=hide)
  * There is no need to be able to click into any of the list items
* Modify the list page of CANs to display the other columns that are part of the CAN Info data table

**Comment by carjug** [comment]
<img width="1439" alt="Screen Shot 2021-09-22 at 6 53 10 PM" src="https://user-images.githubusercontent.com/10871517/134440498-004e8682-3388-4e53-bbf1-803b5319c50f.png">
<img width="1438" alt="Screen Shot 2021-09-22 at 6 53 18 PM" src="https://user-images.githubusercontent.com/10871517/134440504-bdc86bf0-f90e-46dc-815c-86594afab981.png">

Hey @ninamak here are screenshots of the new table display (meant to mimic the airtable spreadsheet), if you want any tweaks let me know!

**Comment by ninamak** [comment]
@carjug this list view LGTM!  thank you!  if there are changes that come out of the PR review that impact things, let me know and i can take another look.

**Comment by alexsoble** [comment]
Removing my review label since I reviewed and approved the work, also removing @ninamak's and @amymok's since they did the same! 🎉 🚢
