### ISSUE TITLE
Usability Testing for progress to-date

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#943]
### Goals
* Have a plan we can use for the stories we have already delivered and deployed

### Tasks
- [x] Create research plan / testing approach
- [x] Additional outreach, as needed
- [ ] Schedule usability testing sessions
- [ ] Conduct testing sessions
- [ ] Synthesize notes / summarize what we learned and opportunities to improve the UI
- [ ] Create backlog items for UI improvements, prioritize with OPRE stakeholders

### Additional Context
- Includes usability testing for creating a research project, creating and agreement wit budget lines, and sending an agreement to approval (for planned status)
- Further usability testing would get conducted with each story as part of DoD
