### ISSUE TITLE
Create Feature Flags - Create Pre-Auth'd / No-Auth'd Environment

### ISSUE THREAD

**Issue by tdonaworth** [HHS/OPRE-OPS#963]
### Goals
Using OPS within DEV / STAGING without having to go through SSO or a Login process and for longer periods of time specifically to fulfill testing, usability demos, user training or other tasks

-----------------------------------------

### Tasks
- [x] Create a way to easily enable/disable features per release/deployment (Feature Flags)
- [x] Create a `default` user profile that is used when `Login` is clicked; which is assumed for all actions
- [x] BONUS: Create multiple user profiles, with different permissions, to enable quick/easy testing of authorization, or multi-user process flows (adding comments, modifying data as someone else, etc).

### Resources

**Comment by jonnalley** [comment]
@tdonaworth is this `dev-ready` ?

**Comment by jonnalley** [comment]
#970 took care of some of the asks of this backlog item already.  Part of the work necessary for feature flags are also being discussed and maybe handled in #1507. So close!

**Comment by jonnalley** [comment]
This was done via vite environment variables and not having the fakeauth requirements even present in production
