### ISSUE TITLE
An Approver reviewing a draft agreement with BL (planned status)

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#965]
### **User Story**
As a Division Director, I want to review submitted draft agreements from CORs/Team Leaders, so that an approval decision can be reached for inclusion in the OPRE planned budget.

### Preconditions
The DD already knows they have a contract/BLs to review based on notifications they got from #1471

### Acceptance Criteria
- [x] Newly-submitted agreement and budget lines should be reviewed (for approval in #967) first by the division director 
- [x]  The approver should be able to review at least the dollar amounts, CAN(s) chosen, and team members.
- [x]  As part of the approval process, a division director can be aware of how much remaining funds are available in the selected CAN(s) for the BLs as well as received vs. expected funds for the selected CAN(s).
- [x]  If the reviewed BLs will exceed the expected or available funds in the CAN, that should be abundantly clear to the division director

### Tasks
**UX**
- [x] Review research from #993 
- [x] Write out what additional documents/data might need to be provided (during submit to approval for the approver to review or for the approver to add as a part of their approval)
- [x]  Explore design options
- [x]  Share designs with OPRE stakeholders for feedback
- [x]  Refine the design based on feedback
- [x] Meet with Developers to discuss design and interactions
- [x] Share design options with DDs for feedback
  - [x] Determine what additional info the approvers need to provide (if any)
- [x] Refine the design based on feedback
- [x] Provide design assets with annotations to developers

**Doc**
- [x] Create sequence diagram

**Dev**

***Backend***
- [x] #1089 @xlorepdarkhelm 
- [x] #992 @johndeange 
  - Create an `Alert` endpoint, that returns all alerts for a User
  - Create an `Alert` endpoint, that returns only `active` alerts for a User
  - Create an `Alert` endpoint, that allows for updating an Alert, when a user dismisses or otherwise changes the status.
- [x] Look at / Update Sequence diagram and #1555
- [x] Create endpoints to query `workflows` based on Agreement ID / BLI IDs
  - [x] Create endpoint to return by workflow status
  - [x] Create endpoint to update the workflow status
  - [x] Create endpoint to return a status summary (for multiple agreements?)
  - [x] #1768

***Frontend***
- [x] #1655
  - [x] new table, new/updated columns (need to update existing table)
  - [x] hover area with new icon for go-to-approve page
  - [x] expanded area with agreement details
  - [x] include workflow step ID in links to approve page

### Definition of Done Checklist
- [ ]  UI works as designed
- [ ]  90%+ Code coverage achieved
- [ ]  PR(s) have been merged to main
- [ ]  Design/tech debt eliminated
- [ ]  Build process updated
- [ ]  Documentation updated or added
- [ ]  Feature flags/toggles created
 
###  Additional Context/Resources
* Depending on when #676 happens, should logging of the approval events be part of this story or included as part of that one ?
* Do we need more authz stuff and user roles in place as a pre-req first? #1399
* Which DD the approval goes to will be based on the portfolio and division tied to the CAN involved, unless @kimschulke  and @andressacurvelo's inquiries to the DDs proves otherwise. :-) 
* https://docs.google.com/document/d/18YDPPDbebc7bJn3XzhkKhP79YtmayL0xA0-tBz01eSM/edit

**Comment by kimschulke** [comment]
Draft questions to better understand the approval process - https://docs.google.com/document/d/1LTY7zwiHs8fAtMD4eVKZf9leQiRFdi5RLQ0qJd8hLuA/edit

**Comment by jonnalley** [comment]
some draft designs are in in place

**Comment by kimschulke** [comment]
As we are working on this... we are running into some complexities related to designing for the scenario when an agreement is cross-portfolio or even cross-division. Do we want to include those scenarios within this user story? or should we just design for a happy path and figure out the more complex scenarios next? @jonnalley thoughts?

**Comment by jonnalley** [comment]
Happy path, document the need for other stories or whatnot, and let’s move on

**Comment by jonnalley** [comment]
12/21
