### ISSUE TITLE
Approve BLs - Draft to Planned Status

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#967]
### **User Story**
As a Division Director, I want to approve submitted draft budget lines on an agreement that I have reviewed so that further action can be taken in the agreement's lifecycle.

### Acceptance Criteria

- [x]  Users with a valid role and responsibility for approving (DDs) should be able to approve the new draft agreement and budget line item submissions, having already reviewed them in #965
- [x]  As part of the approval process, a division director can approve to exceed the total funds that the CAN has been allotted for or has remaining, but the DD should be aware of this choice.
- [x]  Once an agreement and its BLs are approved, the BL status should change to "Planned"
- [x]  The approval action should get recorded accordingly in audit/history logging/tables including which BLs had the action taken, by whom, and when

### Tasks
**UX**
- [x] Review research from #993 
- [x] Write out what additional documents/data might need to be provided (during submit to approval for the approver to review or for the approver to add as a part of their approval)
- [x]  Explore design options
- [x]  Share designs with OPRE stakeholders for feedback
- [x]  Refine the design based on feedback
- [x] Meet with Developers to discuss design and interactions
- [x] Share design options with DDs for feedback
- [x] Provide design assets with annotations to developers

**Dev**
#### Backend
- [x] #1135 -  <--- Dev Ready ⭐ @xlorepdarkhelm 
  - Populate it with the outlined Applied Research, Evaluative Research, or Program Support
  - Create `GET` endpoint

#### Frontend
- [x] #1657
  - Review Agreement Details
  - [x] #1658
    - table different from review page (no selection)
  - Review CANs
  - Review Changes
  - [x] Check box for acknowledging subtraction
  - [x] validation before enabling Approve
- [x] Integrate with Workflow to pull in BLI Package
- [x] Button actions(Decline, Approve)
  - [x] Update BLIs to "Planned" status via Workflow
- [x] Add Submitter Notes - see Planned to Executing artboard

### Definition of Done Checklist
- [x] Usability validated
- [x]  UI works as designed
- [x]  90%+ Code coverage achieved
- [x]  PR(s) have been merged to main
- [x]  Design/tech debt eliminated
- [x]  Build process updated
- [x]  Documentation updated or added
- [x]  Feature flags/toggles created
 
###  Additional Context/Resources
* Depending on when #676 happens, should logging of the approval events be part of this story or included as part of that one ?
* Do we need more authz stuff and user roles in place as a pre-req first? #1399
* https://docs.google.com/document/d/18YDPPDbebc7bJn3XzhkKhP79YtmayL0xA0-tBz01eSM/edit
* Depends on the completion of: #1428

**Comment by tdonaworth** [comment]
I propose we allow #1806 to be it's own thing which this (967) isn't dependent on. As I feel like #1806 needs a little more refinement to flush out.

**Comment by jonnalley** [comment]
@tdonaworth so let it be written, so let it be done. 

12/21
