### ISSUE TITLE
[4] Set up CodeQL for static analysis

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#98]
### Goals
* Set up static analysis to check for security misconfigurations in our code. 

### Tasks
- [ ] Research how other 18F teams have set up GitHub CodeQL (e.g., FNS NAC)
- [ ] Research on GitHub docs on how to configure it
- [ ] Set it up

### Additional Context
* We don't want to set this up in the 18F repo; we'd want to set this up in the HHS repo #83 

### Resources
* Background on tech choice: #36 
* [Info on how to set up](https://docs.github.com/en/code-security/secure-coding/automatically-scanning-your-code-for-vulnerabilities-and-errors/setting-up-code-scanning-for-a-repository)
