### ISSUE TITLE
DevEx: Refactor Create Budget Lines

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#982]
### Goals

Refactor create budget line: refactor state, look for code/components that can be reused, etc.

### Tasks
- [x] refactor steps into their own components
- [x] use localState where possible
- [x] elevate reusable comps
state refactor with [Reducer and Context pattern](https://react.dev/learn/scaling-up-with-reducer-and-context)
  - [x] add bl from agreements select
  - [x] create new ones
  - [x] handle no budget lines
  - [x] edit 
  - [x] set bl to be edited
  - [x] cancel
  - [x] delete
  - [x] duplicate
  - [x] duplicate existing bli
  - [x] post?
  - [x] test agreements workflow
- [x] replace useEffects with global state from RTK
- [x] remove CreateBudgetLine slice
- [x] bug: budget lines are not posting from create Agreement workflow
- [x] fix/update unit-test and e2e

**Comment by fpigeonjr** [comment]
making progress 
<img width="1399" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/2e8989c4-7693-42d0-865f-3275a038a8ca">
