### ISSUE TITLE
global Alert refactor

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#983]
### Goals
Once one creates a new Agreement (or click on `Save Draft` button), should redirect to Agreements list and display alert above the table on that page.
Currently has a `StepAgreement Success` shows the alert and then redirects. 
### Tasks
- [x] add global state
- [x] remove `StepAgreementSuccess`
- [x] show success Alert above the `/agreements` list
- [x] allow for redirects or in-place
- [x] cleanup all Alerts to use dispatch

### Additional Context
- The table should appear right away and the success message appears at the top of that page - so its not one before the other, both at same time.
- same treatment for Save Draft in the Agreements workflow @kimschulke?

Probably look something like this but with the proper text for successfully creating an Agreement.
<img width="769" alt="image" src="https://github.com/HHS/OPRE-OPS/assets/4629398/f5b69195-88de-4c4f-8a61-00fed44da434">

### Resources
* [_Links to useful related info (e.g., articles, help docs, etc)_](https://flexion.slack.com/archives/C03LJ0NKZUG/p1683741867132999?thread_ts=1683740221.585889&cid=C03LJ0NKZUG)

**Comment by kimschulke** [comment]
Sounds right @fpigeonjr - thank you!

**Comment by tdonaworth** [comment]
> @tdonaworth /@johndeange, Do you think it makes sense for Alerts to have global state? Is is redux toolkit worthy? This use case requires for Alert to be triggered on the create Agreement workflow and the Alert be displayed on the Agreements list.

I think global should be fine here.

**Comment by fpigeonjr** [comment]
Thanks @tdonaworth, I'll add an `alertSlice` to handle state.
