### ISSUE TITLE
[8] Set up OWASP Zap for application scanning

### ISSUE THREAD

**Issue by ninamak** [HHS/OPRE-OPS#99]
### Goals
* Set up application scanning to find security flaws in our application from the point of view of external access

### Tasks
- [ ] Research how to set up OWASP Zap
- [ ] Add config to CI/CD pipeline
- [ ] Store OWASP Zap reports as HTML

### Additional Context
* We don't want to set this up in the 18F repo; we'd want to set this up in the HHS repo #83
* Dependent on #85 being completed
* Dependent on #86 being completed
* HTML report is an important artifact for our team and OCIO

### Resources
* [Weekly Docker image](https://hub.docker.com/r/owasp/zap2docker-weekly/)
* [Stable Docker image](https://hub.docker.com/r/owasp/zap2docker-stable)
