### ISSUE TITLE
Strategic Research on Agreement Approval Processes

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#993]
### Goals
* Understand the implications, mechanics, and concepts around the approval of an agreements moving from draft to planned status
* Have enough tactical research performed to better inform specific UX tasks for our user stories #675, #965, and #967

### Tasks

- [x]  Create research plan / outline questions
- [x]  Schedule interviews with DDs (suggestions: Hilary Bruck, Maria Woolverton)
- [x]  Conduct research as needed about current process and ideal future processes
- [x]  Explore design options
- [x]  Develop or update the user workflow / process map, if needed
- [x]  Share designs with stakeholders and other OPRE team members for feedback
- [x]  Refine the design based on feedback
- [ ]  Provide design assets with annotations to developers (Designs for #675, #965, and #967)

### Additional Context
*

**Comment by kimschulke** [comment]
Draft questions to better understand the approval process - https://docs.google.com/document/d/1LTY7zwiHs8fAtMD4eVKZf9leQiRFdi5RLQ0qJd8hLuA/edit

**Comment by kimschulke** [comment]
Conducted interviews with two Division Directors on 5/31 and 6/9. 

Scheduled two more interviews with Team Leads for 6/27 and 6/29.

**Comment by kimschulke** [comment]
I think our research is complete for now. We have a more solid understanding of how agreements and BLIs move through each status across FYs with the various tags and labels. The diagram we validated with Sheila will be helpful in moving forward and I think we are ready get back into designing the submit for approval and reviewer/approver process.
