### ISSUE TITLE
Azure IaaS vs. PaaS

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#998]
### Goals
* With a minimal time investment, make an initial determination about whether to initially pursue PaaS in Azure (App Service) vs. IaaS (something like Container Instances) as part of our evaluation
* Getting more familiar with the approaches, limitations, and requirements of these different Azure features

### Tasks
- [x] Configure and deploy a relevant container using App Service
- [x] Configure and deploy a relevant container using Container Instances
- [x] Configure and deploy a relevant container using ???
- [x] If time permits, experiment with ancillary services that would be required (API Management, Application Gateway, ACR)

### Resources
* _Links to useful related info (e.g., articles, help docs, etc)_

**Comment by jonnalley** [comment]
we've initially done container instances and decided against app service.  Could use Functions too for backend. would use statically hosted files in Storage Accounts for the frontend
